### ISSUE TITLE
PyTorch-Transformers: Add support for version 1.1.0

### ISSUE THREAD

**Issue by stefan-it** [zalandoresearch/flair#1000]
Hi,

version *1.1.0* of `pytorch-transformers` was released a few hours ago.

For RoBERTa, Flair currently uses the `torch.hub` functionality and uses the `fairseq` implementation. With *1.1.0* RoBERTa support was added to `pytorch-transformers`. I'll change the `RoBERTaEmbeddings` implementation to use the `pytorch-transformers` implementation.

Changelog can be found [here](https://github.com/huggingface/pytorch-transformers/releases).

**Comment by alanakbik** [comment]
Thanks for your great work as always @stefan-it! 

(and what a great ticket to celebrate our 1000th issue :))

**Comment by stefan-it** [comment]
Merged and fully available in latest *0.4.3* version of Flair 🤗
