### ISSUE TITLE
model optimization dev scores always 0

### ISSUE THREAD

**Issue by anjapago** [zalandoresearch/flair#1007]
I used the code from the tutorial on model optimization: https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_8_MODEL_OPTIMIZATION.md

And the output in loss.tsv shows devs scores always as 0, is this the expected behaviour?

EPOCH	TIMESTAMP	BAD_EPOCHS	LEARNING_RATE	TRAIN_LOSS	DEV_LOSS	DEV_PRECISION	DEV_RECALL	DEV_F1
0	18:52:16	0	0.1500	9.603234402905262	9.539236068725586	0.0	0.0	0.0
1	18:55:43	1	0.1500	9.593898497647684	9.531429290771484	0.0	0.0	0.0
2	18:59:03	2	0.1500	9.517001741598962	9.461878776550293	0.0	0.0	0.0
3	19:02:21	3	0.1500	9.32978164322157	9.427535057067871	0.0	0.0	0.0
4	19:05:41	4	0.1500	9.153932962363925	9.473787307739258	0.0	0.0	0.0
5	19:08:58	1	0.0750	8.945433283836264	9.607274055480957	0.0	0.0	0.0
(continues for 21 epochs)

Also, in param_selection.txt, for every evaluation run I am always getting: 
score: 1.0
variance: 0.0
test_score: 0.0

Thanks.

**Comment by marcelgwerder** [comment]
@anjapago Ever figured out why this happened?

**Comment by anjapago** [comment]
I think I traced it down to an issue with my corpus. I had mixed up the order of columns e.g.: column_name_map = {4: "text", 1: "label_topic", 2: "label_subtopic"},  and the issue was fixed after I got my corpus fixed (if I am remembering correctly).
