### ISSUE TITLE
NER - Slow predictions on master branch compared to version 0.4.2

### ISSUE THREAD

**Issue by pommedeterresautee** [zalandoresearch/flair#1012]
**Describe the bug**
With the very same code, and the very same data, Inference is much more slower on NER task when I use the version on master branch compared to the released version 0.4.2 (from 84 seconds to 234 seconds).
I have tried storing method None, cpu and gpu (btw documentation is missing, in particular none option is not clear to me even when reading the code)

FYI training the model doesn't take more time on master branch.
nvidia-smi tells me that during inference the GPU is used at 10-12% when using master, and at 25 to 30% when using 0.4.2

**To Reproduce**
```python
#  ...
    corpus: Corpus = prepare_flair_train_test_corpus(spacy_model=nlp, data_folder=data_folder, dev_size=dev_size)

    model_path = os.path.join(model_folder, 'best-model.pt')
    tagger: SequenceTagger = SequenceTagger.load(model_path)

    test_results, _ = tagger.evaluate(DataLoader(corpus.test, batch_size=50, num_workers=10))
    print(test_results.detailed_results)

    sentences_predict: List[Sentence] = corpus.train.sentences + corpus.test.sentences

    start = time.time()
    _ = tagger.predict(sentences_predict, mini_batch_size=50, verbose=True, embedding_storage_mode="gpu")
    print(time.time() - start)
    # 234 seconds on when using master branch
```
The training of the model looks like this:

```python
   # ...
    embedding_types: List[TokenEmbeddings] = [
        WordEmbeddings('fr'),
        FlairEmbeddings('resources/flair_ner/lm/ca_forward/best-lm.pt'),
        FlairEmbeddings('resources/flair_ner/lm/ca_backward/best-lm.pt'),
    ]

    embeddings: StackedEmbeddings = StackedEmbeddings(embeddings=embedding_types)

    tagger: SequenceTagger = SequenceTagger(hidden_size=256,
                                            embeddings=embeddings,
                                            tag_dictionary=tag_dictionary,
                                            tag_type='ner')
   # ...
```
Here it is a custom LM, but `fr` model from Zalendo has the same behaviour.

**Expected behavior**
I expect the time to process the same data with the same NER model to be the same than with master and 0.4.2.

**Environment (please complete the following information):**
Ubuntu 19.04
Flair master VS Flair 0.4.2
GPU 2080TI

**Comment by alanakbik** [comment]
Oha thanks for spotting this. Definitely something we need to investigate!

**Comment by alanakbik** [comment]
Again thanks for spotting this. I was able to reproduce and find the source of the problem. The new version does not only return the most likely tag but also a probability distribution over all tags in case you want to know what the second best guess was etc. However, it seems the implementation of this feature imposes a CPU bottleneck, hence the slowdown and reduced GPU usage. 

I'll push a PR that adds an optional flag to the `predict()` method that if not set will not do this distribution.` evaluate()` by default will not return the distribution. This speeds everything back up. Here the numbers of a v100: 

**Task - evaluating CoNLL-03 'ner' model**
_Release 0.4.2_:   ~30 seconds
_Current master_: ~40 seconds
_After fix_:             ~20 seconds

**Task - predict on all sentences in CoNLL-03 wirh 'ner' model**
_Release 0.4.2_:   ~100 seconds
_Current master_: ~190 seconds
_After fix_:             ~85 seconds

**Comment by alanakbik** [comment]
@pommedeterresautee just pushed the PR to master. Could you check if this works for you?

**Comment by pommedeterresautee** [comment]
I confirm that master is even more rapid than 0.4.2.
Thanks for the rapid fix!
