### ISSUE TITLE
SIGKILL when training NER model

### ISSUE THREAD

**Issue by fsonntag** [zalandoresearch/flair#102]
I'm trying to train an NER model based the [train.py example](https://github.com/zalandoresearch/flair/blob/master/train.py) based on the latest master branch.
Training is done on CPU with GloVe and forward and backward CharLMEmbeddings with a batch size of 32, no downsampling is done.

Sometime during training in between 200 to 400 iterations within the first epoch the python process is getting killed with a SIGKILL.
I have watched the memory usage of flair and it slowly increases over time until the process gets killed.

I tried training on different machines with different memory sizes (16GB and 32GB), and different operating systems (Ubuntu, CentOS and Mac OS).
I also tried using PyTorch 0.4.1 instead of 0.4.0

Unfortunately, I can't really track down the concrete issue.

**Comment by fsonntag** [comment]
Thanks a lot for the response! Highly appreciated.
The fast embeddings didn't help, but not putting them in memory worked :)

So what memory size would you recommend for training if one would like to keep the embeddings in memory?

**Comment by alanakbik** [comment]
Sure! If the embeddings don't fit in memory I would really recommend using the '-fast' language models unless you have a lot of time.

**Comment by fsonntag** [comment]
Okay, I'm just wondering what memory size is suitable, because the '-fast' language models also don't seem to fit into 16GB memory...

**Comment by alanakbik** [comment]
Ah ok! So total iterations on CoNLL-03 is about 650, so if you get to 400 iterations, you would need maybe about 1.5-2 times the RAM. So 64GB should work here!

**Comment by fsonntag** [comment]
Great, thanks a lot for the feedback :) I'll close the issue then!

**Comment by fsonntag** [comment]
@alanakbik 
On a related note (I don't want to create a new issue), are there plans for releasing fast german LM embeddings?

**Comment by alanakbik** [comment]
Yes! The next release will probably contain a much larger library of different types of LM embeddings, including fast ones and more languages!

**Comment by fsonntag** [comment]
Great, very much appreciated!
