### ISSUE TITLE
XLNet, RoBerta model size 

### ISSUE THREAD

**Issue by DecentMakeover** [zalandoresearch/flair#1033]
Currently the size of these models are over a GB, FlairEmbeddings('news-forward') on the other hand is about 500 Mb, 

Is there a way to reduce the size of these models(XLNet, RoBerta etc)

Thanks in advance.

**Comment by stefan-it** [comment]
@DecentMakeover you should definitely checkout out this [awesome blog post](https://medium.com/huggingface/distilbert-8cf3380435b5) about "distilling" a BERT (base, uncased) model 🤗

The so called "DistilBERT" model will be integrated into Flair (hopefully very soon, this PR #1044 ).

**Comment by stefan-it** [comment]
Additionally, I think the PyTorch-Transformers guys are currently working on an implementation that allows to prune several attention heads, which could also decrease the model size. (WIP on the [`pruning-save-and-load` branch](https://github.com/huggingface/pytorch-transformers/compare/pruning-save-and-load))

**Comment by DecentMakeover** [comment]
@stefan-it Thanks for your input and i saw your reference pull request too, i was wondering what was the size of the DistillBert model?Would you mind sharing?

Thanks

**Comment by thomwolf** [comment]
Hi, the weights file is 255 MB for the current 66M parameters DistilBert model.

**Comment by DecentMakeover** [comment]
Thanks a lot
