### ISSUE TITLE
Add support for DistilBERT

### ISSUE THREAD

**Issue by stefan-it** [zalandoresearch/flair#1041]
Hi,

based on this [great blog post](https://medium.com/huggingface/distilbert-8cf3380435b5) about model "distillation" and an implementation in PyTorch-Transformers, we can easily support the so called *DistilBERT* model.

> Overall, our distilled model, DistilBERT, has about half the total number of parameters of BERT base and retains 95% of Bert’s performances on the famous language understanding benchmark GLUE

I made some preliminary experiments with DistilBERT and Flair on the (full) CoNLL-2003 corpus and the result is only 0.74% behind the BERT (base) model. More comparisons can be found [here](https://github.com/stefan-it/flair-experiments/blob/master/conll2003-ner-english/README.md).

The NER model size and training time decreased ~ 50%!

I'll add *DistilBERT* as an extension to the `BertEmbeddings` layer :)

**Comment by pommedeterresautee** [comment]
Hi, I may miss something, have you done some compare versus Flair language model? 
Speed and F1?

**Comment by stefan-it** [comment]
I'll try to add the training times to the table (includ. some comparisons to the Flair Embeddings) :)

Yes, I could try to run the DistilBERT model with your CRF-PR to compare the speed improvements 🤗

**Comment by stefan-it** [comment]
Support for DistilBERT is now merged and available on the `master` branch, so I'm closing here 🤗
