### ISSUE TITLE
Flair v 0.4.3: wrong parameter names in description of release 0.4.3

### ISSUE THREAD

**Issue by krzysztoffsiuwa** [zalandoresearch/flair#1042]
Hi,

it's great you're keeping this whole repo so up-to-date!

I found that in https://github.com/zalandoresearch/flair/releases/tag/v0.4.3 in "Optimizations" section you introduce "amp=True" parameter, however in https://github.com/zalandoresearch/flair/blob/master/flair/trainers/trainer.py in line 86 there is "use_amp" parameter.

Similar issue takes place with described in "Optimizations" "embedding_storage_mode", which in
https://github.com/zalandoresearch/flair/blob/master/flair/trainers/trainer.py in line 78 is called "embeddings_storage_mode".

After correcting these typos the training runs.

**Comment by stefan-it** [comment]
@krzysztoffsiuwa Thanks for reporting that :+1: 

I updated the release notes 🤗

**Comment by alanakbik** [comment]
@krzysztoffsiuwa thanks for spotting this - @stefan-it thanks for updating! :)
