### ISSUE TITLE
ELMo Token Embedding by Word

### ISSUE THREAD

**Issue by andreaoclarksevilla** [zalandoresearch/flair#1046]
Hello,

I was wondering, is there a way to access the embedding of a particular word token by providing the actual word instead of the token number for the word in the sentence?

Thank you!

**Comment by alanakbik** [comment]
Hi @andreaoclarksevilla - could you clarify with what you mean by "providing the actual word"? The general problem is that a sentence may contain the same word multiple times, so providing the word as a string alone will not always be enough to select the correct word.

**Comment by andreaoclarksevilla** [comment]
Yes, I meant providing the word as a string, but you make a good point that I didn't consider. Thank you for your help!
