### ISSUE TITLE
Loading CoNLL-03 corpus throws TypeError: unsupported operand type(s) for /: 'str' and 'str'

### ISSUE THREAD

**Issue by m-michalek** [zalandoresearch/flair#1048]
I downloaded the CoNLL-03 dataset from [this repo](https://github.com/patverga/torch-ner-nlp-from-scratch/tree/master/data/conll2003) into the `/resources/tasks/conll_03/` directory and executed following code:

`from flair.datasets import CONLL_03`
`corpus: Corpus = CONLL_03(base_path='resources/tasks')`

But I get the following error:
<img width="933" alt="Bildschirmfoto 2019-08-30 um 11 40 44" src="https://user-images.githubusercontent.com/20742170/64010995-13e76c80-cb1b-11e9-9b3a-e51226924c3e.png">

What am I missing here?

**Environment (please complete the following information):**
 - OS: macOS 10.14.6.
 - Version: 0.4.2.

Thanks for any help!

**Comment by alanakbik** [comment]
Hi @m-michalek can you update to Flair 0.4.3? This should be fixed in the newest version.

**Comment by m-michalek** [comment]
This works perfectly, but I use version 0.4.2. because I get the following error if I want to evaluate a model with version 0.4.3.

I used following code to demonstrate the error:

`from flair.datasets import Sentence`
`from flair.models import SequenceTagger`

`tagger = SequenceTagger.load('ner')`
`corpus = Corpus([Sentence('Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt')],[Sentence('Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt')],[Sentence('Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt')]) `

`result, _ = tagger.evaluate(corpus.test)`

<img width="795" alt="Bildschirmfoto 2019-08-30 um 12 03 03" src="https://user-images.githubusercontent.com/20742170/64012526-28793400-cb1e-11e9-9e12-1644ef9456c4.png">

**Comment by alanakbik** [comment]
Ah yes, that is because the interface for the `evaluate()` function has changed. It now needs a flair `DataLoader`, i.e.: 

```python
from flair.datasets import DataLoader

result, _ = tagger.evaluate(DataLoader(corpus.test))
```

You can parameterize the `DataLoader` for your requirements, for instance by increasing the mini-batch size: 

```python
result, _ = tagger.evaluate(
    DataLoader(corpus.test, batch_size=32, shuffle=False, num_workers=8)
)
```

**Comment by m-michalek** [comment]
Thank you now everything works fine!
