### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'en-sentiments'

### ISSUE THREAD

**Issue by imratnesh** [zalandoresearch/flair#1049]
I am running code in google colaboratory 

`classifier = TextClassifier.load('en-sentiments') `

and getting error
**FileNotFoundError: [Errno 2] No such file or directory: 'en-sentiments'**

**Comment by stefan-it** [comment]
@imratnesh Could you try to use the latest *0.4.3* version? With that version I was able to load the model :)

**Comment by alanakbik** [comment]
@imratnesh there's a typo in the model name, you can load it like this: 
```python
classifier = TextClassifier.load('en-sentiment')
```

**Comment by imratnesh** [comment]
@alanakbik It works. Thanks.
