### ISSUE TITLE
ELMo Embeddings return empty tensor

### ISSUE THREAD

**Issue by lambdaofgod** [zalandoresearch/flair#1050]
**Describe the bug**
I get empty tensor when I try to run ELMo Embeddings.

**To Reproduce**
```
from flair import embeddings as flair_embeddings
from flair.data import Sentence

elmo_model = flair_embeddings.ELMoEmbeddings()

sentence = Sentence("I love to code")
elmo_model.embed(sentence)[0].embedding
```

Gives

> tensor([])

**Environment (please complete the following information):**
 - Ubuntu 18.04
> >>> flair.__version__                                         
> '0.4.3'                                                       
> >>> allennlp.__version__                                       
> '0.8.5'

**Comment by stefan-it** [comment]
I'll check it :)

**Comment by brytjy** [comment]
I assume you want to extract the embedding for the first token.

This works,

elmo_model.embed(sentence)[0]**[0]**.embedding

**Comment by stefan-it** [comment]
Just call the `embed` function without any index access:

```python
elmo_model.embed(sentence)
```

Then you can access the embedding of each token:

```python
sentence[0].embedding
```

or for all tokens:

```python
for token in sentence.tokens:
  print(token.embedding)
```

:)

**Comment by lambdaofgod** [comment]
Ok, it's not a bug, it's just confusing. I thought that if every token has an embedding, I should be able to call embedding of whole sentence, and it would just return concatenated embeddings.
