### ISSUE TITLE
Runtime error -training a text classifier on Google Colab

### ISSUE THREAD

**Issue by Shivanandroy** [zalandoresearch/flair#1051]
**Describe the bug**
RuntimeError: Expected object of backend CUDA but got backend CPU for sequence element 413 in sequence argument at position #1 'tensors'

**To Reproduce**
from flair.data_fetcher import NLPTaskDataFetcher
from flair.embeddings import WordEmbeddings, FlairEmbeddings, DocumentLSTMEmbeddings
from flair.models import TextClassifier
from flair.trainers import ModelTrainer
from pathlib import Path
corpus =  NLPTaskDataFetcher.load_classification_corpus(Path('.'))
word_embeddings = [WordEmbeddings('glove'), FlairEmbeddings('news-forward-fast'), FlairEmbeddings('news-backward-fast')]
document_embeddings = DocumentLSTMEmbeddings(word_embeddings, hidden_size=512, reproject_words=True, reproject_words_dimension=256)
classifier = TextClassifier(document_embeddings, label_dictionary=corpus.make_label_dictionary(), multi_label=False)
trainer = ModelTrainer(classifier, corpus)
trainer.train('./', max_epochs=10)

**Environment (please complete the following information):**
 - Google Colab
 - Flair (0.4.3)
![2019-08-31 05_38_33-Untitled2 ipynb - Colaboratory](https://user-images.githubusercontent.com/25221992/64059749-dda8fc00-cbb1-11e9-8c16-a21d230b721d.png)

**Additional context**

**Comment by alanakbik** [comment]
Hi @Shivanandroy the `NLPTaskDataFetcher` class is deprecated and has been replaced by `flair.datasets` methods. You can load a fast text formatted corpus [like this](https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_6_CORPUS.md#fasttext-format). You can now also load a classification corpus directly from a CSV file, [like this](https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_6_CORPUS.md#reading-a-text-classification-dataset).

Could you try with the new methods and see if this fixes the error?

**Comment by AshviniKSharma** [comment]
> Hi @Shivanandroy the `NLPTaskDataFetcher` class is deprecated and has been replaced by `flair.datasets` methods. You can load a fast text formatted corpus [like this](https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_6_CORPUS.md#fasttext-format). You can now also load a classification corpus directly from a CSV file, [like this](https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_6_CORPUS.md#reading-a-text-classification-dataset).
> 
> Could you try with the new methods and see if this fixes the error?

I am facing the same issue, I replaced NLPTaskDataFetcher with flair.datasets but the issue is still there 
![Screenshot from 2019-09-27 16-26-24](https://user-images.githubusercontent.com/44145699/65764636-b9562600-e143-11e9-8ada-18b2fb7c8920.png)

**Comment by alanakbik** [comment]
Hello @AshviniKSharma - the `DocumentLSTMEmbeddings` class was also deprecated a few Flair versions ago. Could you try the `DocumentRNNEmbeddings` instead? See also our [tutorial on text classification](https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_7_TRAINING_A_MODEL.md#training-a-text-classification-model).

**Comment by AshviniKSharma** [comment]
Thanks a lot, @alanakbik, I think this one is the fastest reply I ever got on my query. Issue solved.
Thanks,
Ashvini Kumar Sharma
