### ISSUE TITLE
Flair overriding user logging config

### ISSUE THREAD

**Issue by Kotwic4** [zalandoresearch/flair#1059]
**Describe the bug**
During import Flair set the root logger to WARN overriding any user provided basicConfig(see [__init__.py#L40](https://github.com/zalandoresearch/flair/blob/master/flair/__init__.py#L40)).

This is problem for me, because I am creating python microservice with flair and I need to have logs from system.

**To Reproduce**
```
import logging
logging.basicConfig(
    format="%(asctime)s : %(levelname)s : %(message)s", level=logging.INFO
)
logging.info("First info")

import flair
logging.info("Second info")

logging.basicConfig(
    format="%(asctime)s : %(levelname)s : %(message)s", level=logging.INFO
)
logging.info("Third info")
```
Only the first log will be present.

**Expected behavior**
All user log should be present

**Screenshots**
![image](https://user-images.githubusercontent.com/10147099/64147236-eb63b900-ce1f-11e9-842d-4bdbbf61c870.png)

**Environment (please complete the following information):**
 - OS [e.g. iOS, Linux]: Ubuntu 18.04.3 LTS
 - Version [e.g. flair-0.3.2]: Flair-0.4.3

**Additional context**
Related issuses:
https://github.com/zalandoresearch/flair/issues/282
https://github.com/zalandoresearch/flair/issues/415

**Comment by alanakbik** [comment]
@Kotwic4 this was potentially fixed with PR #1063 - could you check on current master branch if the problem is fixed for you?

**Comment by Kotwic4** [comment]
Yes, this PR fixed my problem. Thank you :)

**Comment by BertrandMiannay** [comment]
It seems this bug is back
