### ISSUE TITLE
Flair v. 0.2.1 segfaults on big text with special characters when CPU-only torch build is used

### ISSUE THREAD

**Issue by hcl14** [zalandoresearch/flair#106]
Python version 3.6.5, Ubuntu 18.04.1

Segfault seem to occur not in torch, but in Flair (see below).

The use-case is somewhat incorrect, as here Flair is used to tokenize not sentence, but a big text paragraph, but sometimes it is impossible to properly tokenize the text, so such errors occur in real world usage. The error does not occur with either: 1) GPU version of torch, or 2) when I use nltk to tokenize sentences in text first, and then run flair tagger sentence by sentence. However, in the second case the code works longer.

It seems that problem persists with ordinary torch package on CPU-only machine (I have seen this bug on AWS EC2 node), but I cannot verify the latter right now.

Steps to reproduce:

1. create python3 venv:
```
$ python3 -m venv test_env 
$ source test_env/bin/activate
```
2. install CPU-only build of torch v.0.4.0 (as flair requires) - or you can try using standard package on CPU-only machine:
```
(test_env) $ pip install --upgrade pip
(test_env) $ pip install http://download.pytorch.org/whl/cpu/torch-0.4.0-cp36-cp36m-linux_x86_64.whl
```
3. install Flair:
```
(test_env) $ pip install flair
```

4. Download text file from here: 
https://drive.google.com/file/d/18z2rBOzBybHpP_9ttr7yY-KFMwZbVGkf/view?usp=sharing

5. Run the following python code in venv:

*frair_segfault.py*:
```
print("Loading NER")
from flair.models import SequenceTagger
from flair.data import Sentence
tagger = SequenceTagger.load('ner') 
print("NER loaded")

with open("textdata.txt", "r") as f:
    sent_txt = f.read()

sentence = Sentence(sent_txt)
tagger.predict(sentence)
```

```
(test_env) $ python3 -i flair_segfault.py
Loading NER
NER loaded
Segmentation fault (core dumped)
```

You can add this piece of code at the beginning of `frair_segfault.py` to find segfault place more precisely:

```
from inspect import currentframe, getframeinfo, stack

def tracefunc(frame, event, arg, indent=[0]):
    if event == "call":
        indent[0] += 2
        print("-" * indent[0] + "> call function {}".format(frame.f_code.co_name))
    elif event == "return":
        print("<" + "-" * indent[0], "exit function {}".format(frame.f_code.co_name))
        indent[0] -= 2
    elif event == "line":
        caller = getframeinfo(stack()[1][0])
        print("%s:%d" % (caller.filename, caller.lineno))
        #print("<" + "-" * indent[0], "exectuting code: {}".format(frame.f_code.co_name))
    elif event == 'exception':
        print('ERROR:')
        exception, value, traceback = arg
        print(exception)
        print(value)
        print(traceback)
    return tracefunc

import sys
sys.settrace(tracefunc)
```

Last lines of the output:
```
----------------------> call function linear
/home/hcl/Documents/work/test/test_env/lib/python3.6/site-packages/torch/nn/functional.py:990
/home/hcl/Documents/work/test/test_env/lib/python3.6/site-packages/torch/nn/functional.py:992
<---------------------- exit function linear
<-------------------- exit function forward
/home/hcl/Documents/work/test/test_env/lib/python3.6/site-packages/torch/nn/modules/module.py:492
/home/hcl/Documents/work/test/test_env/lib/python3.6/site-packages/torch/nn/modules/module.py:498
/home/hcl/Documents/work/test/test_env/lib/python3.6/site-packages/torch/nn/modules/module.py:511
<------------------ exit function __call__
/home/hcl/Documents/work/test/test_env/lib/python3.6/site-packages/flair/models/language_model.py:78
<---------------- exit function forward
/home/hcl/Documents/work/test/test_env/lib/python3.6/site-packages/flair/models/language_model.py:100
----------------> call function repackage_hidden
/home/hcl/Documents/work/test/test_env/lib/python3.6/site-packages/flair/models/language_model.py:106
/home/hcl/Documents/work/test/test_env/lib/python3.6/site-packages/flair/models/language_model.py:107
<---------------- exit function repackage_hidden
/home/hcl/Documents/work/test/test_env/lib/python3.6/site-packages/flair/models/language_model.py:102
<-------------- exit function get_representation
Segmentation fault (core dumped)
```

This is as much as I can investigate with my knowledge.

**Comment by stefan-it** [comment]
What's the available RAM of the Amazon machine? I tried your example code with the provided test data and it worked on my machine (CPU-only), prediction took ~ 4.3 GB of RAM. I'm using Python 3.7, a recent `master`  version and pytorch in version `'0.4.1.post2`.

So just check the available memory of your amazon instance and try to use a recent version of `flair` with the latest pytorch version. I hope this would solve the error :)

**Comment by hcl14** [comment]
I used current master branch:

```
$ pip install git+https://github.com/zalandoresearch/flair
```

No success.

**Comment by alanakbik** [comment]
Cool, thanks for debugging this! This really shows that we need to update to the latest torch. We will fix this in the next release!
