### ISSUE TITLE
tags_proba_dist returns empty dict

### ISSUE THREAD

**Issue by m-michalek** [zalandoresearch/flair#1060]
Shouldn't the following code not return the probability distribution over all classes?

`from flair.datasets import WIKINER_ENGLISH`
`from flair.models import SequenceTagger`

`corpus = WIKINER_ENGLISH().downsample(0.99)`
`tagger = SequenceTagger.load('ner')`

`tagger.predict(corpus.train[10])`
`for token in corpus.train[10]:`
`    print(token.tags_proba_dist)`

![image](https://user-images.githubusercontent.com/20742170/64171731-a5284d00-ce53-11e9-879d-d23600b204af.png)

**Environment (please complete the following information):**
 - OS: macOS 10.14.06
 - Version: 0.4.3.

**Comment by pommedeterresautee** [comment]
You need to set in `predict` the option `all_tag_prob` to `True`
https://github.com/zalandoresearch/flair/blob/master/flair/models/sequence_tagger_model.py#L363

**Comment by m-michalek** [comment]
Thank you!
