### ISSUE TITLE
Similarity learning

### ISSUE THREAD

**Issue by yosipk** [zalandoresearch/flair#1065]
Feature request

Many problems in machine learning can be cast as similarity learning e.g. multi-media retrieval, question answering, paraphrase detection. It would be nice to have a class that supports this downstream task.

Similarity is a function that compares two objects (e.g. two sentences) and produces a scalar that reflects the degree of similarity. The higher the scalar the more similar objects are. The implementation could operate on level of embeddings, i.e. each object is embedded into a vector, and similarity operates on the embeddings. To learn similarity one usually uses labeled pairs. The class constructor could be provided by source and target embeddings, a similarity function and loss function.

**Comment by pommedeterresautee** [comment]
In search (reranking) and recsys, this is very useful. Usually, there are positive pairs (true similars) and negative pairs. I read this WE a recent paper from Zalando (forgot the title) on recsys having some strategies to prune positive and negative examples... showing how that part is important.

If you think to implement something like that, having the power to control weighting and negative examples provides usually a nice performance boost without adding too much complexity to the architecture.
Another point coming to my mind, there is a very simple library from Fb well thought and quite general doing such stuff: [starspace](https://github.com/facebookresearch/StarSpace), link to the paper is also provided on Github. 
I use it from time to time to test ideas, it s really a nice lib.
However its capacity to modelize is limited by its simple architecture (shallow nn), I am wondering how better it would be if it can leverages LM and so on...
The way they formulate things, the file format, etc. can be an inspiration for a similarity API in Zalando Flair.

**Comment by alanakbik** [comment]
@pommedeterresautee cool thanks for the pointer to the starspace repo - we'll definitely check it out!

Closing this issue for now as first version was added to master in PR #1066 - but this is work in progress so more similarity learning features, datasets, documentation etc. will follow.

**Comment by yosipk** [comment]
> In search (reranking) and recsys, this is very useful. Usually, there are positive pairs (true similars) and negative pairs. I read this WE a recent paper from Zalando (forgot the title) on recsys having some strategies to prune positive and negative examples... showing how that part is important.
> 
> If you think to implement something like that, having the power to control weighting and negative examples provides usually a nice performance boost without adding too much complexity to the architecture.
> Another point coming to my mind, there is a very simple library from Fb well thought and quite general doing such stuff: [starspace](https://github.com/facebookresearch/StarSpace), link to the paper is also provided on Github.
> I use it from time to time to test ideas, it s really a nice lib.
> However its capacity to modelize is limited by its simple architecture (shallow nn), I am wondering how better it would be if it can leverages LM and so on...
> The way they formulate things, the file format, etc. can be an inspiration for a similarity API in Zalando Flair.
