### ISSUE TITLE
Sentence() indexing behaves strangely when running on CPU

### ISSUE THREAD

**Issue by kyoungrok0517** [zalandoresearch/flair#107]
Hi, I found out that on CPU, no matter what model I load (`news-forward`, `news-forward-fast`), the 0-th element of `Sentence()` is `None`, which should be the first Token in the textual sentence. I'm running on **macOS High Sierra 10.13.6**, and **PyTorch 0.4.1**. 

I see
```python
Sentence("He like apple .")[0] = None
```
Which should be
```python
Sentence("He like apple .")[0] = Token: He
```

**Comment by alanakbik** [comment]
Hm, yes you're right - thanks for reporting this! We'll fix it!

**Comment by alanakbik** [comment]
It seems it currently uses the token id, which begins at 1. So, you can get the first token with `Sentence("He like apple .")[1]`. But we will fix this in the next version!

**Comment by tabergma** [comment]
It was already fixed and merged into the master branch (see https://github.com/zalandoresearch/flair/issues/62). 
The feature will be included in the next release.

**Comment by alanakbik** [comment]
Ah yes! Ok, so it will be part of release 0.3. Or if you use the current master branch instead of installing through pip then it's already fixed now!
