### ISSUE TITLE
Keep word embedding tensors on pinned cpu memory during training

### ISSUE THREAD

**Issue by alanakbik** [zalandoresearch/flair#1079]
If `embeddings_storage_mode = 'cpu'` is selected during training, all word embedding tensors are moved to CPU memory and are at each epoch copied over to GPU memory when processing a mini-batch. It's possible to pin tensors so that the GPU copy operation becomes faster. The drawback is that pinning tensors is costly, so this would increase the time needed for the first epoch (which creates and pins the tensors) but would decrease the time needed for all subsequent epochs (since copy operations are now faster). 

Task: Add tensor pinning to training routine and investigate how this impacts training speed.

**Comment by pommedeterresautee** [comment]
I have a PR coming for that. Basically I setup a LRU cache for embeddings in CUDA.
