### ISSUE TITLE
Fix cuda out of memory issue for text classification

### ISSUE THREAD

**Issue by tabergma** [zalandoresearch/flair#108]
When training a text classifier on large datasets, the trainer runs into memory problems. 
Investigate why we are running into out of memory issues and fix them.

**Comment by stefan-it** [comment]
I can confirm that issue. Currently I'm trying to train on the GermEval 2018 dataset, and passing `embeddings_in_memory=False` to the `train` function helps :)

**Comment by tabergma** [comment]
@stefan-it It seems like the evaluation method takes a lot of memory and causes the `cuda out of memory` problems. We are looking into it.

Yesterday we fixed a bug in training a text classifier on a single label task (see https://github.com/zalandoresearch/flair/issues/109). So in case you used single label training, you might want to try again with the current version in the master branch.

**Comment by tabergma** [comment]
We could not find any memory leak. However, training a text classifier on a large data set which contains large documents/sentences using contextual string embeddings is quite expensive and can lead to out of memory issues. To avoid this, you can now
(1) disable the evaluation on the training data set
(2) use a smaller batch size for evaluation
