### ISSUE TITLE
embedding_length of CharacterEmbeddings

### ISSUE THREAD

**Issue by yahshibu** [zalandoresearch/flair#1083]
https://github.com/zalandoresearch/flair/blob/3c93339ff69b5d827822228f17ee075e880db195/flair/embeddings.py#L1532

I think the following is correct:
```python
        self.__embedding_length = self.hidden_size_char * 2
```

When the value of "self.char_embedding_dim" is not equal to that of "self.hidden_size_char" with the current implementation, it will not work properly.

**Comment by alanakbik** [comment]
@yahshibu - thanks for spotting this! Would you like to put in a PR to fix this?

**Comment by yahshibu** [comment]
@alanakbik  Thanks. Yes, I'll do it!
Is it OK to create a branch from v0.4.3 tag?

**Comment by alanakbik** [comment]
Easiest would be from current master, then there's fewer problems in automatic merging!
