### ISSUE TITLE
Does flair contain any pre-train character embedding to use?

### ISSUE THREAD

**Issue by RichardHWD** [zalandoresearch/flair#1086]
Does flair contain any pre-train character embedding to use?

**Comment by pommedeterresautee** [comment]
Flair Language Model is a character based language model.
It can download those pretrained models for many languages. You can check this tuto to see how to use them https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_7_TRAINING_A_MODEL.md

More info on the language model itself here:
https://github.com/zalandoresearch/flair/blob/master/resources/docs/embeddings/FLAIR_EMBEDDINGS.md

**Comment by RichardHWD** [comment]
Thanks, and I can`t load common_characters from https://s3.eu-central-1.amazonaws.com/alan-nlp/resources/models/common_characters. Did they remove?
