### ISSUE TITLE
When restarting from checkpoint, the model is trained more than max_epochs

### ISSUE THREAD

**Issue by lucaventurini** [zalandoresearch/flair#1087]
**Describe the bug**
As in the title, when loading a model that was already trained for some epochs, setting max_epochs parameter trains for *further* max_epochs.

**To Reproduce**
I saved a checkpoint after 3 epochs. When I load this checkpoint and run with max_epochs=3, I see epoch 4, 5, 6 get executed.

**Expected behavior**
The above behavior could make sense, but I'd really like to set the **total** max epochs (or my jobs can potentially never end if they keep getting interrupted and restored).

So, in the example above, I would expect that no further epochs are trained.

Alternatively, how can I read how many epochs were already trained when I load the checkpoint?

**Comment by alanakbik** [comment]
hello @lucaventurini this should be fixed in master branch. Can you check if it works for you?

**Comment by lucaventurini** [comment]
Hi @alanakbik , the update seems to work as expected.

I'd only mention that it breaks the loading of a checkpoint made with old code:
```python
/usr/local/lib/python3.6/dist-packages/torch/serialization.py:454: SourceChangeWarning: source code of class 'flair.embeddings.DocumentRNNEmbeddings' has changed. you can retrieve the original source code by accessing the object's source attribute or set torch.nn.Module.dump_patches = True and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/usr/local/lib/python3.6/dist-packages/torch/serialization.py:454: SourceChangeWarning: source code of class 'flair.embeddings.StackedEmbeddings' has changed. you can retrieve the original source code by accessing the object's source attribute or set torch.nn.Module.dump_patches = True and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/usr/local/lib/python3.6/dist-packages/torch/serialization.py:454: SourceChangeWarning: source code of class 'flair.embeddings.WordEmbeddings' has changed. you can retrieve the original source code by accessing the object's source attribute or set torch.nn.Module.dump_patches = True and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
Traceback (most recent call last):
  File "train_flair.py", line 163, in <module>
    sys.exit(main(sys.argv[1:]))
  File "train_flair.py", line 155, in main
    trainer = ModelTrainer.load_checkpoint(check_file, corpus)
  File "/usr/local/lib/python3.6/dist-packages/flair/trainers/trainer.py", line 489, in load_checkpoint
    model.corpus = corpus
AttributeError: 'dict' object has no attribute 'corpus'
```

I personally don't need to load old checkpoints though.

Thank you for the fix!
