### ISSUE TITLE
Add support for Multilingual Flair Embeddings

### ISSUE THREAD

**Issue by stefan-it** [zalandoresearch/flair#1099]
Hi,

I trained multilingual Flair Embeddings for over 300 languages on the [JW300](https://www.aclweb.org/anthology/P19-1310/) corpus.

The training corpus consists of 2,025,826,977 token (2B) and was trained for 5 epochs. Thanks to half precision support this could be done in 10 days on a V100 😅 (so the total training time for both forward and backward language model was 20 days).

The model can be downloaded from:

```bash
$ wget https://schweter.eu/cloud/flair-lms/lm-jw300-forward-v0.1.pt
$ wget https://schweter.eu/cloud/flair-lms/lm-jw300-backward-v0.1.pt
```

To use it in Flair:

```python
from flair.embeddings import FlairEmbeddings

jw_forward = FlairEmbeddings("lm-jw300-forward-v0.1.pt")
jw_backward = FlairEmbeddings("lm-jw300-backward-v0.1.pt")
```

More details can be found in [this repo](https://github.com/stefan-it/flair-lms#multilingual-flair-embeddings).

Additionally, I made a few experiments for PoS tagging on the Universal Dependencies v1.2 dataset. It seems that this new multilingual language model can achieve comparable results to a multilingual BERT model. More details can be found in [this repository](https://github.com/stefan-it/flair-pos-tagging), including a multilingual evaluation of (mono-lingual) Flair Embeddings.

I would like to thank Željko Agić (@zeljkoagic) for giving me early access to the JW300 corpus  🤗

**Comment by pommedeterresautee** [comment]
Bravo!
Made any check NER score on classical datasets? Vs dedicated language Flair LM?

**Comment by zeljkoagic** [comment]
Happy to see our dataset put to good use, nice results! Cite if you use, share alike, you know the drill!

**Comment by alanakbik** [comment]
This is awesome @stefan-it! Should we add it as the new default for 'multi-forward' and 'multi-backward'  in `FlairEmbeddings`? I could reupload these models on our server and add this in a PR.

**Comment by stefan-it** [comment]
@pommedeterresautee Thanks :) Experiments on WikiANN are definitely on my todo list for autumn 😅
