### ISSUE TITLE
CSVClassificationCorpus encoding problems

### ISSUE THREAD

**Issue by ristonen** [zalandoresearch/flair#1106]
Hi,

Hopefully this is not something already fixed!

I tried to load my own corpus like explained in tutorial: https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_6_CORPUS.md

I created train.csv, test.csv and dev.csv containing Finnish text with ä, ö, Ä and Ö. Seemed to be fine with encoding = 'utf-8'. Checking the file with code below, it contained this text: "osittain sähkö / mittari puuttua".
dev_set = pd.read_csv(datafolder+'dev.csv', encoding = "utf-8", sep = ',')
print(dev_set['viesti'][0])

Then I loaded corpus with this line:
corpus: Corpus = CSVClassificationCorpus(datakansio,column_name_map,skip_header=True,delimiter=',')

And checking corpus with code below, the text was changed to this: "osittain sÃ ¤ hkÃ ¶ / mittari puuttua". Encoding had changed somehow, and all ä, ö, Ä and Ö did broke.
print(corpus.dev[0])

 - OS: Windows
 - Version: Python 3.7.1, flair 0.4.3, torch 1.2.0

**Comment by eurekaqq** [comment]
On my ubuntu computer and Windows computer, it prints out the correct words.
Maybe you can try the last version flair on github.

**Comment by ristonen** [comment]
Thanks, I’ll try it

**Comment by ristonen** [comment]
@eurekaqq 
Stupid question: is there a newer version than 0.4.3 to install? Some beta version?

**Comment by eurekaqq** [comment]
@ristonen yeah. in pip, the latest version is 0.4.3, But you can clone from github, and using it.

**Comment by ristonen** [comment]
Thanks @eurekaqq 
It works perfectly! Sorry, I'm new with GitHub :) I close this now.
