### ISSUE TITLE
Bug "training your own embeddings"

### ISSUE THREAD

**Issue by felipenv** [zalandoresearch/flair#1109]
Following the tutorial on how to train the embeddings in my own corpus I got an issue:

my structure is exactly the same as in the example:
├── corpus
│   ├── test.txt
│   ├── train
│   │   ├── train_split11
│   │   ├── train_split12
│   │   ├── train_split13
│   │   ├── train_split14
│   │   ├── train_split15
│   └── valid.txt
...

Running using flair 0.4.3, GPU NVIDIA Tesla V100 32GB, 300GB RAM, 100cpus, and in total my corpus has 1.4GB only for this test. I'm running for testing just the exact parameters as in the example.

the error:
**ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).**

What I can tell is that in this server I can't believe there's any issue of memory. How do I fix this?

**Comment by BernierCR** [comment]
Did you check the shared memory? That server has lots of memory, but maybe something is low about the shared kind. You aren't trying to run this from WSL right? I wouldn't expect WSL on a beefy server like that.

**Comment by felipenv** [comment]
> Did you check the shared memory? That server has lots of memory, but maybe something is low about the shared kind. You aren't trying to run this from WSL right? I wouldn't expect WSL on a beefy server like that.

I ran it straight in the Server (ssh connection, docker) Really had all resources available. Is there an issue with 0.4.3 version?

**Comment by stefan-it** [comment]
When you're using (nvidia-) docker then you need to increase the shm size. Just pass --shm-size=300G to your docker run command :)

**Comment by felipenv** [comment]
> When you're using (nvidia-) docker then you need to increase the shm size. Just pass --shm-size=300G to your docker run command :)

I was using --memory=300g instead of shm-size. 
Now it works! thanks!
