### ISSUE TITLE
"unexpected EOF. The file might be corrupted" when loading model

### ISSUE THREAD

**Issue by krzysztoffsiuwa** [zalandoresearch/flair#1118]
Hi,

i have most probably the same issue with one of the LM (XLNetEmbeddings()) as described in a closed issue: https://github.com/zalandoresearch/flair/issues/52.

I looked into '''~/.flair''' there is a folder called "embeddings" and inside i see only:
en-fasttext-news-300d-1M glove.gensim.vectors.npy
en-fasttext-news-300d-1M.vectors.npy news-backward-0.4.1.pt
glove.gensim news-forward-0.4.1.pt

Is there any other place where flair stores the downloaded LMs? I have downloaded and used successfully other i.e. RoBERTaEmbeddings(), OpenAIGPT2Embeddings() so they should be somewhere there but i can't find them.

I'd appreciate some help!

**Comment by alanakbik** [comment]
The transfomer models are handled by the `pytorch-transformers` package so they are not downloaded into the ''~/.flair'' folder like the other embeddings. Have you found where these embeddings are downloaded to on your machine?

**Comment by krzysztoffsiuwa** [comment]
Sorry for the delay and thanks for information. I found here https://huggingface.co/pytorch-transformers/model_doc/overview.html#cache-directory that "Usually, if you don’t set any specific environment variable, pytorch_pretrained_bert cache will be at ~/.cache/torch/pytorch_pretrained_bert/". In my case this wasn't BERT, i was interested in XLNet, and the auto-created path was ~/.cache/torch/pytorch_transformers, but in fact changing name of this folder helped: after trying to run these embeddings again the auto-download created a new pytorch_transformers folder and downloaded the model. So generally one should look in ~/.cache/torch.
