### ISSUE TITLE
How to load the checkpoint of a customized ner model and do prediction

### ISSUE THREAD

**Issue by JiajunBao** [zalandoresearch/flair#1120]
I trained a ner model with flair and saved the checkpoint. Is there any tutorial on how to load it to do prediction? I just find one for the built-in tagger. Thank you.

**Comment by alanakbik** [comment]
Hello @JiajunBao you can load a checkpoint as done in the code example [here](https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_7_TRAINING_A_MODEL.md#resuming-training).

**Comment by JiajunBao** [comment]
I guess you are referring to this part. Is there an option to link to the checkpoint?
`# 5. initialize sequence tagger
from flair.models import SequenceTagger

tagger: SequenceTagger = SequenceTagger(hidden_size=256,
                                        embeddings=embeddings,
                                        tag_dictionary=tag_dictionary,
                                        tag_type=tag_type,
                                        use_crf=True)`

**Comment by alanakbik** [comment]
Actually I was referring to the last part in the code example, i.e. 

```python
# load the checkpoint
from pathlib import Path
checkpoint = tagger.load_checkpoint(Path('path/to/checkpoint.pt'))

# restore the trainer from loaded checkpoint
trainer = ModelTrainer.load_from_checkpoint(checkpoint, corpus)

# train anew
trainer.train('resources/taggers/example-ner',
              learning_rate=0.1,
              mini_batch_size=32,
              max_epochs=150,
              checkpoint=True)
```

Note that this is true for the latest Flair release (0.4.3). On master branch, the semantics have changed. Here you only need to do the following: 

```python
# restore trainer from checkpoint
trainer = ModelTrainer.load_checkpoint(checkpoint, corpus)

# train anew
trainer.train('path/to/checkpoint.pt',
              learning_rate=0.1,
              mini_batch_size=32,
              max_epochs=150,
              checkpoint=True)
```

This will become the new way of doing this in the next Flair release (0.4.4).

**Comment by JiajunBao** [comment]
Thanks!
