### ISSUE TITLE
Model taking too much GPU memory

### ISSUE THREAD

**Issue by DecentMakeover** [zalandoresearch/flair#1124]
I have trained a model, and the size of that model is 386MB, but when i load the model to get predictions, 1.2GB of my GPU memory gets utilised.Does anyone have any idea why this happens, i was under the impression that only 400MB would be used.

Thanks in advance.

**Comment by pommedeterresautee** [comment]
The size it takes on GPU RAM is not the same than the serialized version of the model. Moreover, check the storage option on predict() function. GPU option will lead you to a OOM error if your dataset is large.

**Comment by DecentMakeover** [comment]
@pommedeterresautee  Thanks for the response, i was wondering what you meant by ` GPU option will lead you to a OOM error if your dataset is large`,because my confusion is during inference you will predict for a single sentence right?

**Comment by DecentMakeover** [comment]
also what should be the ideal option in predict function if your running it on CPU?

**Comment by absaravanan** [comment]
> also what should be the ideal option in predict function if your running it on CPU?

Hi, I think it should be "none"

**Comment by pommedeterresautee** [comment]
Basically if the memory storage is set to GPU, each representation of each token is stored in the token. And it's just a pointer toward an array somewhere in the GPU RAM. In this situation no garbage collection will happen. And at the end, if you make many predictions, you will finish to saturate your memory.

As said by @absaravanan , none is usually the good option.

**Comment by DecentMakeover** [comment]
@pommedeterresautee Thanks for the response.
