### ISSUE TITLE
Why each letter is encoded in UTF-8?

### ISSUE THREAD

**Issue by pommedeterresautee** [zalandoresearch/flair#1133]
I am wondering why in the disctionnary each letter is encoded in UTF-8.
It increases computation pressure during training and inference and I don't see what it brings in exchange. Moreover, it makes iterating over character harder (forcing us to proceed to the computation on each char instead of applying it to the string).

https://github.com/zalandoresearch/flair/blob/master/flair/data.py#L42

**Comment by alanakbik** [comment]
Hm good question - I am struggling to remember why we did this tbh :) Perhaps it can be removed.

**Comment by pommedeterresautee** [comment]
Disabling it (with a full re encoding of the dict first) doesn't seem to hurt the performance. 
But I think that all the released/trained models will stop to work... as the model contains the dict. Am I right?

**Comment by alanakbik** [comment]
Yes I think so, the only way to address this would be to extend the deserialization method so that the dictionary gets converted before loading.

**Comment by pommedeterresautee** [comment]
Another approach would be to have a dirty conversion during the first call of get char index, and clean code in the init. new model will use the clean code, old ones will use the dirty code. In 1 or 2 Flair release, dirty code is deleted.
Extending de-serialization would create some technical debt forever. Honestly, I have contributed a lot to XGBoost long time ago, me and others have written lots of dirty code to add some not core features without any cleaning strategy for the future... let's say we still pay it a lot (as you know speed of XGboost is not on par compared to Msft boosting lib... ). I have the feeling that Flair with its modular by design approach may last quite some time... so you see my point ;-)
