### ISSUE TITLE
pip install not working due to encoding error in README

### ISSUE THREAD

**Issue by NilsRethmeier** [zalandoresearch/flair#114]
TLDR;
The README needs a (unicode) fix

Got error,
```
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    long_description=open("README.md").read(),
  File "/home/rethmeier/miniconda3/envs/PT0.4/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2539: ordinal not in range(128)
```
Emptied the README.md file.

Now `python setup.py install` on a cloned flair repo worked.

**Comment by alanakbik** [comment]
Oha very strange. What system are you installing on? Are you installing from pipy or from master branch?

**Comment by stefan-it** [comment]
Hi, you should check the current locale for your shell, see this issue #67. Just use an utf8 locale :)

**Comment by alanakbik** [comment]
There was a pull request by @halidziya that was merged into the master branch a few hours ago. 

@NilsRethmeier could you try checking out the code again and see if isntall works without emptying the README?

**Comment by tabergma** [comment]
Closing issue as bug is fixed.
