### ISSUE TITLE
Change the tokenizer inside the model.

### ISSUE THREAD

**Issue by JiajunBao** [zalandoresearch/flair#1140]
I find the way the way to change tokenizer in the test stage.
```
# your text of many sentences
text = "This is a sentence. This is another sentence. I love Berlin."

# use a library to split into sentences
from segtok.segmenter import split_single
from flair.data import segtok_tokenizer

sentences = [Sentence(sent, use_tokenizer=segtok_tokenizer) for sent in split_single(text)]

# predict tags for list of sentences
tagger: SequenceTagger = SequenceTagger.load('ner')
tagger.predict(sentences)
```
Are we able to use customized tokenizers in the training stage?
Thank you.

**Comment by pommedeterresautee** [comment]
To train a NER you are supposed the provide a `TextCorpus` so you are free to use the tokenizer you like. Is there something special you need?

**Comment by JiajunBao** [comment]
I see. Thank you.

**Comment by bbruceyuan** [comment]
hello, how can I pass the tokenizer which implemented by myself?

I use the code:
```python
def my_tokenizer(x):
    # this is my tokenizer implementation
    # which is similar to space tokenizer
    # what I changed is replacing space with \x02.
    # because I wanna segment the sentence with \x02
# then I pass it into  Sentence
Sentence('hello\x02world',use_tokenizer=my_tokenizer)
```
but it doesn't work. So how can implement my personal tokenizer?

what I can find is  [this comment in flair.data](https://github.com/zalandoresearch/flair/blob/5d62c8be1884beff3a8ee2208feb9b282e209cfe/flair/data.py#L525). but I don't know how to do it?
