### ISSUE TITLE
Offline use of BertEmbeddings

### ISSUE THREAD

**Issue by felix-chan** [zalandoresearch/flair#1155]
I am trying to use Flair and `BertEmbeddings` in an offline machine. I had studied about it and I tried to download necessary resources and put it into the machine.

When I try to use `BertEmbeddings()`, 2 resources are required and I download it separately. They are 

 - https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt
 - https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased.tar.gz

And I put them into 
 - `/path/to/file/bert-base-uncased-vocab.txt`
 - `/path/to/file/bert-base-uncased.tar.gz`

However, I don't know how to pass the 2 locations correctly. I checked the source code:

https://github.com/zalandoresearch/flair/blob/release-0.4.1/flair/embeddings.py#L1056-L1075

`BertTokenizer.from_pretrained(bert_model_or_path)` and `BertModel.from_pretrained(bert_model_or_path)` are reading the same variable (`bert_model_or_path`). In my situation, they should be 

```python
        self.tokenizer = BertTokenizer.from_pretrained('/path/to/file/bert-base-uncased-vocab.txt')
        self.model = BertModel.from_pretrained('/path/to/file/bert-base-uncased.tar.gz')
```
What should I do?

**Comment by stefan-it** [comment]
@felix-chan The following should work with `BertEmbeddings()`:

Just create a folder `bert-base-uncased` and extract all files into it. That means, the following files must be located in that folder:

* `vocab.txt` -> Word piece vocabulary file
* `pytorch_model.bin` -> PyTorch-converted model weigths+
* `config.json` -> JSON-based configuration file, that describes the model

Then pass that path to the contructur, lile: BertEmbeddings(bert_model_or_path="/path/bert-base-uncased`)` :)

**Comment by felix-chan** [comment]
Thanks a lot. It works!
