### ISSUE TITLE
Outdated documentation?

### ISSUE THREAD

**Issue by MichalTurski** [zalandoresearch/flair#1162]
Isn't chapter **Non-Latin Alphabets** in **Tutorial 9: Training your own Flair Embeddings** outdated? I think it's workaround for issues closed by #1150. At least there should be mentioned   about new (bigger) dictionaries.

**Comment by alanakbik** [comment]
Yes good point - we always have the problem that many users install Flair through pip while others use the current master branch. If we update the documentation now it would cause errors for those users who installed through pip. 

This is one reason why we'd like to switch to a more frequent release. In fact, I'm planning to release 0.4.4 hopefully at the beginning of next week and then update all online documentation to make it consistent with all the fixes and changes introduced in the last month!

**Comment by MichalTurski** [comment]
@alanakbik Thanks for the response!
