### ISSUE TITLE
How do I extract POS tags in dictionary ?

### ISSUE THREAD

**Issue by anandhperumal** [zalandoresearch/flair#1164]
On using POS tags I get the output as a string, rather I'm expecting it in dictionary.

Output :
George \<PROPN\> Washington \<PROPN\> went \<VERB\> to \<ADP\> Washington \<PROPN> . \<PUNCT\> Dort \<ADV\> kaufte \<VERB\> er \<PRON\> einen \<DET\> Hut \<NOUN\> . \<PUNCT\>

Expected Output:
{ George : \<PROPN\>,
Washington: \<PRON\>,
went: \<VERB\>,
....
}

Below is the code, 
```
sentence = Sentence('I love Berlin .')
tagger = SequenceTagger.load('pos-multi')

tagger.predict(sentence)
print(sentence)
```

**Comment by stefan-it** [comment]
Here's a code snippet that produces a list of tuples (token -> tag):

```python
[(token.text, token.tags["upos"].value) for token in sentence.tokens]                                                                                                                                                          
Out[17]: [('I', 'X'), ('love', 'X'), ('Berlin', 'PROPN'), ('.', 'PUNCT')]
```

Dictionary wouldn' preserve word order (and to keep same tokens in a sentence would only be possible with a list as value)

**Comment by anandhperumal** [comment]
Thanks

**Comment by sarthakpan** [comment]
> Here's a code snippet that produces a list of tuples (token -> tag):
> 
> ```python
> [(token.text, token.tags["upos"].value) for token in sentence.tokens]                                                                                                                                                          
> Out[17]: [('I', 'X'), ('love', 'X'), ('Berlin', 'PROPN'), ('.', 'PUNCT')]
> ```
> 
> Dictionary wouldn't preserve word order (and to keep same tokens in a sentence would only be possible with a list as value)

This will not work anymore.
use this:
`[(token.text,token.labels[0].value) for token in sentence.tokens]`
