### ISSUE TITLE
how can I pass my personal tokenizer in Sentence Class?

### ISSUE THREAD

**Issue by bbruceyuan** [zalandoresearch/flair#1167]
hello, how can I pass the tokenizer which implemented by myself?

I use the code:
```python
def my_tokenizer(x):
    # this is my tokenizer implementation
    # which is similar to space tokenizer
    # what I changed is replacing space with \x02.
    # because I wanna segment the sentence with \x02
# then I pass it into  Sentence
Sentence('hello\x02world',use_tokenizer=my_tokenizer)
```
but it doesn't work. So how can implement my personal tokenizer?

what I can find is  [this comment in flair.data](https://github.com/zalandoresearch/flair/blob/5d62c8be1884beff3a8ee2208feb9b282e209cfe/flair/data.py#L525). I know that we can not pass a function to it, just as the comment read. but how can I complete my requirement?

thank you in advance!

**Comment by stefan-it** [comment]
Hi @bbruceyuan, a small example would be:

```python
from typing import List
from flair.data import Sentence, Token

def own_tokenizer(text: str) -> List[Token]:
    """
    Tokenizer based on space character only.
    """
    tokens: List[Token] = [Token(token) for token in text.split()]
    
    return tokens

s = Sentence("Berlin and Munich .", use_tokenizer=own_tokenizer)

print(s)
```

Make sure, that your own tokenizer is returning a List of `Token` objects :)

**Comment by bbruceyuan** [comment]
thanks for your reply. I do this implementation just like you. but it doesn't work. 

Just like your example. you split input text by space character. As a result, we got a `Sentence` with 4 `Tokens`. 

if you print the result `s`, you will get output `Sentence: "Berlin and Munich ." - 4 Tokens`.

But if you replace the code with:
```python
from typing import List
from flair.data import Sentence, Token

def own_tokenizer(text: str) -> List[Token]:
    """
    Tokenizer based on space character only.
    """
    tokens: List[Token] = [Token(token) for token in text.split('\x02')]
    
    return tokens

s = Sentence("Berlin\x02and\x02Munich\x02.", use_tokenizer=own_tokenizer)

print(s)
```
Just replace `split()` with `split('\x02')`. and the output should be
 `Sentence: "Berlin and Munich ." - 4 Tokens`
But now, we got 
`Sentence: "Berlin and Munich ." - 7 Tokens`

It's should be `4 Tokens`, because we split the text with `\x02`. 

So is there something wrong about my understanding of it?

**Comment by stefan-it** [comment]
@bbruceyuan Could you try the latest `master` version? I tried it with b81bf847f20d785abfccccab8e37d1a087fc6ded and the errors seems to be fixed now.

I'm getting:
```python
In [5]: print(s)                                                                                                                                                      
Sentence: "Berlin and Munich ." - 4 Tokens
```

now :)

**Comment by bbruceyuan** [comment]
@stefan-it 

just now, I have tried the `master` version and got the right result. 
It seems the bug was fixed.
