### ISSUE TITLE
Question about importing some functionalities

### ISSUE THREAD

**Issue by himkt** [zalandoresearch/flair#1169]
Hi all! Thank you for sharing the awesome nlp toolkit!
I have a question about `segtok_tokenizer` and some classes or methods in `flair.data`.

I'm new to flair.
After installed flair (v0.4.3) and segtok (v1.5.7), I followed the tutorial.

When I read [the document for tokenization](https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_1_BASICS.md#tokenization) and execute a sample code to find the error.

### Sample code

```python
(pipenv) $ cat seg.py
from flair.data import Sentence, segtok_tokenizer


# Make a sentence object by passing an untokenized string and a tokenizer
sentence = Sentence('The grass is green.', use_tokenizer=segtok_tokenizer)

# Print the object to see what's in there
print(sentence)
```

### Error I got

```bash
(pipenv) $ pipenv run python seg.py
Traceback (most recent call last):
  File "seg.py", line 1, in <module>
    from flair.data import Sentence, segtok_tokenizer
ImportError: cannot import name 'segtok_tokenizer' from 'flair.data' (/home/ubuntu/.local/share/virtualenvs/flair-59nyjY
io/lib/python3.7/site-packages/flair/data.py)
```

### My understanding and question

I read the code of flair and found the implementation of [segtok_tokenizer](https://github.com/zalandoresearch/flair/blob/15bfcb88c95ce634eedfcd649c0822728bf21c45/flair/data.py#L427-L465). So it seems not to be a bug, but I have no idea for the cause.😢So my question is what am I doing wrong?

### Misc
I attach the result of ipython's completion for `from flair.data import <TAB>`.

```
In [3]: from flair.data import
         abstractmethod()     DataPoint            Dictionary           iob_iobes()          logging              Span                 Token                word_tokenizer()     __package__
         ConcatDataset        Dataset              flair                Label                MultiCorpus          split_contractions() torch                __doc__
         Corpus               defaultdict          FlairDataset         List                 random_split()       split_single()       Tqdm                 __file__
         Counter              Dict                 iob2()               log                  Sentence             Subset               Union                __name__
```

Regards,

**Comment by doolingdavid** [comment]
I have the exact same issue.

**Comment by okiriza** [comment]
I think for now you can copy-paste the definition of segtok_tokenizer function from [flair/data.py](https://github.com/zalandoresearch/flair/blob/master/flair/data.py) at master branch to flair/data.py on your computer.

**Comment by alanakbik** [comment]
Hello all, this feature is only available in master branch currently. So if you install flair through pip it is not yet possible to specify your own tokenizer this way. 

If you want to have this feature now, you could work on master branch. For instance, you can install master like this: 
```console
pip install --upgrade git+https://github.com/zalandoresearch/flair.git
```

We will also release another version to pip soon, so if you can wait a week or so this feature will be also installable normally through pip.

**Comment by himkt** [comment]
It makes sense! Thanks @okiriza @alanakbik.
I install flair of master branch.
