### ISSUE TITLE
Contribution for support for the Danish Language

### ISSUE THREAD

**Issue by AmaliePauli** [zalandoresearch/flair#1176]
Hi,

I have trained Flair word embeddings on Danish using Wikipedia and Europarl corpus, and by using this a Part of Speech Tagger trained on the [Danish Dependency Treebank](https://github.com/UniversalDependencies/UD_Danish-DDT/blob/master/README.md) corpus. In our project we also annotated the Danish Denendecy treebank corpus with NER tags (LOC, ORG, PER), and trained a NER tagger using Flair. Here is the link to our github [DaNLP](https://github.com/alexandrainst/danlp).

I think it could be cool to contribute the models to the Flair framework such that it supports Danish. Is this something you are interested in and how can it be done?

Kind Regards
Amalie Pauli

**Comment by alanakbik** [comment]
Hello @AmaliePauli that would be great - we'd very much appreciate a contribution that adds support for Danish!

The easiest is if you send me the models and I re-upload them on our server and include them in the code. Otherwise, if you prefer to host the models on your server you could also do the PR yourself. Either way we'll make sure to reference DaNLP in the docs and code!

**Comment by stefan-it** [comment]
Hi @AmaliePauli really great project 🤗

Have you also performed a comparison with the recently integrated Danish Flair Embeddings 🤔 I did some benchmarks for PoS tagging with the current Danish Flair Embeddings on the Universal Dependencies v1.2 (see [here](https://github.com/stefan-it/flair-pos-tagging)) :)

**Comment by AmaliePauli** [comment]
Hi @alanakbik , That sound great, thanks. Here is a link to the models https://alexandrainstituttet-my.sharepoint.com/:f:/g/personal/amalie_nyhagen_alexandra_dk/Eoi-TL7IW8FLvE62BiQ47pMBm0ixshMY7ktWy8FQy7TCKQ
We plan to continue working on the models and hope to improved them using more data in the future (especially ner), and we also integrate the flair models in our framework.
@stefan-it cool that you have run comparison on PoS tagging, I have not seen before that you also have trained it for Danish, and I see that your Danish PoS tagger gets 98.51 where I got   97,14 based on a single run.

**Comment by alanakbik** [comment]
Thanks - I think the 'da-ner' and 'da-pos' files might be empty in the folder?

**Comment by AmaliePauli** [comment]
Sorry, the files should be properly uploaded now. Thanks:)

**Comment by alanakbik** [comment]
@AmaliePauli thanks, will make the PR now! Are you planning on releasing the Danish NER dataset? If so, we could also include it into Flair with a dataset downloader class?

**Comment by hvingelby** [comment]
Hi @alanakbik,
I have also been working on the Danish NER dataset and in fact it is already available. We have also made a loading function to load it as a a flair ColumnCorpus, which you can find here.
https://github.com/alexandrainst/danlp/blob/master/danlp/datasets/ddt.py#L54

Note however that in the current dataset each sentence has only been annotated once and we are currently having a second annotator annotating the full dataset. Whenever this is done we will upload the updated dataset.

I think it will make most sense to include it into Flair after the second annotation round wouldn't you agree?

**Comment by alanakbik** [comment]
Hello @hvingelby - yes that makes sense, best include the final version of the data!

**Comment by hvingelby** [comment]
Hi @alanakbik,

The finished dataset is now ready. I have made a PR for a dataset class.

Let me know if anything needs change for the PR.
