### ISSUE TITLE
Error while loading BertEmbeddings with pooling_operation = "mean"

### ISSUE THREAD

**Issue by dhanachandran-ezdi** [zalandoresearch/flair#1188]
word_embeddings = [BertEmbeddings('bert-base-uncased', pooling_operation = 'mean')]

[80         if not everything_embedded or not self.static_embeddings:
---> 81             self._add_embeddings_internal(sentences)
     82 
     83         return sentences
   2141                             embedding.unsqueeze(0) for embedding in embeddings
   2142                         ]
-> 2143                         mean = torch.mean(torch.cat(embeddings, dim=0), dim=0)
   2144                         token.set_embedding(self.name, mean)
   2145 

RuntimeError: expected a non-empty list of Tensors]

**BUT there is no error if pooling_operation = "first"**

**Comment by eurekaqq** [comment]
Hello @dhanachandran-ezdi , which flair version do you use?
In my test, it works fine.
Can you share code snippets and data to reproduce this problem?

**Comment by dhanachandran-ezdi** [comment]
Flair version 0.4.3

`from flair.data import Corpus
from flair.datasets import CSVClassificationCorpus

data_folder = 'data_folder'
column_name_map = {0: "text", 1: "label_topic"}

corpus: Corpus = CSVClassificationCorpus(data_folder,
                                         column_name_map,
                                         skip_header=False,
                                         delimiter='\t',    # tab-separated files
)
  
label_dict = corpus.make_label_dictionary()`

`from flair.data import Corpus
from flair.embeddings import WordEmbeddings, FlairEmbeddings, DocumentRNNEmbeddings
from text_classification_model import TextClassifier
from trainer import ModelTrainer

from flair.embeddings import BertEmbeddings



# 3. make a list of word embeddings
word_embeddings = [
                    BertEmbeddings('bert-base-uncased', pooling_operation = 'mean')#(pooling_operation = 'mean')
                  ]

# 4. initialize document embedding by passing list of word embeddings
# Can choose between many RNN types (GRU by default, to change use rnn_type parameter)
document_embeddings: DocumentRNNEmbeddings = DocumentRNNEmbeddings(word_embeddings,
                                                                     hidden_size=512,
                                                                     reproject_words=True,
                                                                     reproject_words_dimension=256,
                                                                     )

# 5. create the text classifier
classifier = TextClassifier(document_embeddings, label_dictionary=label_dict)

# 6. initialize the text classifier trainer
trainer = ModelTrainer(classifier, corpus)

# 7. start the training
trainer.train('resources/bert_emb',
              learning_rate=0.1,
              mini_batch_size=32,
              anneal_factor=0.5,
              patience=5,
              max_epochs=150)

# 8. plot weight traces (optional)
from flair.visual.training_curves import Plotter
plotter = Plotter()
plotter.plot_weights('resources/bert_emb/weights.txt')`

ERROR:
2019-10-10 05:58:49,048 epoch 1 - iter 0/521 - loss 0.64399666 - samples/sec: 404.00

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-3-82a905e4eadb> in <module>
     33               anneal_factor=0.5,
     34               patience=5,
---> 35               max_epochs=150)
     36 
     37 # 8. plot weight traces (optional)

~/Dhana/semeval_2020/deft_eval_2020/trainer.py in train(self, base_path, learning_rate, mini_batch_size, mini_batch_chunk_size, max_epochs, anneal_factor, patience, min_learning_rate, train_with_dev, monitor_train, monitor_test, embeddings_storage_mode, checkpoint, save_final_model, anneal_with_restarts, batch_growth_annealing, shuffle, param_selection_mode, num_workers, sampler, use_amp, amp_opt_level, **kwargs)
    309 
    310                         # forward pass
--> 311                         loss = self.model.forward_loss(batch_step)
    312 
    313                         # Backward

~/Dhana/semeval_2020/deft_eval_2020/text_classification_model.py in forward_loss(self, data_points)
    132     ) -> torch.tensor:
    133 
--> 134         scores = self.forward(data_points)
    135         return self._calculate_loss(scores, data_points)
    136 

~/Dhana/semeval_2020/deft_eval_2020/text_classification_model.py in forward(self, sentences)
     97     def forward(self, sentences) -> List[List[float]]:
     98 
---> 99         self.document_embeddings.embed(sentences)
    100 
    101         text_embedding_list = [

~/anaconda3/envs/tensorflow_37_vatsal/lib/python3.7/site-packages/flair/embeddings.py in embed(self, sentences)
   2697         sentences = [sentences[i] for i in sort_perm]
   2698 
-> 2699         self.embeddings.embed(sentences)
   2700 
   2701         longest_token_sequence_in_batch: int = len(sentences[0])

~/anaconda3/envs/tensorflow_37_vatsal/lib/python3.7/site-packages/flair/embeddings.py in embed(self, sentences, static_embeddings)
    147 
    148         for embedding in self.embeddings:
--> 149             embedding.embed(sentences)
    150 
    151     @property

~/anaconda3/envs/tensorflow_37_vatsal/lib/python3.7/site-packages/flair/embeddings.py in embed(self, sentences)
     79 
     80         if not everything_embedded or not self.static_embeddings:
---> 81             self._add_embeddings_internal(sentences)
     82 
     83         return sentences

~/anaconda3/envs/tensorflow_37_vatsal/lib/python3.7/site-packages/flair/embeddings.py in _add_embeddings_internal(self, sentences)
   2141                             embedding.unsqueeze(0) for embedding in embeddings
   2142                         ]
-> 2143                         mean = torch.mean(torch.cat(embeddings, dim=0), dim=0)
   2144                         token.set_embedding(self.name, mean)
   2145 

RuntimeError: expected a non-empty list of Tensors

**Comment by eurekaqq** [comment]
Hello @dhanachandran-ezdi , sorry, I can't find where to download the dataset.
I think you can try the code snippet below, maybe it can run well.
```python
from flair.data import space_tokenizer

corpus: Corpus = CSVClassificationCorpus(
    data_folder,
    column_name_map,
    skip_header=False,
    delimiter='\t',  # tab-separated files
    tokenizer=space_tokenizer)
```

**Comment by Dhanachandra** [comment]
Link to the dataset: [deft_eval](https://github.com/Dhanachandra/deft_eval)

There is error in your code snippet. Please it
`>>> import flair
>>> flair.__version__
'0.4.3'
>>> from flair.data import space_tokenizer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'space_tokenizer'`

**Comment by eurekaqq** [comment]
Hi @Dhanachandra , I see the data.
This problem is wrong tokenization result with segtok tokenizer, like "did n't" -> "did", "", "n't".
You can try using the latest version in github and use my code snippet.
If you want to use version 0.4.3, you should add `use_tokenizer` parameter like below.
```python
corpus: Corpus = CSVClassificationCorpus(
    data_folder,
    column_name_map,
    skip_header=False,
    delimiter='\t',
    use_tokenizer=False)
```
