### ISSUE TITLE
path SST-2 forced to lowercase sst-2 while fine tuning BERT for classification

### ISSUE THREAD

**Issue by vr25** [zalandoresearch/flair#1205]
I am getting an error on running this:

python run_classifier.py \
--task_name $GLUE_DIR/SST-2 \
--do_train \
--do_eval \
--do_lower_case \
--data_dir $GLUE_DIR/SST-2/bert_movie_data \
--bert_model $BERT_BASE_DIR/uncased_L-12_H-768_A-12 \
--max_seq_length 128 \
--train_batch_size 32 \
--learning_rate 2e-5 \
--num_train_epochs 3.0 \
--output_dir bert_movie \
--init_checkpoint $BERT_BASE_DIR/bert_model.ckpt.index \
--vocab_file $BERT_BASE_DIR/vocab.txt \
--bert_config_file $BERT_BASE_DIR/bert_config.json

Traceback (most recent call last):
  File "run_classifier.py", line 981, in <module>
    tf.app.run()
  File "/data/ftm/xgb_regr/lib64/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "run_classifier.py", line 813, in main
    raise ValueError("Task not found: %s" % (task_name))
ValueError: Task not found: $glue_dir/sst-2/

**Comment by stefan-it** [comment]
I think this should be better posted in the `transformers` repository [here](https://github.com/huggingface/transformers) :)

But just use the latest version of `transformers` and try to use the commands here in the documentation:

https://huggingface.co/transformers/examples.html#glue
