### ISSUE TITLE
Multitask learning

### ISSUE THREAD

**Issue by antgr** [zalandoresearch/flair#1260]
Is it possible to do multitask learning using flair? I would like to try a very simple example.

**Comment by antgr** [comment]
I suspect that I have to use regular pytorch implementation for this part, right?

**Comment by djstrong** [comment]
I would be interested in multitask learning.

**Comment by alanakbik** [comment]
@djstrong agree, we really need this in Flair.

**Comment by stefan-it** [comment]
I also agree with that :) In the meantime I may point you to the following papers:

* ["AdapterFusion: Non-Destructive Task Composition for Transfer Learning"](https://github.com/Adapter-Hub/AdapterFusion/blob/master/AdapterFusion.pdf)
* ["MAD-X: An Adapter-based Framework for Multi-task Cross-lingual Transfer"](https://github.com/Adapter-Hub/MAD-X/blob/master/MAD-X.pdf)

There will be a huge release on https://adapterhub.ml/ in the next days/weeks and we should really try to integrate that into Flair :)

**Comment by djstrong** [comment]
A simple (I guess) multitask learning is implemented in sentence-transformers.
