### ISSUE TITLE
0.4.4 is breaking flair.datasets

### ISSUE THREAD

**Issue by eliehamouche** [zalandoresearch/flair#1275]
**Describe the bug**

```
import flair.datasets
```
Results in a Module not found error:
ModuleNotFoundError: No module named 'flair.datasets'

Looked in the package itself and don't see datasets anymore:

```
$ ls
data_fetcher.py  embeddings.py  hyperparameter  models  optim.py     trainers           visual
data.py          file_utils.py  __init__.py     nn.py   __pycache__  training_utils.py
```

Tried reinstalling using pip on a fresh conda environment, same issue.

**Environment (please complete the following information):**
 - OS [Manjaro]:
-  Python [3.6.9]
 - Version [flair-0.4.4]

Other packages seem to be working just fine

**Comment by jantrienes** [comment]
Can you verify that you have `flair-0.4.4` installed?

```py
>>> import flair
>>> print(flair.__version__)
0.4.4
```

if this outputs an older version, try a `pip instal -U flair`.

**Comment by eliehamouche** [comment]
Yep on 0.4.4:

```
>>> import flair
>>> print(flair.__version__)
0.4.4
```

Tried installing from source and that works - but I can still recreate the error just by running 
pip install flair in a new environment

Source working however so it must be something in my environment. Closing for now
