### ISSUE TITLE
camemBERT

### ISSUE THREAD

**Issue by robinalexandre** [zalandoresearch/flair#1276]
Hi,

A little question about French model.
Do you plan to include camemBERT (https://camembert-model.fr) model in a futur release soon ?

Thanks

**Comment by stefan-it** [comment]
I tested it locally for a French NER dataset and the results are really great (compared to the multilingual BERT model).

I'm going to add CamemBERT to Flair in the next days :)

**Comment by robinalexandre** [comment]
Great news! Let us know when you it's done :)

**Comment by hzitoun** [comment]
Great news! I'm eager to use the model with flair!

**Comment by robinalexandre** [comment]
> Great news! I'm eager to use the model with flair!

Do you checkout onto the new branch to get it ?
I don't find it in the actual release.

@stefan-it, Can you confirm camemBERT with Flair is ready to be used ?

**Comment by stefan-it** [comment]
@robinalexandre You just need to install a recent version of `transformers`, then you can use the `camembert-embeddings` branch of Flair. 

Implementation is working, I just need to add some unit tests and a depedency update of `transformers` :)

**Comment by hzitoun** [comment]
> @robinalexandre You just need to install a recent version of `transformers`, then you can use the `camembert-embeddings` branch of Flair.
> 
> Implementation is working, I just need to add some unit tests and a depedency update of `transformers` :)

Great work @stefan-it ! Could you please show how to get the embedding vector of a sentence with HF `transformers` lib please?  (the equivalent of flair's `embedding.embed([Sentence("Salut, ça va")])`

**Comment by stefan-it** [comment]
To get embeddings for the last layer with `transformers`:

```python
import torch

from transformers import CamembertTokenizer
from transformers import CamembertModel

tokenizer = CamembertTokenizer.from_pretrained("camembert-base")
model = CamembertModel.from_pretrained('camembert-base')

sent = "J'aime le camembert !"

input_ids = torch.tensor(tokenizer.encode(sent, add_special_tokens=True)).unsqueeze(0)

outputs = model(input_ids)

last_hidden_states = outputs[0]
```

With:

```
In [22]: input_ids                                                                                                                                                                                                                                                                              
Out[22]: tensor([[    5,   121,    11,   660,    16,   730, 25543,   110,    83,     6]])

In [23]: last_hidden_states.shape                                                                                                                                                                                                                                                               
Out[23]: torch.Size([1, 10, 768])
```

**Comment by hzitoun** [comment]
> To get embeddings for the last layer with `transformers`:
> 
> ```python
> import torch
> 
> from transformers import CamembertTokenizer
> from transformers import CamembertModel
> 
> tokenizer = CamembertTokenizer.from_pretrained("camembert-base")
> model = CamembertModel.from_pretrained('camembert-base')
> 
> sent = "J'aime le camembert !"
> 
> input_ids = torch.tensor(tokenizer.encode(sent, add_special_tokens=True)).unsqueeze(0)
> 
> outputs = model(input_ids)
> 
> last_hidden_states = outputs[0]
> ```
> 
> With:
> 
> ```
> In [22]: input_ids                                                                                                                                                                                                                                                                              
> Out[22]: tensor([[    5,   121,    11,   660,    16,   730, 25543,   110,    83,     6]])
> 
> In [23]: last_hidden_states.shape                                                                                                                                                                                                                                                               
> Out[23]: torch.Size([1, 10, 768])
> ```

Great thank you very much!

**Comment by stefan-it** [comment]
To get a fixed embedding sentence vector, you could e.g. perform pooling operations, like mean or max pooling over all ouput vectors (from each subtoken).

I think a good reference is the [Reimers and Gurevych paper](https://arxiv.org/abs/1908.10084), incl. their repository on [GitHub](https://github.com/UKPLab/sentence-transformers) for Transformer-based sentence embeddings :)
