### ISSUE TITLE
trainers not in __init__.py

### ISSUE THREAD

**Issue by kylebgorman** [zalandoresearch/flair#128]
The following doesn't work:

    import flair
    flair.trainers.SequenceTaggerTrainer

because there's no `from . import trainers` in `flair/__init__.py`. This seems to violate the principle of least astonishment since this works fine for `data` and `models`.

Glad to submit a PR if you're okay with this.

**Comment by tabergma** [comment]
Thanks for detecting this. We are more than happy, if you could submit a PR fixing this issue. Thank you!

**Comment by tabergma** [comment]
We already included it in the branch `release-0-3`. So it will be part of the next release, which should happen next week.

**Comment by kylebgorman** [comment]
Ok, great, so no PR needed, I take it.

**Comment by tabergma** [comment]
Yes. Thanks for spotting this!

I'll close this issue as we already merged the change into `release-0.3`.
