### ISSUE TITLE
Are you planning to add DistilRoberta to available models?

### ISSUE THREAD

**Issue by krzysztoffiok** [zalandoresearch/flair#1285]
Hi,
are you planning to add DistilRoberta model to list of available models?

https://github.com/huggingface/transformers/tree/master/examples/distillation

Best,

**Comment by stefan-it** [comment]
Hi @krzynio,

yes, I'm planning to sync the current `transformers` version with Flair, so new models can be used 🤗

CamemBERT is one of the new awesome models. And some new distilled models (e.g. multilingual) will be integrated into `transformers` very soon,

**Comment by krzysztoffiok** [comment]
That's great news, thanks!
