### ISSUE TITLE
Training on PTB 3 POS task

### ISSUE THREAD

**Issue by kylebgorman** [zalandoresearch/flair#135]
I am attempting to train a model on the PTB 3 POS task using the tutorial model specification. The only custom code I am using is to create the lists of tagged sentences from a `token/tag` format. I have 62 GB of RAM and 48 cores in all. RAM usage of the trainer grows rapidly: during the 4th iteration my machine becomes unresponsive and eventually, the kernel kills the job. Is this expected? Do you train with even more RAM than that? (Or would you expect radically less RAM utilization on GPU?)

**Comment by kylebgorman** [comment]
Thanks for looking into this.

I was using yesterday's HEAD, master branch, from Github. Should I grab the
"release-0.3" branch instead?

Yes, memory usage increased per epoch. 20% running the first iteration,
roughly 30% the second one...swapping wildly by the fourth iteration.

**Comment by alanakbik** [comment]
Ah that is very strange. Could you retry with the master 0.3 branch? If the error happens here too we have to take a closer look!

**Comment by kylebgorman** [comment]
Just did (`git checkout release-0.3`) then ran my script. The printout is now a bit nicer but the same problem: it gets to iter 238/1195 (loss is steadily going down) but by then it's used 80+% of the available memory and then the OS kills it.

**Comment by alanakbik** [comment]
Yes, that's a good point. We are actually currently looking into ways for embeddings that don't fit into memory to be persisted on disk with an index for quick lookup. This would address the memory issue for all use cases and also not require the embeddings to be generated over and over again at each epoch (thus speeding up the process). Also, if you rerun an experiment over a dataset, you can use already computed embeddings, making repeat experiments faster. 

I'll upload a branch soon that we might merge into release-0.3. So if all works well, we can probably get it into the next official release!

**Comment by kylebgorman** [comment]
> On Oct 10, 2018, at 10:14 AM, Alan Akbik <notifications@github.com> wrote:
> 
> Yes, that's a good point. We are actually currently looking into ways for embeddings that don't fit into memory to be persisted on disk with an index for quick lookup. This would address the memory issue for all use cases and also not require the embeddings to be generated over and over again at each epoch (thus speeding up the process). Also, if you rerun an experiment over a dataset, you can use already computed embeddings, making repeat experiments faster.
> 
> I'll upload a branch soon that we might merge into release-0.3. So if all works well, we can probably get it into the next official release!

That would be great, thanks. This is more than sufficient in the meantime, so you’re welcome to close this if you are tracking that elsewhere.

**Comment by alanakbik** [comment]
Ok! Created issue #137 for this.
