### ISSUE TITLE
Prepare release-0.3

### ISSUE THREAD

**Issue by tabergma** [zalandoresearch/flair#139]
- update documentation
- push to pip
- add new language models

**Comment by stefan-it** [comment]
Is there any concrete release date for `0.3`? E.g. last week I trained a model for pos tagging and I noticed some evaluation problems (f-score and accuracy had been switched). The visualization script worked ok, unless I needed to add a `round(...,2)` for f-score and accuracy values.

**Comment by alanakbik** [comment]
We wanted to do it probably tomorrow, but since there is no particular rush we could hold off a few more days for those issues - sounds important :)

**Comment by stefan-it** [comment]
Thanks for your patience :)

I found one strange behaviour after using the `GH-139-release-0.3`  branch compared to the `release-0.3` branch:

```bash
2018-10-13 08:46:23,048 DEV : f-score 1.0000 - acc 1.0000 - tp 6271.0 - fp 962.0 - fn 962.0 - tn 0.0
2018-10-13 08:46:23,048 TEST: f-score 1.0000 - acc 1.0000 - tp 6368.0 - fp 1055.0 - fn 1055.0 - tn 0.0
```

For pos-tagging. Using `release-0.3` the f-score and accuracy metrics were correct. But `tn` was always *0.0*.

I'm preparing a test example for pos tagging on universal dependencies, so you can reproduce the problem :)

**Comment by stefan-it** [comment]
Thanks for the fix! The values look more reasonable now :+1: 

But I quite do not understand the metrics. `tn` is again always *0.0*. Let's look at the following output after one training epoch:

```bash
2018-10-13 14:01:51,895 EPOCH 1: lr 0.1000 - bad epochs 0
2018-10-13 14:01:51,895 DEV : f-score 0.9272 - acc 0.8643 - tp 11565.0 - fp 918.0 - fn 897.0 - tn 0.0
2018-10-13 14:01:51,895 TEST: f-score 0.9308 - acc 0.8705 - tp 15344.0 - fp 1152.0 - fn 1131.0 - tn 0.0
```

After that epoch I quit training and run an evaluation script for calculating accuracy (comparing each predicted tag with the gold tag):

```bash
Accuracy: 0.9147984736465538
```
I looked at the `evaluate` method [here](https://github.com/zalandoresearch/flair/blob/GH-139-release-0.3/flair/trainers/sequence_tagger_trainer.py#L173) and `metric.tn()` is never set.

**Comment by stefan-it** [comment]
I have following temp. solution:

```bash
                if evaluation_method == 'F1':
                    # check for true positives, false positives and false negatives
                    for prediction in predicted_tags:
                        if prediction in gold_tags:
                            metric.tp()
                        else:
                            metric.fp()

                    for gold in gold_tags:
                        if gold not in predicted_tags:
                            metric.fn()
                else:
                    for prediction, gold in zip(predicted_tags, gold_tags):
                        if prediction == gold:
                            metric.tp()
                        else:
                            metric.tn()
```

But now I could see a higher accuracy than my evaluation script. 

The `evaluate` method has the `out_path` argument. When this argument is set a test.tsv is created. I counted the number of evaluated tags and compared them to my script:

| method  | evaluated tags
| ---------- | -------------------
| `flair`s `evaluate` method | 16.498
| my evaluation script | 16.772

So there's a difference of 274 tags :(

**Comment by alanakbik** [comment]
Thanks for your help! So do these "contractions" account for the difference in tags between the two evaluation scripts?

Wrt false negatives: since in PoS tagging there is always a prediction for each word there should normally be no false negatives. So I think this is correct. However in NER there can be false negatives (i.e. when a word is incorrectly not labeled as an entity), so I'll look into this!

**Comment by stefan-it** [comment]
Another finding related to the accuracy calculation. My evaluation script outputs the same accuracy as for the accuracy calculated on `test.tsv`. But this value is not the same as from the `flair.training_utils.Metric` object used in the accuracy calculation method.

I found the following:

In some cases the correct gold tag is not fetched from the sentence in the final accuracy calculation. But the correct gold tag is written to the `test.tsv` file. 

For the `test.tsv` the gold tags are fetched like this:

```python
for token in sentence.tokens:
    gold_tag = token.get_tag(self.model.tag_type).value
```

For the final accuracy calculation the following method is used:

```python
gold_tags = [str(tag) for tag in sentence.get_spans(self.model.tag_type)]
```

So `get_spans` is used. Then I checked the cases, where the predicted and gold tag are not equal, but the predicted tag and the gold tag used in `test.tsv`:

```bash
Prediction: NOUN-span [56]: "Rückziehers"
Gold: PUNCT-span [57]: "."
Prediction_test.tsv: NOUN
Gold_test.tsv: NOUN
```

This happened 166 times and caused an accuracy decrease of ~ 1%.

**Comment by alanakbik** [comment]
Interesting. Could you paste this full sentence the way it appears in `test.tsv` here? Maybe it's a problem of how the spans get extracted.

**Comment by alanakbik** [comment]
Ahh yes, I see the error. The span method currently treats all tags that are only one character long as 'out'-tag. In these sentences, there is the 'X' tag which gets wrongly interpreted. That's a big mistake - I'll correct this and hopefully that should fix the issue. 

Thanks very much for your help!

**Comment by stefan-it** [comment]
@alanakbik  I checked the length of the prediction and gold tags, and can confirm this! E.g.

```bash
18	a	a	ADP	FM	Foreign=Yes	20	compound	_	_
19	la	la	X	FM	Foreign=Yes	20	compound	_	_
20	malaguena	malaguena	NOUN	FM	Foreign=Yes	10	conj	_	_
```

is then converted to:

```bash
'ADP-span [18]: "a"', 'NOUN-span [20]: "malaguena"'
```
So the "a" is dropped, because of the `X` tag.

**Comment by stefan-it** [comment]
@alanakbik I think the following commit:

https://github.com/zalandoresearch/flair/commit/8d362877197d01a66d35a823d30146bf47fdf146#diff-2f126a2147fa6983e2d958afc805100e

breaks with the text classification trainer. I got the following error message when reading in a text classification file:

```bash
Traceback (most recent call last):
  File "train_1.py", line 9, in <module>
    sentences_train: List[Sentence] = NLPTaskDataFetcher.read_text_classification_file('training.preprocessed.txt')
  File "/mnt/flair/flair/data_fetcher.py", line 352, in read_text_classification_file
    sentence = Sentence(text, labels=labels, use_tokenizer=True)
  File "/mnt/flair/flair/data.py", line 303, in __init__
    token = Token(word, start_position=index(word, running_offset))
ValueError: substring not found
```

Line is: 

```bash
__label__OTHER Liebe Corinna, wir würden dich gerne als Moderatorin für uns gewinnen! Wärst du begeisterbar?
```

**Comment by tabergma** [comment]
@stefan-it I cannot reproduce this error. When I add your example sentence to a file and try to read it via `read_text_classification_file`, everything works fine. Can you maybe share more details around the setup or even the complete file? Thanks.

**Comment by tabergma** [comment]
I added a try catch around finding the word index, should make it more robust.

**Comment by stefan-it** [comment]
Thanks for that fix, it is working now :)
