### ISSUE TITLE
Question on LM training details

### ISSUE THREAD

**Issue by jvamvas** [zalandoresearch/flair#140]
Please allow a few questions on the language models that you provide. I am referring to the following models:
`lm-news-english-forward-v0.2rc.pt / lm-news-english-backward-v0.2rc.pt`

* What GPU did you use?
* How many times did the trainer pass through the training set?
* When you say you trained for a week, does this include both directions or just a single direction?

**Comment by alanakbik** [comment]
Hi @jvamvas we trained each model separately and each a week - although now we typically train our models for about 2 weeks (and on current experiments over much larger datasets even 3 weeks). The models you references have made about 10 full epochs over the 1BW corpus, using a V100 GPU.

Hope this helps!

**Comment by jvamvas** [comment]
@alanakbik Thanks for the infos, Alan!
