### ISSUE TITLE
Python Error : Word Embeddings

### ISSUE THREAD

**Issue by Killthebug** [zalandoresearch/flair#143]
Executing : 
`>>> from flair.embeddings import CharLMEmbeddings
`
Raises Error :

> Traceback (most recent call last):  
>   File "<stdin>", line 1, in <module>  
>   File "/home/jaipal.singh/.local/lib/python3.5/site-packages/flair/embeddings.py", line 37   
>     everything_embedded: bool = True
>                        ^
> SyntaxError: invalid syntax

Any ideas on how to resolve this?

**Comment by alanakbik** [comment]
Hi @Killthebug it looks like you're using Python 3.5. You need to use Python 3.6+ for Flair. See [requirements and installation](https://github.com/zalandoresearch/flair/tree/GH-139-release-0.3#requirements-and-installation).

If you're on Ubuntu 16.04, this page gives a quick intro on how to install Python 3.6: https://vsupalov.com/developing-with-python3-6-on-ubuntu-16-04/

**Comment by Killthebug** [comment]
Hi @alanakbik Thanks for pointing that out!
I'm working on a University server which doesn't allow me to upgrade my python version (beyond 3.5).
I wish to use the flair pre-trained embeddings and have thought of two solutions for the same.
1.  Run the flair code on my local system and save the model out. Then move the model to the server and use it.
2. Download the pre-trained word-embeddings (I've not yet figured a way to do this.)

Is there a way to download the pre-trained word-embeddings?

**Comment by stefan-it** [comment]
@Killthebug I made good experiences with `pyenv`, e.g. you can try the following:

```bash
git clone https://github.com/pyenv/pyenv.git ~/.pyenv
echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bash_profile
echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bash_profile
```

See more instructions [here](https://github.com/pyenv/pyenv#basic-github-checkout).

Then you could:

```bash
pyenv install 3.6.6
pyenv global 3.6.6
```

Then `python` points to a 3.6 version of Python. This can all be done on a system requiring non-root permissions :)

**Comment by Killthebug** [comment]
@stefan-it Your solution with pyenv did the job. Thanks a ton!

**Comment by steambread666** [comment]
@alanakbik  Hi,I try to reproduce experiments on Penn Treebank Part-of-Speech Tagging,but I got the error when I run the code:
Executing :
>>> from self.precomputed_word_embeddings = gensim.models.KeyedVectors.load(embeddings)
Raises Error :
Traceback (most recent call last):
  File "/home/cciip/mycode/flair-master/train.py", line 23, in <module>
    WordEmbeddings('extvec'),
  File "/home/cciip/mycode/flair-master/flair/embeddings.py", line 191, in __init__
    self.precomputed_word_embeddings = gensim.models.KeyedVectors.load(embeddings)
  File "/home/cciip/anaconda3/lib/python3.6/site-packages/gensim/models/keyedvectors.py", line 211, in load
    return super(BaseKeyedVectors, cls).load(fname_or_handle, **kwargs)
  File "/home/cciip/anaconda3/lib/python3.6/site-packages/gensim/utils.py", line 419, in load
    obj = unpickle(fname)
  File "/home/cciip/anaconda3/lib/python3.6/site-packages/gensim/utils.py", line 1358, in unpickle
    return _pickle.load(f, encoding='latin1')
_pickle.UnpicklingError: STACK_GLOBAL requires str

Any ideas on how to resolve this?

**Comment by alanakbik** [comment]
@steambread666 hm very strange - what operating system are you on and what version of Flair are you using?

**Comment by steambread666** [comment]
@alanakbik Hi,My operating sysytem is Ubuntu 16.04.And I run the code in the "flair-master" project instead of installing Flair.

**Comment by alanakbik** [comment]
@steambread666 Is this still an issue with the current version?

**Comment by steambread666** [comment]
@alanakbik  It works well now! Thank you very much!
