### ISSUE TITLE
Using custom word embeddings

### ISSUE THREAD

**Issue by mhham** [zalandoresearch/flair#170]
Hi there,

I am experimenting with training a SequenceTagger for NER in french, and I would like to use custom word embeddings for the language.

Is there a simple way to do this, that doesn't involve changing the code of `WordEmbeddings` ?

Cheers, and thank you for the great work !

**Comment by tabergma** [comment]
Hi @mhham!

Thanks!

What do you mean by custom word embeddings? Are you looking for something like this: https://github.com/zalandoresearch/flair/issues/81?

**Comment by mhham** [comment]
Exactly, I was wondering if there was a way to do it just by passing the embedding path (correctly formatted to gensim) to the WordEmbeddings constructor

**Comment by tabergma** [comment]
No, not yet. But as you are the second person asking about this, we will add it.

**Comment by mhham** [comment]
I tried modifying the WordEmbeddings class (as suggested in #81) to input my custom embedding. 
The embedding seems to work fine, but when training a sequence tagger I get a torch serialization error, right after the first epoch.

Code:

```
from flair.data_fetcher import NLPTask
from flair.embeddings import CharacterEmbeddings, CharLMEmbeddings, TokenEmbeddings, WordEmbeddings, StackedEmbeddings
from typing import List

# 1. get the corpus
corpus = downsampled_corpus 

# 2. what tag do we want to predict?
tag_type = 'ner'

# 3. make the tag dictionary from the corpus
tag_dictionary = corpus.make_tag_dictionary(tag_type=tag_type)
print(tag_dictionary.idx2item)


# 4. initialize embeddings
embedding_types: List[TokenEmbeddings] = [

    WordEmbeddings('fr-fasttext') #Defined in the WordEmbeddings class

    # comment in this line to use character embeddings
    # CharacterEmbeddings(),

    # comment in these lines to use contextual string embeddings
    #CharLMEmbeddings('news-forward'),
    #CharLMEmbeddings('news-backward'),
]

embeddings: StackedEmbeddings = StackedEmbeddings(embeddings=embedding_types)

# 5. initialize sequence tagger
from flair.models import SequenceTagger

tagger: SequenceTagger = SequenceTagger(hidden_size=256,
                                        embeddings=embeddings,
                                        tag_dictionary=tag_dictionary,
                                        tag_type=tag_type,
                                        use_crf=True)

# 6. initialize trainer
from flair.trainers import SequenceTaggerTrainer

trainer: SequenceTaggerTrainer = SequenceTaggerTrainer(tagger, corpus)

# 7. start training
trainer.train('resources/taggers/example-ner',
              learning_rate=0.1,
              mini_batch_size=32,
              max_epochs=10)
```

Gives the following error :

```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-6-de6d08c3eb5d> in <module>()
     47               learning_rate=0.1,
     48               mini_batch_size=32,
---> 49               max_epochs=10)

.../lib/python3.7/site-packages/flair/trainers/sequence_tagger_trainer.py in train(self, base_path, learning_rate, mini_batch_size, max_epochs, anneal_factor, patience, train_with_dev, embeddings_in_memory, checkpoint, save_final_model, anneal_with_restarts)
    161                 # if we use dev data, remember best model based on dev evaluation score
    162                 if not train_with_dev and dev_score == scheduler.best:
--> 163                     self.model.save(base_path + "/best-model.pt")
    164 
    165             # if we do not use dev data for model selection, save final model

.../lib/python3.7/site-packages/flair/models/sequence_tagger_model.py in save(self, model_file)
    149             'rnn_layers': self.rnn_layers,
    150         }
--> 151         torch.save(model_state, model_file, pickle_protocol=4)
    152 
    153     @classmethod

.../lib/python3.7/site-packages/torch/serialization.py in save(obj, f, pickle_module, pickle_protocol)
    207         >>> torch.save(x, buffer)
    208     """
--> 209     return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
    210 
    211 

.../lib/python3.7/site-packages/torch/serialization.py in _with_file_like(f, mode, body)
    132         f = open(f, mode)
    133     try:
--> 134         return body(f)
    135     finally:
    136         if new_fd:

.../lib/python3.7/site-packages/torch/serialization.py in <lambda>(f)
    207         >>> torch.save(x, buffer)
    208     """
--> 209     return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
    210 
    211 

.../lib/python3.7/site-packages/torch/serialization.py in _save(obj, f, pickle_module, pickle_protocol)
    280     pickler = pickle_module.Pickler(f, protocol=pickle_protocol)
    281     pickler.persistent_id = persistent_id
--> 282     pickler.dump(obj)
    283 
    284     serialized_storage_keys = sorted(serialized_storages.keys())

OSError: [Errno 22] Invalid argument
```

**Comment by alanakbik** [comment]
Thanks for reporting the issue!

Wrt to the word embeddings: You could also convert your embeddings into gemsim keyedvectors format and then just pass the path to the keyedvectors to the `WordEmbeddings` class. If you use fasttext embeddings, you can use the code from #81 : 

```python
import os
from gensim.models.fasttext import FastText

# load fasttext embeddings by pointing this method to the ft embeddings txt file
model = FastText.load_fasttext_format('/path/to/fasttext/embeddings')
word_vectors = model.wv

# save as KeyedVectors
from gensim.models import KeyedVectors
word_vectors.save('/path/to/converted')
```

You can then init `WordEmbeddings` by passing this path, i.e. 
```python
embeddings = WordEmbeddings('/path/to/converted')
```

Does this work for you?

**Comment by stefan-it** [comment]
Btw: in my experiments using the subword information from `fasttext` embeddings `(gensim.models.FastText.load_fasttext_format()` significantly decreases accuracy (up to 9 %)?! I'm not sure why, so also recommend to load `fasttext` embeddings with `load_word2vec_format` without subword information.

**Comment by alanakbik** [comment]
Hi @stefan-it yes we and other groups have made this observation as well, for sequence labeling but also other NLP tasks. Somehow the subword information introduces false generalizations that are more detrimental to downstream tasks than having some unknown words in there. I believe several papers have mentioned this as well.

**Comment by abeermohamed1** [comment]
> Thanks for reporting the issue!
> 
> Wrt to the word embeddings: You could also convert your embeddings into gemsim keyedvectors format and then just pass the path to the keyedvectors to the `WordEmbeddings` class. If you use fasttext embeddings, you can use the code from #81 :
> 
> ```python
> import os
> from gensim.models.fasttext import FastText
> 
> # load fasttext embeddings by pointing this method to the ft embeddings txt file
> model = FastText.load_fasttext_format('/path/to/fasttext/embeddings')
> word_vectors = model.wv
> 
> # save as KeyedVectors
> from gensim.models import KeyedVectors
> word_vectors.save('/path/to/converted')
> ```
> 
> You can then init `WordEmbeddings` by passing this path, i.e.
> 
> ```python
> embeddings = WordEmbeddings('/path/to/converted')
> ```
> 
> Does this work for you?

Hi @alanakbik I am using custom embeddings. which syntax is a valid one from the below:

as when i try the below link syntax, an error is thrown:
https://github.com/flairNLP/flair/commit/4a4a38e0c3b1ba71d26d379bf10918aa0dce28f3

Syn 1:
WordEmbeddings( data_folder+'/modelsg300wiki.gensim'),
# the above working fine but accuracy decreased.

Syn 2:
WordEmbeddings( 'custom' , data_folder+'/modelsg300wiki.gensim'),

thank you
