### ISSUE TITLE
Wrong storage size error while loading ner-ontonotes-fast

### ISSUE THREAD

**Issue by rohitmujumdar** [zalandoresearch/flair#172]
Stack trace : 
>>> tagger = SequenceTagger.load('ner-ontonotes-fast')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\flair-0.3.1-py3.7.egg\flair\m
odels\sequence_tagger_model.py", line 566, in load
  File "C:\ProgramData\Anaconda3\lib\site-packages\flair-0.3.1-py3.7.egg\flair\m
odels\sequence_tagger_model.py", line 157, in load_from_file
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line
 358, in load
    return _load(f, map_location, pickle_module)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line
 549, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: storage has wrong size: expected -1497503119 got 2348

Configuration Details :   

Python = 3.7
Torch = 0.4.1
CPU = 8GB RAM, no GPU 

has anyone else got this issue?

**Comment by rohitmujumdar** [comment]
Hi Alan,

I am on Windows 8.1
Yes I could load the normal 'ner' and 'ner-fast' models successfully.

**Comment by alanakbik** [comment]
It could be that there was an error when downloading the ner-ontonotes model. See https://discuss.pytorch.org/t/load-pretrained-model-error/11431 

Can you delete the model locally (stored locally in ~/flair/models/) and run the code again? This will trigger a new download. Also make sure that there is enough disk space.

**Comment by rohitmujumdar** [comment]
I tried deleting the model and re-downloading the model. I get the same error, in fact with the same storage size numbers.

**Comment by devmaha** [comment]
Having the same problem with ner-ontonotes 12 entity models on Windows. It might be actually a serialization related issue. Appreciate if someone could take a look and assist.

**Comment by alanakbik** [comment]
@devmaha @rohitmujumdar thanks for reporting this! This probably is related to #171 so we will make sorting this out an immediate priority. Any help from Windows users debugging this is greatly appreciated!

**Comment by alanakbik** [comment]
Opened #174 for this bug.
