### ISSUE TITLE
DocumentMinEmbeddings, DocumentMaxEmbeddings

### ISSUE THREAD

**Issue by Nilabhra** [zalandoresearch/flair#185]
Hello! 

I would also like to have max and min pooling over word embeddings to represent a document. I believe it can be easily implemented either by passing a parameter `mode` taking values from `['mean', 'min', 'max']` to a generic class like `DocumentPoolEmbeddings` or have separate classes for each.
I would happy to make a pull request if you guys think it's something you would want flair to have.

I would like to thank the Zalando team for making flair open source and I am delighted to see that it's built on PyTorch.

Thanks!

**Comment by alanakbik** [comment]
Hello @Nilabhra - that would be great, we'd appreciate a PR for this! A `DocumentPoolEmbeddings` class sounds like a good idea.

I think the `DocumentLSTMEmbeddings` class could help for orientation on how to extract sentence embeddings from word embeddings. Let us know if you have any questions!

**Comment by Nilabhra** [comment]
@alanakbik I already had a look at the code, I'll try to send a PR ASAP

**Comment by Nilabhra** [comment]
Hey @alanakbik 
`pipenv install --dev && pipenv shell` is failing because of a read timeout error. Any clue what's wrong here? Also, can I just run `pytest -q tests/test_embeddings.py` for the test?

**Comment by alanakbik** [comment]
@Nilabhra thanks a lot for your help!

**Comment by Nilabhra** [comment]
Sure thing! Thanks again for making flair open source.
