### ISSUE TITLE
Bulgarian language support

### ISSUE THREAD

**Issue by stefan-it** [zalandoresearch/flair#188]
Hi,

I trained a Bulgarian language model with texts from Wikipedia, Europarl and SETimes. It is a relatively small corpus with 66 million tokens and was trained for ~ 3 days.

Then I trained a model for pos tagging on universal dependencies (version 1.2). The accuracy was ~ 98 % with `fasttext` embeddings only. In combination with the forward and backward language model the final accuracy is 99.08 % on the test set. Here are some comparisons with other papers (UD 1.2, Bulgarian):

| System                                                     | Final Accuracy
| ---------------------------------------------------------- | -------------
| [Yu et. al (2017)](https://arxiv.org/abs/1706.01723)        | 98.20
| [Plank et. al (2016)](https://arxiv.org/abs/1604.05529)    | 98.23
| [Yasunaga et. al (2017)](https://arxiv.org/abs/1711.04903) | 98.53
| `flair`                                               | **99.08**

I will post the exact training parameters in my [experiments](https://github.com/stefan-it/flair-experiments) repo in the next days. If you want  you can integrate the "fast" language models in `flair` directly (+ pos tagging model)  :)

**Comment by alanakbik** [comment]
Wow, great results! We'll check out the repo and would be very interested in integrating the Bulgarian LM and PoS tagger!

**Comment by stefan-it** [comment]
The Bulgarian is now available for download - you can find it in [this repository](https://github.com/stefan-it/flair-lms). I'm going to post the exact parameters and a trained model on universal dependencies v1.2 for pos tagging in the next days :)
