### ISSUE TITLE
Slovenian language support

### ISSUE THREAD

**Issue by stefan-it** [zalandoresearch/flair#202]
Hi,

I tried a language model for Slovenian on Europarl, Wikipedia and OpenSubtitles2018. The training corpus has a size of 1.8G with 314,973,528 token. Training was done for ~ 3 days reaching a ppl of 3.28 (forward) and 3.34 (backward).

Then I trained a model for pos tagging on universal dependencies (v1.2). With Wikipedia word embeddings only, an accuracy of ~ 97% could be achieved. Using the language models an accuracy of 98.88% could be achieved. Here's a comparison with other models:

| System                                                     | Final Accuracy
| ---------------------------------------------------------- | -------------
| [Yu et. al (2017)](https://arxiv.org/abs/1706.01723)        | 97.16
| [Plank et. al (2016)](https://arxiv.org/abs/1604.05529)    | 96.97
| [Yasunaga et. al (2017)](https://arxiv.org/abs/1711.04903) | 98.11
| `flair`                                               | **98.88**

Forward and backward language models can be found in [this repository](https://github.com/stefan-it/flair-lms) - training params and a trained model for Slovenian will follow :)

**Comment by alanakbik** [comment]
Hey this is great! 

Can we include your trained LMs in the upcoming release? If so, would you prefer to host them yourself (then we would only link to them) or should we upload them to our AWS storage?

**Comment by stefan-it** [comment]
Hi Alan, of course you can use them in the upcoming release :) I think it would be better and more  convenient when you upload the lms to your AWS storage!

**Comment by alanakbik** [comment]
Great, thanks! We really appreciate this!
