### ISSUE TITLE
Tagging multiple tokens with one custom tag in NER task

### ISSUE THREAD

**Issue by henry32144** [zalandoresearch/flair#207]
Hello,  thank you for providing such a great open source project.

 I have a question that can I tagging multiple tokens in one custom tag?

For example, In the following sentence :

**'Sequential involvement of NFAT and Egr transcription factors in FasL regulation.'**, 

**Egr transcription factors** is a word, I want to tag it with "**Gene**".

I have tried **add_tag('ner', 'Gene')**, but it seems like it can only tag one token at once.

Can I get a tagged sentence like this?

 **Egr  transcription factors** \<Gene> .' - 1 Tokens

Sorry for my bad English,

Thanks!

**Comment by qiuwei** [comment]
You can. 

You need to use some encoding scheme, like bio or bieos to achieve this.
For your example,
```
Sequential involvement of NFAT and Egr transcription factors in FasL regulation
```
would be tagged as
```
Sequential/O involvement/O of/O NFAT/O and/O Egr/B-GENE transcription/I-GENE factors/I-GENE in/O FasL/O regulation/O
```
using BIO scheme.

Then you need to recover the entities according to the BIO tags.

**Comment by henry32144** [comment]
Oh, I got it!

Thank you for your help 👍
