### ISSUE TITLE
Not Using GPU

### ISSUE THREAD

**Issue by zhaoxy92** [zalandoresearch/flair#208]
Hi, Thank you for this amazing work! I am trying train a model with GPU. However, I found that there is no place to set GPU/CPU parameter. Now my GPU is not being used. Could you please tell me how to send the model to cuda?

**Comment by qiuwei** [comment]
I think flair automatically detects your gpu.
It might be a bug if it doesn't.

**Comment by zhaoxy92** [comment]
Yeah it's actually my bad. I had a low GPU usage instead of none usage which I think due to data size. I should've clarify this. Thanks!

**Comment by Glorf** [comment]
Hi @zhaoxy92 , I seem to be facing the same problem - my GPU is rarely even used, while CPU is stressed all the time. CUDA is configured and working. Could you describe how you've resolved this?

**Comment by zhaoxy92** [comment]
I wasn't able to resolve it. But I think it low use might be normal, it's
probability because you have a lot of data structures/data (list, data,
etc.) are not computed on GPU.
