### ISSUE TITLE
Fast version of German NER models

### ISSUE THREAD

**Issue by sscdotopen** [zalandoresearch/flair#211]
Hi,

Is there a chance that you could provide a fast version of the German NER model, similar to `ner-fast` for english?

**Comment by alanakbik** [comment]
Good idea - we'll add some faster models for German as well.

**Comment by alanakbik** [comment]
Hi @sscdotopen - we just released flair 0.4.0 - it includes new '_one model, many languages_' NER taggers. I.e. this is a single model that can consume text in English, German, Dutch and Spanish and predict NER tags. (Also kind of works for other languages such as French.)

Use like this: 

```python
# load model
tagger = SequenceTagger.load('ner-multi')

# text with English and German sentences
sentence = Sentence('George Washington went to Washington . Dort traf er Thomas Jefferson .')

# predict NER tags
tagger.predict(sentence)

# print sentence with predicted tags
for entity in sentence.get_spans('ner'):
    print(entity)
```

We also include a 'fast' version for CPU inference, and a 'fast-learning' version with new, experimental continuous learning (a bit better than 'fast' and theoretically should keep improving as you use it more). 

```python
# fast multilingual NER model
tagger = SequenceTagger.load('ner-multi-fast')

# fast multilingual NER model with continuous learning
tagger = SequenceTagger.load('ner-multi-fast-learn')
```

We'd be happy to hear how they work for you!

**Comment by timnon** [comment]
Thanks for this awesome package! I noticed that `ner-multi` has problems with the following constellation: "Hans Meier ist ein fleissiger Mensch. Er arbeitet bei der Firma ABCDE.".  "ABCDE" is not recognized as an organisation or anything else. Other letter combinations are recognized, sometimes as locations. The organisation recognition works if i use "Hans Meier arbeitet bei der Firma ABCDE".

**Comment by alanakbik** [comment]
Hi @timnon thanks for sharing this example - we'll take a look!

**Comment by Benvorth** [comment]
Hey, is there a more recent version of `ner-multi-fast`? I was not able to make it run with recent libs like `torch==2.2.1` and `flair==0.14.0`...
