### ISSUE TITLE
Resume training (keeping epoch, losses, and best model score)

### ISSUE THREAD

**Issue by mhham** [zalandoresearch/flair#217]
It would be nice to be able to keep the epoch numbers and losses when resuming training on a model loaded from disk.

(https://pytorch.org/tutorials/beginner/saving_loading_models.html#saving-loading-a-general-checkpoint-for-inference-and-or-resuming-training)

#200 already mentioned keeping the scores in the pickled .pt object, but keeping the logs is also a nice add in (not overwriting them).

**Comment by alanakbik** [comment]
Yes good point, we will add a better mechanism for this!
