### ISSUE TITLE
How to credit you properly?

### ISSUE THREAD

**Issue by hankcs** [zalandoresearch/flair#222]
Hi flair team,

Thanks for your paper and codes, I learnt a lot from them as a junior researcher. In our project, I "ported" your codes from PyTorch to another DL framework called MXNet. Now we are drafting the documentation, then I have a question about how to correctly give you credits. Of course we'll cite your paper, but how to cite your code? Could you tell me which one of those words is proper for [our codes](https://github.com/elitcloud/elit/tree/hankcs/elit/nlp/tagger)?

1. Adopted from flair with some modifications.
1. Replicated from flair with some modifications.
1. Ported from flair with some modifications.

**Comment by alanakbik** [comment]
Hi @hankcs - wow that's great! Are you getting good results with this approach in MXNet? 

I think all three options are good, maybe "ported" is the most clear, if possible also with a version number (it looks like you ported from Flair release 0.2). Could you also include a link to our project? Thanks!

**Comment by hankcs** [comment]
Thanks for your quick reply. Although we couldn't replicate the score on paper, but our codes produced similar numbers with flair 0.2 on our data, which are `WSJ NER F1=92.74, POS Acc=97.72`. 

Yes, we'll cite it as "ported from PyTorch implementation of flair: https://github.com/zalandoresearch/flair to MXNet". Great!
