### ISSUE TITLE
Non-whitespaced tokenized text results into an infinite loop

### ISSUE THREAD

**Issue by jfilter** [zalandoresearch/flair#226]
I though my text was whitespace-tokenized, but it actually wasn't. I run into an infinite loop here:

https://github.com/zalandoresearch/flair/blob/86485ec920e30b787c43b6b3ff094fbc4fa0c253/flair/data.py#L539-L541

A safeguard would have been helpful and I am about to send a PR to add one.

**Comment by alanakbik** [comment]
Hi @jfilter cool thanks for pointing this out!

I am trying to reproduce the error with a string that is not whitespace tokenized but not getting this error. Could you post a code snippet that causes the error?

**Comment by jfilter** [comment]
Okay, I investigated it a little bit more. I only happens in certain constellations. For instance here:

```python
from flair.models import SequenceTagger
from flair.data import Sentence

tagger = SequenceTagger.load('ner-ontonotes')

text = 'It all boils down to a simple question:    If you are happy with the globalism that has infected our nation on countless levels with New World Order establishment favorites like HW Bush, Bill, W Bush and Obama the past 24 years and want to further erode America, choose Hillary, Ted Cruz or John Kasich who are all more of the same controlled puppets of the elite banks and world power players who only care about making more money and gaining more power for themselves. '

tagger.predict(Sentence(text))[0].to_dict(tag_type='ner')
```

The four spaces after `to a simple question:` break it. If you remove one space, it works fine.

**Comment by alanakbik** [comment]
Wow very interesting. It seems the error only occurs in the predict method - I'll take a closer look! Thanks for spotting this!!

**Comment by alanakbik** [comment]
Thanks again for spotting this. The minimum example to reproduce the error is: 

```python
from flair.data import Sentence

text = ':    nation on '
sentence = Sentence(text)
print(sentence.to_original_text())
```

The error already happens as you noted already during creating the Sentence without a tokenizer. While PR #227 would fix the error, it would prevent people from using the class with text where multiple whitespaces occur (which some might want to do). 

There's a solution in which the indexes get correctly determined even with multiple whitespaces, namely in the Sentence constructor, instead of: 


```python
                for word in text.split(' '):
                    if word:
                        try:
                            word_offset = text.index(word, offset)
                        except:
                            word_offset = offset

                        token = Token(word, start_position=word_offset)
                        self.add_token(token)
                        offset += len(word) + 1
```

use this to determine offsets: 

```python
# add each word in tokenized string as Token object to Sentence
                word = ''
                for index, char in enumerate(text):
                    if char == ' ':
                        if len(word) > 0:
                            token = Token(word, start_position=index-len(word))
                            self.add_token(token)

                        word = ''
                    else:
                        word += char
```

I'll test a bit - if it works, we can do a PR.

**Comment by jfilter** [comment]
Okay, cool! As long it's fixed I am happy. ;)
