### ISSUE TITLE
French CharLM and NER tagger models

### ISSUE THREAD

**Issue by mhham** [zalandoresearch/flair#238]
I have trained forward and backward french CharLMs based on a french wikipedia dump, as well as a french NER tagger using the CharLMs and french Fasttext embedding, on the WikiNER annotated corpus.

For the CharLMs I have reached the following validation perplexities:
- Forward : 3.15
- Backward : 3.17

For the NER tagger, I have reached the following performances : 

 Set | Precision | Recall 
---- | --------- | ------
Validation | 88.1% | 87.9%
Test | 87.9% | 87.7%
[spaCy](https://spacy.io/models/fr) (for comparison) | 82.24% | 81.61%

You can download them and include them in your framework :
- CharLMs backward : [link](http://ovh.to/TCVF6T) 
- CharLMs forward : [link](http://ovh.to/ef1YkJK) 
- NER tagger : [link](http://ovh.to/xNUbZ7v)

**Comment by alanakbik** [comment]
@mhham wow great results! 

Thanks very much for making these models available - we'll include them in the next release!

**Comment by alanakbik** [comment]
@mhham which WikiNER corpus did you use? In the [WikiNER Github](https://github.com/dice-group/FOX/tree/master/input/Wikiner), there is a wp2 and a wp3 version for French (and all other languages).

**Comment by mhham** [comment]
I used the aij-wikiner-fr-wp3 one from the WikiNER Github you mentioned

**Comment by alanakbik** [comment]
Ok, thanks!

**Comment by aschmu** [comment]
Hi, just a quick question, do we know what parameters were used to train the final model? I'm trying to reproduce the metrics using the wikiner dataset.

**Comment by sylvanusmahe** [comment]
Good morning ,
i am having a strange error will loading flair french NER models. 
it seems that the download link is no longer valide.

can you help please me ?

![image](https://user-images.githubusercontent.com/42295558/91549866-ebf63900-e927-11ea-8acd-968918bdbe81.png)

**Comment by alanakbik** [comment]
@sylvanusmahe - see #1831

**Comment by BouriMohammed** [comment]
Hello, Please how I can extract the the wp3 file ?
