### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by omerarshad** [zalandoresearch/flair#248]
when training on dataset of emerging entitiy recognition, memory error occurs, even when using small batch size

**Comment by alanakbik** [comment]
Hi @omerarshad that's strange. Could you give us more info: How much Cuda memory do you have? What embeddings are you using? Where exactly do you get the oom error?

**Comment by omerarshad** [comment]
I have 12 Gb memory, i am using crawl, mix english forward, mix eng backward embeddings to train sequence model on W-NUT emerging entities. I am using example provided in docs.

here is the error : 

![error](https://user-images.githubusercontent.com/16164105/49067329-116e8400-f224-11e8-8536-0b997fdc0585.png)

**Comment by alanakbik** [comment]
could you try setting embeddings_in_memory to False in the trainer? Does it run through then?

**Comment by omerarshad** [comment]
i tried tha but same error persists

**Comment by tabergma** [comment]
Can you please share the following things with us:

- Version: Which flair version are you using?
- Environment: What kind of operation system are you using?
- Code: Can you please share the exact code you are using with us, so that we might be able to reproduce the problem.
- What did you already tried to solve the issue?
- When does the error occur exactly?

The more details you share the easier it is to actually solve the problem :). Thanks.

**Comment by omerarshad** [comment]
Flair version : 0.3.2
Linux, ubuntu 

Code : 

from flair.embeddings import CharLMEmbeddings
from flair.data import Sentence

glove_embedding = WordEmbeddings('crawl')

from flair.data_fetcher import NLPTaskDataFetcher, NLPTask
from flair.data_fetcher import TaggedCorpus

tag_dictionary = corpus.make_tag_dictionary(tag_type='ner')

from flair.models import SequenceTagger

tagger: SequenceTagger = SequenceTagger(hidden_size=256,
                                        embeddings=glove_embedding,
                                        tag_dictionary=tag_dictionary,
                                        tag_type='ner',
                                        use_crf=True)

# 6. initialize trainer
from flair.trainers import SequenceTaggerTrainer

trainer: SequenceTaggerTrainer = SequenceTaggerTrainer(tagger, corpus)

# 7. start training
trainer.train('resources/taggers/example-ner',
              learning_rate=0.1,
              mini_batch_size=10,
              embeddings_in_memory = False,
              
              max_epochs=150)

**Comment by omerarshad** [comment]
Error occurs after few epochs 
![error2](https://user-images.githubusercontent.com/16164105/49082271-a9329900-f249-11e8-9507-d875758a4cfe.png)
