### ISSUE TITLE
Multilingual PoS and NER models

### ISSUE THREAD

**Issue by alanakbik** [zalandoresearch/flair#259]
Release-0.4 has new classes that enable the training of **multilingual** taggers: By passing a `MultiCorpus` to the `ModelTrainer` and using the new multilingual Flair embeddings (`CharLMEmbeddings('multi-forward')`), we can train taggers that work across languages.

For release-0.4, we want to package a few multilingual taggers: 

- [x] Multilingual PoS tagger trained with universal dependencies for many languages (likely English, German, Dutch, Italian, French, Spanish, Portuguese, Swedish, Norwegian, Danish, Finnish, Polish, Czech). 
- [x] Multilingual NER tagger trained over all 4 CoNLL-03 datasets (English, German, Dutch, Spanish)
- [ ] Multilingual NER tagger trained with WikiNER (English, German, Dutch, French, italian, Spanish, Portuguese, Polish) 
- [ ] maybe other multilingual taggers?

**Comment by stefan-it** [comment]
@alanakbik What do think of including this twitter corpus:

https://github.com/GateNLP/broad_twitter_corpus

From the paper ["Broad Twitter Corpus: A Diverse Named Entity Recognition Resource"](http://www.aclweb.org/anthology/C16-1111). They also provide nice conll-formated datasets :)

**Comment by alanakbik** [comment]
Looks interesting! Is there an overlap between this one and the WNUT-17 corpus, or are they distinct?

**Comment by alanakbik** [comment]
Multilingual NER (4 languages) and PoS (12 languages) added in Flair 0.4.0. 

We will look into mode multilingual models for upcoming releases!

**Comment by anksng1201** [comment]
Hi @alanakbik ,
How can I get a list of supported languages for Multilingual POS tagging?
Thanks
