### ISSUE TITLE
Error while training classificaiton model

### ISSUE THREAD

**Issue by omerarshad** [zalandoresearch/flair#275]
![1](https://user-images.githubusercontent.com/16164105/49235348-39174500-f3fa-11e8-84a7-f3fb6707b3a7.png)

**Comment by omerarshad** [comment]
how to pull 0.4 version? using pip?

**Comment by omerarshad** [comment]
its still there.. just pulled the release-0.4 but error persists

**Comment by tabergma** [comment]
Any updates? Otherwise I'll close the issue.
