### ISSUE TITLE
Torch: not enough memory: you tried to allocate 0GB. Buy new RAM! at /pytorch/aten/src/TH/THGeneral.cpp:204

### ISSUE THREAD

**Issue by davidsbatista** [zalandoresearch/flair#288]
I don't know if this an error specific to configuring the GPU/Pytorch/CUDA env, or is something related with flair:

I get this error whenever I add the CharLMEmbeddings:

```
# initialize embeddings
embedding_types: List[TokenEmbeddings] = [
        WordEmbeddings('de'),
        CharLMEmbeddings('german-forward'),
        CharLMEmbeddings('german-backward'),
    ]
```
if I comment the CharLMEmbeddings:

```
# initialize embeddings
embedding_types: List[TokenEmbeddings] = [
        WordEmbeddings('de'),
        #CharLMEmbeddings('german-forward'),
        #CharLMEmbeddings('german-backward'),
    ]
```
everything runs fine:

Both CharLMEmbeddings are in ~/.flair/embeddings:

```
-rw-rw-r-- 1 ubuntu ubuntu  70M Dec  5 11:17 lm-mix-german-backward-v0.2rc.pt
-rw-rw-r-- 1 ubuntu ubuntu  70M Dec  5 11:17 lm-mix-german-forward-v0.2rc.pt

```

This is the traceback:

```
Traceback (most recent call last):
  File "train_test_model_folds.py", line 135, in <module>
    main()
  File "train_test_model_folds.py", line 129, in main
    embeddings_in_memory=True)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flair/trainers/sequence_tagger_trainer.py", line 142, in train
    embeddings_in_memory=embeddings_in_memory)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flair/trainers/sequence_tagger_trainer.py", line 194, in evaluate
    scores, tag_seq = self.model._predict_scores_batch(batch)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flair/models/sequence_tagger_model.py", line 481, in _predict_scores_batch
    feature, lengths, tags = self.forward(sentences)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/flair/models/sequence_tagger_model.py", line 233, in forward
    sentence_tensor = sentence_tensor.cuda()
RuntimeError: $ Torch: not enough memory: you tried to allocate 0GB. Buy new RAM! at /pytorch/aten/src/TH/THGeneral.cpp:204
```

**Comment by alanakbik** [comment]
Hi @davidsbatista the error message is from torch, but it is weird that this already happens during loading of the embeddings, beaucse the models are not that large. 

How much GPU memory do you have available? 

Could you try loading smaller embedding models? I.e. 

```python
# initialize embeddings
embedding_types: List[TokenEmbeddings] = [
        CharLMEmbeddings('english-forward-fast'),
]
```

**Comment by davidsbatista** [comment]
Hi Alan, thanks for picking it up, so, I'm running my experiment now using:

```
# initialize embeddings
    embedding_types: List[TokenEmbeddings] = [
        WordEmbeddings('de'),
        CharLMEmbeddings('german-forward'),
        #CharLMEmbeddings('german-backward'),
    ]```

and it finished epoch 1 and epoch 2, previously, with WordEmbeddings and both forward and backward CharLMEmbeddings it was throwing that error at the end of epoch 1.

machine is on AWS: p3.2xlarge
- 61GB RAM
- GPU: Tesla V100‑SXM2 w/ 16GB RAM

I'm using an AMI image with: PyTorch with Python3 (CUDA 9.2 and Intel MKL)

**Comment by alanakbik** [comment]
Ah ok - a p3.2xlarge should be enough for most use cases. A few more questions: 

- Did the error occur exactly at the end of Epoch 1, or just somewhere towards the end?
- Is your training data very large? In particular, are there any very long sentences / documents in there? 
- What mini batch size do you use? 

Maybe this error is caused by a very large mini batch getting padded to the longest Sentence and thus being too much for GPU memory. But that would only occur if your documents are very large.

**Comment by davidsbatista** [comment]
Hi again Alan, thanks for following, so, here are some more details:

- The error happens after the last mini-batch is processed, but not just right after, it prints the dashed line and computes something for a few minutes, and then throws the error, can it be already on the start of epoch 2?

- The longest sentence is 491 tokens, I still can look at the average or get an histogram of sentence lengths, but yes, I have a strong feeling they should be over 250~300 tokens;  

- I'm using `mini_batch_size=32`

Can you explain to me a bit on how the padding is done? It will only occur inside each batch and not for the whole dataset, correct?  Another thing, and I'm still learning how PyTorch works, isn't the advantage of PyTorch over Tensorflow/Keras that the computation graph is dynamically, meaning that there is no need to pad, and if it's done inside each batch, what's the main reason?  To gain in speed/data transfer?

Thanks again for your time and support.

**Comment by davidsbatista** [comment]
By cleaning the sentences, and having a maximum of 300 tokens and playing around with the batch_size I managed to make a complete training on the data. 

Thanks for the feedback.
