### ISSUE TITLE
Add Twitter Embeddings

### ISSUE THREAD

**Issue by alanakbik** [zalandoresearch/flair#291]
We used to have pre-trained Twitter embeddings in earlier releases. We somehow removed them, but they are important for good scores on the WNUT task. So put them back in.

**Comment by Alexmac22347** [comment]
@alanakbik Hey, do you have any information on where these twitter embeddings came from? They are working well on WNUT, but I can't find much information about the embeddings themselves
Thanks!

**Comment by alanakbik** [comment]
hello @Alexmac22347 these are the GloVe embeddings computed over 2B tweets available on the [GloVe web page](https://nlp.stanford.edu/projects/glove/). I think there might be more information linked on the GloVe page, either in the paper or the google group.

**Comment by stefan-it** [comment]
No one could ever answer questions about the twitter embeddings in the google group (see e.g. [here](https://groups.google.com/forum/#!searchin/globalvectors/twitter%7Csort:date/globalvectors/DGbjvoGvY9Y/MNUOEClEBgAJ))  🤣
