### ISSUE TITLE
Doesn't match for torch v1.0.0

### ISSUE THREAD

**Issue by QianhuiWu** [zalandoresearch/flair#293]
My torch version is v1.0.0,

When I do `pip install flair`, it says that "Could not find a version that satisfies the requirement torch==0.4.1"

**Comment by tabergma** [comment]
Hi @QianhuiWu! 
We are not yet supporting torch v1.0.0. Your torch version is conflicting with the torch version required for flair.
Did you install flair in any kind of virtual environment? If not, I would recommend to do so. You can, for example, use [virtualenv](https://virtualenv.pypa.io/en/latest/):
```
virtualenv -p python3.6 flair-env
source flair-env/bin/activate
pip install flair
```

**Comment by QianhuiWu** [comment]
Thank you! I finally set up a virtual env with torch 0.4.1, like what you say.

**Comment by nooralahzadeh** [comment]
I am wondering if this is still the case , because for falir==0.4.0 one of the requirements  is torch==1.0 !
