### ISSUE TITLE
Comparison to StanfordCoreNLP

### ISSUE THREAD

**Issue by loretoparisi** [zalandoresearch/flair#315]
Stanford CoreNLP is a reference when dealing with NLP tasks like NER, POS, etc. Typically it's using  CRF classifiers for NER based tasks and it is providing NER models in several languages. Could you please depict the main differences from CoreNLP and if there is a way to share models between CoreNLP and FLAIR?

Thank you.

**Comment by alanakbik** [comment]
Hi @loretoparisi - probably the best intro into Flair is [our recent paper](https://aclanthology.coli.uni-saarland.de/papers/C18-1139/c18-1139) on the underlying Flair embeddings. But to briefly summarize: our sequence tagger is a BiLSTM-CRF architecture as is now default - in this architecture, we utilize a new type of word embedding that is derived from character-level language modeling. These embeddings are very powerful, allowing us to train and package models for NER / PoS for several languages (see documentation) that are the current state-of-the-art. 

In version 0.4 of Flair (released yesterday), we also add multilingual NER and PoS models - these models can accurately predict tags for text in different languages. Our NER model handles 4 languages, and the PoS model 12. So all you need to do is instantiate one single model and can then process text in any supported language.

As of version 0.4, we also add BERT and ELMo embeddings. This allows you to train sequence labeling or text classification models with any combination of classic word embeddings, Flair, ELMo and BERT, and to also evaluate them against each other. 

Wrt model sharing I am not sure.
