### ISSUE TITLE
Question about python statements

### ISSUE THREAD

**Issue by ducalpha** [zalandoresearch/flair#32]
I encountered a "weird"/advanced python statement which has a colon at the beginning as follows:

```# 1. get the corpus
corpus: TaggedCorpus = NLPTaskDataFetcher.fetch_data(NLPTask.CONLL_03).downsample(0.1)
print(corpus)
```

Could you please explain what the python statement (which uses a colon after a name at the beginning of the statement) means? I tried to search for usage of colon in Python but could not found the answer.
```corpus: TaggedCorpus = NLPTaskDataFetcher.fetch_data(NLPTask.CONLL_03)```

Thanks.

**Comment by alanakbik** [comment]
Hi Duc, 

this syntax was introduced in python 3.6 and allows you to declare types for your variables. So, by writing `corpus: TaggedCorpus` you are communicating that the object you are receiving from the data fetcher is an object of type `TaggedCorpus`. 

Some argue that declaring types for your variables and using method signatures increases the clarity of your code. Also, if you declare types, IDEs like pycharm can check your code as you write, and for instance alert you to errors, give hints for autocomplete and allow you to jump into objects. 

But this syntax is optional, so you can also leave it out:

`corpus = NLPTaskDataFetcher.fetch_data(NLPTask.CONLL_03)`

works just as well! 

Hope this helps!
