### ISSUE TITLE
Support half precision training (language model)

### ISSUE THREAD

**Issue by stefan-it** [zalandoresearch/flair#324]
Hi,

I would be an awesome improvement if we could train language models with half precision, e.g. the latest NVIDIA GPU generation (RTX cards) supports it very well.

NVIDIA has the `apex` library, which provides utils for fp16 support.

They also include a language model training example with half precision:

https://github.com/NVIDIA/apex/tree/master/examples/word_language_model

**Comment by kashif** [comment]
Indeed, all my refactoring are for this general usecase of distributed fp16 training.

**Comment by khoa-ho** [comment]
APEX now includes `amp` for automatic mixed precision
https://developer.nvidia.com/automatic-mixed-precision
```
from apex import amp

model, optimizer = amp.initialize(model, optimizer)

with amp.scale_loss(loss, optimizer) as scaled_loss:
    scaled_loss.backward()
```

**Comment by stefan-it** [comment]
Support for fp16 was added with the latest *0.4.3* version, so I'm closing here :)

**Comment by rajharshiitb** [comment]
@stefan-it where can I find some examples on "How to use fp16 while inference?" Simply converting loaded model to half doesn't seem to work. Please help.
Thanks.

**Comment by stefan-it** [comment]
Hi @rajharshiitb , I think you can use pass the `use_amp` argument to your `.train()` or `.fine_tune()` call in your training:

https://github.com/flairNLP/flair/blob/b774774752c8338aab3d620f7e5062f66ec7a69d/flair/trainers/trainer.py#L106
