### ISSUE TITLE
printing output predictions of NER model in a text file

### ISSUE THREAD

**Issue by vikas95** [zalandoresearch/flair#328]
Hi  @alanakbik,

Thanks a lot for releasing the new version of FLAIR, it is very convenient to have both BERT and FLAIR in the same repo. 

I was wondering if a flag can be added to write the output/predictions of NER model in a text file. The reason for my request is that various NER shared tasks have their own evaluation metrics, especially in the case where dataset is annotated using BRAT or other similar tool. In such cases, we have to feed the prediction .txt file to the evaluation script. 
This feature will be very helpful for most of us who are using FLAIR for NER shared tasks. 

I think the latest version of BERT also provides the flag to write the output predictions in text file. 

Looking forward for your kind response,

**Comment by alanakbik** [comment]
Hi @vikas95 - yes I think we could add something like this. Do you mean like a routine that you can call with a trained model (i.e. the final model after training) that prints the output into a file? Do you have a list of formats that this routing should ideally support? 

Note that during training we already write results into a column format suitable for evaluation with the CoNLL-03 evaluation script - it is the "text.tsv" that is always generated during training of the SequenceTagger.

**Comment by vikas95** [comment]
Hi @alanakbik,

Thanks for the reply and apologies for asking this question, I dint check the "test.tsv" file before raising this feature request. 

I just had one last thought - It may be easier for others to convert the output of FLAIR (CoNLL-03 format) to their required format if printed sentence sequences are same as that of the input files. 
The current predictions are printed according to the length of the sentences (i.e. sentences with same lengths are printed together coz of batching) but this shuffles the orders of the sentences. 

Thanks again for the response.
