### ISSUE TITLE
Pretrained medtext

### ISSUE THREAD

**Issue by prabhatM** [zalandoresearch/flair#331]
Hi, 
Flair looks interesting. Any pretrained model for medical text NER?

**Comment by alanakbik** [comment]
We don't currently have one, but would be very interested to see how Flair works on a biomedical task. We believe a character-level model would work really well here. 

I think @tmills is working on something like this and has done a comparative evaluation that he'll share soon (#173).

Anyways, if you are interested in training an LM for medtext, we'd be happy to hear about your progress!

**Comment by tmills** [comment]
Hi @prabhatM, as @alanakbik mentioned I have been testing flair with some biomedical tasks, but I'm specifically focusing on extracting information from clinical questions right now. I have not tested yet on straightforward NER task like detecting diseases, signs/symptoms, etc., but if you're interested I'd be happy to share what I know and/or work together on an evaluation.

**Comment by prabhatM** [comment]
Dear Alan,

Thank you for responding to my query. I am working on analysis of free
clinical text.
After a few testing, I am trying to adopt an NER discovery process and for
that I am looking for a pre-trained model. If I come across, I will update
you.

Thank you for @tmills reference.

Regards

Prabhat MOHANTY

**Comment by prabhatM** [comment]
Dear Tim,

It's great to know that you are working in the bionlp domain. I recently
stumbled upon Flair and am hugely impressed by its premise.

I too have interest in diagnostic clinical questions. But I started with
identification the disease and findings from the free clinical text. I was
thinking of training multiword tokens with clinical terminologies. I am
sure you would be needing the same.
I am so eager to know about your work. Please point me to some links or
share a little. I would love to share whatever  resources I come across
with you.

Regards

Prabhat MOHANTY

**Comment by tmills** [comment]
@prabhatM please take a look at my github profile for links to my research page. I work on apache ctakes and do lots of NLP/information extraction on medical texts. Feel free to email me at the address there to follow up so we don't totally derail the issue thread :).

**Comment by prabhatM** [comment]
Hi Tim,

Thank you for your response. I will follow your lead.

Happy New Year.

Regards

Prabhat MOHANTY

**Comment by alanakbik** [comment]
Release 0.4.1 has several pre-trained embeddings (Flair and ELMo embeddings) for medical text. So closing this thread, but feel free to reopen if you have more questions!
