### ISSUE TITLE
BERT embeddings - which layers?

### ISSUE THREAD

**Issue by mvss80** [zalandoresearch/flair#334]
When I extract BERT embeddings, the size of embeddings are 3072 for bert-base-uncased and 4096 for bert-large-uncased. I take this to mean it is extracting embeddings from 4 layers, presumably -1,-2,-3,-4. Is that correct and is it in that order? Is there a way to extract vectors from other hidden layers (eg. -5 through -12 for bert-base-uncased)?

**Comment by alanakbik** [comment]
hi @mvss80 yes you can set the layers parameter when instantiating `BertEmbeddings` to indicate which layers you want. For instance, you could do: 

```python
embeddings = BertEmbeddings(layers='-5, -6')
sentence = Sentence('Berlin is great !')

embeddings.embed(sentence)

print(sentence[0])
print(len(sentence[0].embedding))
```

To select only layers 5 and 6. You can pass the layers you want in a comma separated list string. So if you want the other layers, simply add them to this string.
