### ISSUE TITLE
Pretrained semantic role labeling model(s)?

### ISSUE THREAD

**Issue by KeepingItClassy** [zalandoresearch/flair#335]
I saw this image on LinkedIn of what looks like a very accurate semantic role labeler/tagger, and it was attributed to Flair:

![ext](https://user-images.githubusercontent.com/12824699/50499964-ab337780-0a02-11e9-9e65-c3ced242e32b.jpeg)

However, I can't find a semantic tagger among the [pretrained tagging models](https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_2_TAGGING.md); I'm only seeing NER, POS, syntactic chunking, and frame models. Is this a custom/proprietary model that's not publicly available, or am I looking in the wrong place?

**Comment by alanakbik** [comment]
Hi @KeepingItClassy - this screenshot is from a "fashion" NER model that is currently proprietary to Zalando, so unfortunately we don't currently bundle it with the Flair release. 

(But we do include general NER models such as the Ontonotes model which has a lot of classes you might find useful, as well as our frame detection model.)

Should you be interested in adding a frame-semantic parser to Flair we'd be very happy! Something like a FrameNet or PropBank parser has been on our list for a while, but we haven't yet gotten around to working on this.

**Comment by KeepingItClassy** [comment]
@alanakbik thank you for your quick reply! I'll try to contribute a pretrained model when I get the chance.
