### ISSUE TITLE
Text Generation Performance

### ISSUE THREAD

**Issue by bttahir** [zalandoresearch/flair#338]
I am just curious. Would using this approach (contextualized string embedding) generate much better aka readable text? My intuition would be it should do better than some char-RNN model since it is looking at much more than just the sequence of the previous few characters but wanted to ask how the results look.

**Comment by alanakbik** [comment]
Hello @bttahir we include a method for text generation into the `LanguageModel` class. You can call this snippet to check out text generation: 

```python
from flair.embeddings import FlairEmbeddings

# get the English news forward language model
model = FlairEmbeddings('news-forward').lm
temperature = 0.2

# Complete this text
prefix = '\nThe meaning of life is'

# Generate five times
for i in range(5):
    text = model.generate_text(prefix=prefix, temperature=temperature, number_of_characters=200, break_on_suffix='\n')
    print(text)
```

Interestingly, we include multilingual language models. If you ask such a model to complete a sentence, it will nearly always complete in the same language. Check this example for English and German: 

```python
from flair.embeddings import FlairEmbeddings

# get the multilingual forward language model
model = FlairEmbeddings('multi-forward').lm
temperature = 0.2

# Complete this English text
prefix = '\nThe meaning of life is'

# Generate five times
for i in range(5):
    text = model.generate_text(prefix=prefix, temperature=temperature, number_of_characters=200, break_on_suffix='\n')
    print(text)

# Complete this German text
prefix = '\nDer Sinn des Lebens ist es,'

# Generate five times
for i in range(5):
    text = model.generate_text(prefix=prefix, temperature=temperature, number_of_characters=200, break_on_suffix='\n')
    print(text)
```

So, you can check out text generation quality with the different language models. Hope this helps!

**Comment by bttahir** [comment]
Thanks! I looked at the generate_text method and just to confirm you are doing a greedy search? Is there a beam search implementation?

**Comment by alanakbik** [comment]
Yes, it is greedy. We don't have a beam search yet but would be happy if someone were to add this!

**Comment by SolsticeProjekt** [comment]
I'm confused. The code presented above causes an error: `TypeError: 'NoneType' object is not callable`
Note, I'm not asking for having it fixed.
I'm mentioning it, because it probably shouldn't cause an error.

```
from flair.embeddings import FlairEmbeddings

# get the English news forward language model
model = FlairEmbeddings('news-forward').lm
temperature = 0.2

# Complete this text
prefix = '\nThe meaning of life is'

# Generate five times
for i in range(5):
    text = model.generate_text(prefix=prefix, temperature=temperature, number_of_characters=200, break_on_suffix='\n')
    print(text)
```
