### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by Huijun-Cui** [zalandoresearch/flair#339]
**Describe the bug**
When I load the previous trained model from check point this bug happend

**To Reproduce**
from pathlib import Path
from flair.trainers import ModelTrainer
from flair.data import TaggedCorpus
path = './checkpoint_log/glove'
data_path = './datasets'
columns = {0: 'text', 1: 'ner'}
from flair.data_fetcher import NLPTaskDataFetcher
corpus: TaggedCorpus = NLPTaskDataFetcher.load_column_corpus(data_path, columns,
                                                                 train_file='train.txt',
                                                                 test_file='test.txt',
                                                                 dev_file='test.txt')
trainer = ModelTrainer.load_from_checkpoint(Path(path + '/final-model.pt'),'SequenceTagger', corpus)

**Comment by alanakbik** [comment]
Hello @Huijun-Cui are you loading a model to continue training or do you just want to predict? 

If you want to continue training, you need to restore from the last checkpoint, not the final model. Checkpoints are written out at each epoch as "checkpoint.pt", but only if you use the `checkpoint=True` option in the model trainer. So, during first training, do 

```python
trainer = ModelTrainer(classifier, corpus)

# train with checkpointing
trainer.train('./',
              checkpoint=True)
```

Then, if you want to resume training from the last checkpoint, do: 

```python
trainer = ModelTrainer.load_from_checkpoint(Path(path + '/checkpoint.pt'),'SequenceTagger', corpus)
```

But if you only want to load the final model for prediction, you can skip the trainer class and do: 

```python
tagger = SequenceTagger.load_from_file('final-model.pt')
```

**Comment by Huijun-Cui** [comment]
@alanakbik  It`s so helpful , by this I solve my problem,thank you !

**Comment by alanakbik** [comment]
Great!
