### ISSUE TITLE
Update of torch version

### ISSUE THREAD

**Issue by stefan-it** [zalandoresearch/flair#34]
Hi,

I'm currently running `flair` in a nvidia-docker flavoured container using `pyenv` and Python 3.7. When installing `flair` via `pip` (or from source via `pip install -e .`) the following error message appears:

```bash
root@599cf5a2dde2:~/flair# pip install flair
Collecting flair
  Downloading https://files.pythonhosted.org/packages/1f/08/b2bdb5ef305227a7dacfc69b0c16689de21e70b9d76e3d07eefa1690311b/flair-0.1.1.tar.gz
Collecting torch==0.4.0 (from flair)
  Could not find a version that satisfies the requirement torch==0.4.0 (from flair) (from versions: 0.1.2, 0.1.2.post1, 0.4.1, 0.4.1.post2)
No matching distribution found for torch==0.4.0 (from flair)
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

With `0.4.1.post2` training runs perfectly, so I would like to ask if we can bump the Torch version?

Notice: using `0.4.1` has a strange `numpy` bug, which is discussed [here](https://github.com/pytorch/pytorch/issues/9903).

**Comment by alanakbik** [comment]
I think we can bump the version for release 0.3!

**Comment by tabergma** [comment]
Torch version updated on release-0.3 branch, will be included in the next release.
