### ISSUE TITLE
Sequence tagging side effects

### ISSUE THREAD

**Issue by Nilabhra** [zalandoresearch/flair#347]
As a side effect of sequence tagging e.g. NER, the embeddings per token is saved. This causes out of memory error `RuntimeError: $ Torch: not enough memory: you tried to allocate 0GB. Buy new RAM! at /pytorch/aten/src/TH/THGeneral.cpp:201` when tagging a large number of sequences. A simple fix is to call clear_embeddings on the batches just before the loop exit.

**Comment by alanakbik** [comment]
Ah yes that's true - thanks for spotting this! Would you be interested in putting in a pull request to fix this?

**Comment by Nilabhra** [comment]
Sure, will make a PR tonight.

**Comment by alanakbik** [comment]
Great, thanks!

**Comment by Nilabhra** [comment]
Another way to boost performance would be to create batches from a sorted list instead of sorting within the batch. This way, a minimum amount of compute and memory is wasted due to padding. I can add this to the PR too.

Also it would be nice to get visual feedback when processing a lot of sequences. Something like tqdm would come in handy here (only if verbosity is set to true). I can also add this to the PR if you think it's necessary.

**Comment by alanakbik** [comment]
Yes good idea with the pre-sorting. Also agree that tqdm would be helpful. If you can add both to the PR that would be great!

**Comment by Nilabhra** [comment]
Great! Will do so.

**Comment by alanakbik** [comment]
closed by #353
