### ISSUE TITLE
Problem loading corpus

### ISSUE THREAD

**Issue by frtacoa** [zalandoresearch/flair#371]
Hello guys,

I am following your tutorial about [hyperparameters optimization](https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_8_MODEL_OPTIMIZATION.md), but there seems to be a problem when loading the `NLPTask.AG_NEWS` corpus:

```py
from flair.data_fetcher import NLPTaskDataFetcher, NLPTask
corpus: TaggedCorpus = NLPTaskDataFetcher.load_corpus(NLPTask.AG_NEWS)
```

The code from above returns the following error:

```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-17-b457eea87ed8> in <module>
----> 1 corpus: TaggedCorpus = NLPTaskDataFetcher.load_corpus(NLPTask.AG_NEWS)

/usr/local/lib/python3.6/dist-packages/flair/data_fetcher.py in load_corpus(task, base_path)
    190         # for text classifiers, we use our own special format
    191         if task == NLPTask.IMDB.value or task == NLPTask.AG_NEWS.value:
--> 192             return NLPTaskDataFetcher.load_classification_corpus(data_folder)
    193
    194     @staticmethod

/usr/local/lib/python3.6/dist-packages/flair/data_fetcher.py in load_classification_corpus(data_folder, train_file, test_file, dev_file)
    345         # automatically identify train / test / dev files
    346         if train_file is None:
--> 347             for file in data_folder.iterdir():
    348                 file_name = file.name
    349                 if 'train' in file_name:

/usr/lib/python3.6/pathlib.py in iterdir(self)
   1079         if self._closed:
   1080             self._raise_closed()
-> 1081         for name in self._accessor.listdir(self):
   1082             if name in {'.', '..'}:
   1083                 # Yielding a path object for these makes little sense

/usr/lib/python3.6/pathlib.py in wrapped(pathobj, *args)
    385         @functools.wraps(strfunc)
    386         def wrapped(pathobj, *args):
--> 387             return strfunc(str(pathobj), *args)
    388         return staticmethod(wrapped)
    389

FileNotFoundError: [Errno 2] No such file or directory: '/home/<username>/.flair/datasets/ag_news'
```

Can I have some help to solve this? Or, if there is another way to try the hyperparameter optimization from the tutorial, please let me know.
Thanks!

**Comment by tabergma** [comment]
The AGNews dataset is not included in Flair by default. You first need to download the dataset [here](https://www.di.unipi.it/~gulli/AG_corpus_of_news_articles.html), convert it to the FastText format and then point the `NLPTaskDataFetcher` to the source path. Also take a look at 
[tutorial 6](https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_6_CORPUS.md#reading-a-text-classification-dataset).

We will update the tutorial accordingly.

**Comment by frtacoa** [comment]
Got it. Thanks for pointing this out.

**Comment by Santosh-Gupta** [comment]
> The AGNews dataset is not included in Flair by default. You first need to download the dataset [here](https://www.di.unipi.it/~gulli/AG_corpus_of_news_articles.html), convert it to the FastText format and then point the `NLPTaskDataFetcher` to the source path. Also take a look at
> [tutorial 6](https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_6_CORPUS.md#reading-a-text-classification-dataset).
> 
> We will update the tutorial accordingly.

It looks like this is the case for tutorial 7 as well? I'm getting a 'FileNotFoundError: [Errno 2] No such file or directory: '/root/.flair/datasets/conll_03'' error
