### ISSUE TITLE
"TypeError: expected str, bytes or os.PathLike object, not NoneType"

### ISSUE THREAD

**Issue by jneto04** [zalandoresearch/flair#374]
**Hello, I'm trying to run Flair on the Google Cloud. But every time I run a test I get this error:**

Traceback (most recent call last):
  File "test_flair.py", line 1, in <module>
    from flair.data import Sentence
  File "/usr/local/lib/python3.6/dist-packages/flair/__init__.py", line 2, in <module>
    from . import models
  File "/usr/local/lib/python3.6/dist-packages/flair/models/__init__.py", line 1, in <module>
    from .sequence_tagger_model import SequenceTagger
  File "/usr/local/lib/python3.6/dist-packages/flair/models/sequence_tagger_model.py", line 12, in <module>
    import flair.embeddings
  File "/usr/local/lib/python3.6/dist-packages/flair/embeddings.py", line 7, in <module>
    import gensim
  File "/usr/local/lib/python3.6/dist-packages/gensim/__init__.py", line 5, in <module>
    from gensim import parsing, corpora, matutils, interfaces, models, similarities, summarization, utils  # noqa:F401
  File "/usr/local/lib/python3.6/dist-packages/gensim/parsing/__init__.py", line 4, in <module>
    from .preprocessing import (remove_stopwords, strip_punctuation, strip_punctuation2,  # noqa:F401
  File "/usr/local/lib/python3.6/dist-packages/gensim/parsing/preprocessing.py", line 40, in <module>
    from gensim import utils
  File "/usr/local/lib/python3.6/dist-packages/gensim/utils.py", line 44, in <module>
    from smart_open import smart_open
  File "/usr/local/lib/python3.6/dist-packages/smart_open/__init__.py", line 1, in <module>
    from .smart_open_lib import *
  File "/usr/local/lib/python3.6/dist-packages/smart_open/smart_open_lib.py", line 45, in <module>
    from boto.compat import BytesIO, urlsplit, six
  File "/usr/lib/python3/dist-packages/boto/__init__.py", line 1216, in <module>
    boto.plugin.load_plugins(config)
  File "/usr/lib/python3/dist-packages/boto/plugin.py", line 92, in load_plugins
    for file in glob.glob(os.path.join(directory, '*.py')):
  File "/usr/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**The test I'm running on is this:**

from flair.data import Sentence
from flair.models import SequenceTagger

sentence = Sentence('I love Berlin .')

tagger = SequenceTagger.load('ner')

tagger.predict(sentence)

**The settings for my VM instance are:**
-> 8 vCPUs with 32gb
-> 1 NVIDIA Tesla K80
-> Ubuntu 16.04
-> Cuda 10.0

Thank you!

**Comment by alanakbik** [comment]
Hello @jneto04 thanks for reporting this. It seems like the error is already thrown at the import statement and is somehow thrown during the import of the gensim library. 

To debug, could you print the version of gensim etc. that are installed in your virtualenvironment on google cloud?

**Comment by alanakbik** [comment]
Thanks - one more question: do you have a virtual environment or did you install flair directly on the machine? If not, could you try setting up a fresh virtual environment and installing flair there?

**Comment by jneto04** [comment]
I have a virtual machine (virtual environment) in the Google Cloud.

However, I created a new virtual machine and reinstalled everything that is needed, but I continue with the error. :(

Thanks again!

**Comment by jneto04** [comment]
I was able to solve the problem. Apparently the problem was in the Gensim, triggered by the Boto. What I did was:

```
sudo pip3.6 uninstall boto
sudo pip3.6 install boto
```

And everything worked perfectly!

Thankful!

**Comment by alanakbik** [comment]
Ah great - thanks for sharing the solution!

**Comment by Gru-Preet** [comment]
what about python ?
i am running my code in python. But got a problem.

**TypeError: expected str, bytes or os.PathLike object, not NoneType**

**Comment by alanakbik** [comment]
Can you post a minimal code example to reproduce the error?

**Comment by sayan231** [comment]
actually i am too running a project of fruit recognization on kraggle kernel where i uploaded a zip folder of the dataset containing train test and valid folder and among them different types of fruits folder but when i am running the code it is giving error as expexted str,  bytes or os. PathLike objects,  not list....... 

i used the code... 
trainpath=os.listdir('../input/data/data/train/')

**Comment by ShivamPanchal** [comment]
Anyone resolved it? @sayan231 @Ammy143

**Comment by Virako** [comment]
I was a similar error with python and Django, the problem was an empty folder. When you are reading folders, python check dirname, if the dirname is None, return error.

Steps to found empty folders are:

* Review the error trace, and search what is the library that are calling to  function dirname in /usr/lib/python3.6/posixpath.py (in the example /usr/lib/python3/dist-packages/boto/plugin.py", line 92, in load_plugins) 
* Inside the function (load_plugins), put debugger trace and search what is the folder that call to dirname function and send None param

**Comment by nesspll** [comment]
Turn out I forgot to add: `__init__.py` in a folder I was calling as a package, that solved the issue
