### ISSUE TITLE
Documentation: Clarification on Reading A Sequence Labeling Dataset

### ISSUE THREAD

**Issue by skilfullycurled** [zalandoresearch/flair#379]
Hi,

First, thanks so much for this library, it is a lot more salient than others!  The tutorials are great but there's one area (so far) that I could use some clarification on and consequently, maybe the documentation, too.

In Tutorial 6 - Creating and Reading a Corpus, formatting the annotation file in the section on [reading a sequence labeling dataset ](https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_6_CORPUS.md#reading-a-sequence-labeling-dataset) is very clear.

However, assuming that train.txt, test.txt, and dev.txt are the files containing the actual sentences, then the following questions remain: 

1. What should the sequence labeling dataset be called (e.g. labels.csv)?
2. Where should it be located (if different from ```data_folder```)?
3. How is it loaded such that it can be used by ```NLPTaskDataFetcher.load_column_corpus(...)```.  For example, does the program simply "know" to load it given the proper file name and location? 
4. Does the program automatically save the corpus?
5. If so what will it be called and where will it be saved to (if different from ```data_folder```)?

As an aside, another suggestion I have is adding a line such as (addition in italics): 

> To read such a dataset, define the column structure as a dictionary and use a helper method. _See section 3.1 of this [blog post](https://towardsdatascience.com/text-classification-with-state-of-the-art-nlp-library-flair-b541d7add21f) for how to split your files into training, testing, and development sets._

Thanks much!
Benjamin

**Comment by skilfullycurled** [comment]
Ah, okay, yes, thank you, that does clarify it, but unfortunately it brings up the flip side of the question which is, given the following statement:

> This gives you a ```TaggedCorpus``` object that contains the train, dev and test splits, each has a list of Sentence.

If the train/test/dev files are the sequence labeling files where the first row is interpreted as:
```
text -> George
pos -> N
ner -> B-PER
```
which deliver a ```TaggedCorpus``` called ```corpus```, where is it pulling the sentence info from such that the following is possible:
```
print(corpus.train[0].to_tagged_string('ner'))
George <B-PER> Washington <I-PER> went to Washington <B-LOC> .
```

Regarding the saving of the corpus, how then in Tutorial 7, when training a [sequence labeling model](https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_7_TRAINING_A_MODEL.md#training-a-sequence-labeling-model) would you train a sequence labeling model with your own corpus?  Would you simply replace:

```
# 1. get the corpus
corpus: TaggedCorpus = NLPTaskDataFetcher.load_corpus(NLPTask.CONLL_03).downsample(0.1)
print(corpus)
```
with
```
corpus: TaggedCorpus = NLPTaskDataFetcher.load_column_corpus(data_folder, columns,
                                                              train_file='train.txt',
                                                              test_file='test.txt',
                                                              dev_file='dev.txt')
```
Bonus question! Later in [multi-dataset training](https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_7_TRAINING_A_MODEL.md#multi-dataset-training) how would you add the corpus you made to the MultiCorpus?
```
corpus: MultiCorpus = NLPTaskDataFetcher.load_corpora([NLPTask.UD_ENGLISH, NLPTask.UD_GERMAN]).downsample(0.1)
```

Perhaps...

```
column_corpus: TaggedCorpus = NLPTaskDataFetcher.load_column_corpus(data_folder, columns,
                                                              train_file='train.txt',
                                                              test_file='test.txt',
                                                              dev_file='dev.txt')
multi_corpus: MultiCorpus = NLPTaskDataFetcher.load_corpora([column_corpus,NLPTask.UD_ENGLISH).downsample(0.1)
```
Thank you so much for these clarifications! 

I'm actually quite excited to try it out.  I hope the questions will be fruitful at the very least, perhaps even by linking to the thread.

**Comment by alanakbik** [comment]
Hello @skilfullycurled yes that is how you would load your own corpora and multicorpora. I think we can add some clarifications to the docs to make this easier to understand! 

With regards to the column file: sentences are separated by empty lines, so they typically look like this: 

```console
George N B-PER
Washington N I-PER
went V O
to P O
Washington N B-LOC

Johnny N B-PER
Berlin N I-PER
went V O
to P O
Berlin N B-LOC
```

this would be two sentences in column format with labels. Hope this clarifies!

**Comment by skilfullycurled** [comment]
It does.  Perfect.  Follow up question:  are you awesome.  yes.  thank you!  : )

I'm not great at pull requests and such, in fact, it would be my first one, but if I figure it out and you haven't gotten to a documentation update (or want to somehow task me with it, I'd be happy to do so.

Thanks again, and I'm looking forward to trying it out!

Benjamin

**Comment by alanakbik** [comment]
Great, thanks - we'd appreciate a PR!
