### ISSUE TITLE
Make case randomization in TextCorpus optional

### ISSUE THREAD

**Issue by snovotney** [zalandoresearch/flair#381]
#219 explained the benefit for randomly flipping the case of a small percentage of sentences. For some use cases where the text is known to be all mono-case, it is useful to turn this feature off.

A proposed solution is to add a parameter in `TextCorpus` to turn off this behavior, defaulting to `True`.

**Comment by tabergma** [comment]
closed by https://github.com/zalandoresearch/flair/pull/382
