### ISSUE TITLE
Dataset Downloader: Basque Named Entities Corpus

### ISSUE THREAD

**Issue by stefan-it** [zalandoresearch/flair#383]
Hi,

I wrote an importer for the Basque Named Entities Corpus (EIEC).

The corpus is available under: http://ixa.eus/node/4486?language=en

The upcoming PR will introduce a new task `NLPTask.NER_BASQUE` and the corresponding section in `download_dataset`.

The original corpus does not include any dev set, so the internal downsampling method will be used :)

PR is coming soon!

**Comment by alanakbik** [comment]
Wow this is great - thanks!
