### ISSUE TITLE
How to deal with Japanese Language model?

### ISSUE THREAD

**Issue by MokkeMeguru** [zalandoresearch/flair#386]
Hello. I want to train Japanese language model.      
But a Japanese sentence has no space between words. (ex. hellomynameisJohn (in English)).    
In Japan, we can some technique splitting words, so should I use this technique in this model?

**Comment by alanakbik** [comment]
Hello @MokkeMeguru - that depends on the use cases for which you want to use the language model. Generally, we train over untokenized text meaning that we just take a corpus as-is without any preprocessing. This tends to work well in the use cases we have looked at. 

Alternatively, you could first tokenize your text and create text files with whitespace-tokenized strings over which you train the LM. This option might be interesting if you have exactly one tokenizer for Japanese and you are sure that you will always use it for your downstream tasks. Then, the language model will mirror the tokenization you expect for downstream tasks and probably give you a minimal boost.

**Comment by MokkeMeguru** [comment]
Thanks to your advice!
