### ISSUE TITLE
Whether to consider adding Attention-mechanism or CNN module?

### ISSUE THREAD

**Issue by illcat** [zalandoresearch/flair#395]
Thank you.

**Comment by alanakbik** [comment]
I am not sure if I understand correctly. Could you elaborate a bit on this issue?

**Comment by djstrong** [comment]
I second that. CNN text classification would be helpful.

@alanakbik What is your opinion? Implementing `DocumentCNNEmbeddings` is the right choice?

**Comment by djstrong** [comment]
I have implemented a simple CNN: #2141
