### ISSUE TITLE
Is Flair uses other columns as features in a sequence tagging problem?

### ISSUE THREAD

**Issue by bsat007** [zalandoresearch/flair#398]
A clear and concise description of what you want to know.
George N B-PER
Washington N I-PER
went V O
to P O
Washington N B-LOC

In this data, does flair uses pos tags(2nd column) as a feature while training the NER model?

**Comment by alanakbik** [comment]
Hello @bsat007 no, our models currently only use the first column, but not any other information such as the POS tag. 

If you would like to experiment with models that also embed POS tags or other information, there was a recent pull request by @tmills that allows you to embed other fields. Check out PR #361 for more information.

**Comment by stefan-it** [comment]
The second column won't be used during training. 

When you import these kind of data format, so have specify the dataset format:

```python
columns = {0: 'text', 1: 'pos', 2: 'ner'}
```

So the column information is only used and need for parsing the dataset :)
