### ISSUE TITLE
ValueError: The given model "spanish-forward" is not available or is not a valid path.

### ISSUE THREAD

**Issue by basque21** [zalandoresearch/flair#409]
I can't load basque nor spanish flair embeddings. Not problem with english or german for example, but if I do: 

`flair_backward = FlairEmbeddings('spanish-forward')` 

i get:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-21-09051c9580a7> in <module>
----> 1 flair_backward = FlairEmbeddings('spanish-forward')

/tertiary/imanol/imanol/env_flair/lib/python3.6/site-packages/flair/embeddings.py in __init__(self, model, detach, use_cache, cache_directory)
    557 
    558         elif not Path(model).exists():
--> 559             raise ValueError(f'The given model "{model}" is not available or is not a valid path.')
    560 
    561         self.name = str(model)

ValueError: The given model "spanish-forward" is not available or is not a valid path.

```

**Comment by stefan-it** [comment]
Hi,

the Flair Embeddings for Spanish and Basque are relatively new and not available in a released version of `flair`.

To use them, you have to use a recent `master` version of this repository. So just:

```bash
git clone https://github.com/zalandoresearch/flair.git
cd flair
pip install -e .
```

And the latest version in `master` will be installed. Then you can use Basque or Spanish models!

**Comment by basque21** [comment]
Thanks! I downloaded them by `wget` and used with the path directly, but thanks anyway!
