### ISSUE TITLE
Execution stop while trying to generate BERT embeddings

### ISSUE THREAD

**Issue by Arjunsankarlal** [zalandoresearch/flair#411]
I followed the same code in the tutorials for BERT embeddings. I used bert-base-cased model. I downloaded initially. After that it throws this issue and stops. Also my mac throws that python stopped unexpectedly.

dyld: lazy symbol binding failed: Symbol not found: _PySlice_Unpack
  Referenced from: /Users/arjun/venv/lib/python3.6/site-packages/torch/lib/libtorch_python.dylib
  Expected in: flat namespace

**Comment by Arjunsankarlal** [comment]
Downgraded the torch version to 0.4.1 and it worked. But the version in requirements.txt is torch==1.0.0

Not sure why this issue occurred.

**Comment by alanakbik** [comment]
Thanks for reporting this - we'll keep an eye on this especially if more people run into this issue!
