### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by basque21** [zalandoresearch/flair#412]
Hi, thanks for your great job! I was wondering if you are planning to create some documentation page like torch, keras or tensorflow have, in order to know all the parameters of each function, etc. 

It would be great, thanks!

**Comment by alanakbik** [comment]
Hi @basque21 thanks that is a good idea - we are currently planning a non-github web site for Flair with documentation so will add such information there!

**Comment by basque21** [comment]
Thanks! nice to know it! Good luck!
