### ISSUE TITLE
Can StackedEmbeddings be used to text classification?

### ISSUE THREAD

**Issue by basque21** [zalandoresearch/flair#414]
It's a question, can StackedEmbeddings be used to text classification or only for sequence labeling? because for textclassifier it's necesary a document embedding, but document embeddings can be created with StackedEmbeddings, isn't it?

Thanks!

**Comment by alanakbik** [comment]
`StackedEmbeddings` are currently a `WordEmbeddings` class, so they cannot directly be used to classify documents. They can only be used for sequence labeling.

However, you can put a stack of word embeddings into one of the `DocumentEmbeddings` classes such as `DocumentPoolEmbeddings` or `DocumentLSTMEmbeddings`. This way, you are  specifying how to aggregate word embeddings for text classification. See also #388 for more discussion.

**Comment by basque21** [comment]
Thanks!
