### ISSUE TITLE
macro_avg_f_score bug

### ISSUE THREAD

**Issue by wakafengfan** [zalandoresearch/flair#417]
In the file flair/training_utils.py, when calculating macro_avg_f_score, I think 'recall' method should be called but 'precision' is called.

![image](https://user-images.githubusercontent.com/44130753/51589926-4b59bf00-1f23-11e9-964a-24ac0bc82589.png)

i think it needs to write like this:
`def macro_avg_f_score(self): 
         class_precisions = [self.precision(class_name) for class_name in self.get_classes()] 
         class_recalls = [self.recall(class_name) for class_name in self.get_classes()]`

**Comment by tabergma** [comment]
Thanks for spotting this!

**Comment by wakafengfan** [comment]
Glad to help :)
