### ISSUE TITLE
Why do embeddings' size and weights change when tagged with POS and/or NER?

### ISSUE THREAD

**Issue by VanHoang85** [zalandoresearch/flair#424]
So, I have this sentence "_the home crowd cheered when **Princeton** took the field_". I created three different Sentence object of this sentence: sentence_1, sentence_2, sentence_3:

For sentence_1, I embedded it using flair embeddings (news-forward + news-backward)
For sentence_2, I tagged it first with a ner tagger and then embedded it with flair.
For sentence_3, I tagged it first with a pos tagger and then embedded it with flair.

I only use the tagger shipped with flair library.

When I got the embeddings of the word **Princeton** and checked their shape, the results were as follow:
Embedding of **Princeton** in sentence_1 --> torch.Size([4096])
Embedding of **Princeton** <S-ORG> in sentence_2 --> torch.Size([8292])
Embedding of **Princeton** <NNP> in sentence_3 --> torch.Size([4096])

When I calculated the cosine similarity of **Princeton** embeddings in sentence_1 and sentence_3, using CosineSimilarity class of torch library, it showed cos=tensor(-0.0057). So they are quite _different_ as I understand the result.

I think this is because flair takes into account pos and ner tags as features when embedding the sentences. But when I read around the Issues, it seems it isn't the case. And when training the LM to generate the embeddings, no linguistic annotations are needed either.

So I wonder why the size and shape of the embeddings change when tagged with POS and NER annotations. Any explanation for this?

Thanks for creating a great library anyway! :)

**Comment by alanakbik** [comment]
Hello @VanHoang85 thanks for your interest! 

Currently, if you use a trained tagger such as 'ner' or 'pos' it will:

- first, embed the sentence with the specific Flair embeddings that it needs (included in the model)
- second, predict tags 

So after calling tagger.predict() on your sentence, you get a sentence that is both embedded as well as has predicted tags. However, in the current version of Flair, the tagger-specific embeddings get removed, so after predicting tags you should only have tags, not embeddings. 

Are you using the current Flair version? If so, the behavior you describe might be a bug - could you then post a minimum code example to get the above behavior so we can investigate?

**Comment by VanHoang85** [comment]
Hi, this is the code I used

`from flair.data import Sentence
from flair.embeddings import StackedEmbeddings, FlairEmbeddings
from flair.models import SequenceTagger

ner_tagger = SequenceTagger.load('ner')
pos_tagger = SequenceTagger.load('pos')
flair = StackedEmbeddings([ FlairEmbeddings('news-forward'), 
                                         FlairEmbeddings('news-backward') ])

sentence = "the home crowd cheered when Princeton took the field"
sentence1 = Sentence(sentence)
sentence2 = Sentence(sentence)
sentence3 = Sentence(sentence)

ner_tagger.predict(sentence2)
pos_tagger.predict(sentence3)

flair.embed(sentence1)
flair.embed(sentence2)
flair.embed(sentence3)

embedding1 = sentence1[5].embedding 
embedding2 = sentence2[5].embedding
embedding3 = sentence3[5].embedding
 
embedding1.shape
# torch.Size([4096])

embedding2.shape
# torch.Size([8292])

embedding3.shape
# torch.Size([8192])`

I don't know why the shapes differ this time when I tried it again this morning. And I have flair-0.4.0 installed on my computer.

**Comment by alanakbik** [comment]
Hello @VanHoang85 thanks for posting the code - I see now that this is an error that was fixed in the master branch. So, if you use the current master branch, you would get 

```console
embedding1.shape
>>> torch.Size([4096])

embedding2.shape
>>> torch.Size([4096])

embedding3.shape
>>> torch.Size([4096])
```

for this code, which is the expected behavior. So you could either

- use the current code from master branch 
- or wait a bit (about 1 week or so) until we release 0.4.1 where this is fixed 

Alternatively, you can add the following lines to your code: 

```python
sentence2.clear_embeddings()
sentence3.clear_embeddings()
```

right after prediction. That will also give you this behavior now without updating the flair library. 

Hope this helps!

**Comment by alanakbik** [comment]
Hi, yes flair 0.4.1. adds support for embedding other features such as PoS tags (see #345).
