### ISSUE TITLE
Cannot install allennlp due to matplotlib dependency conflict

### ISSUE THREAD

**Issue by dennisverspuij** [zalandoresearch/flair#429]
Hello, thanks for the great package. I want to play with ELMoEmbeddings, which requires package allennlp, not installed by default with Flair. However, installing latest allennlp fails because it requires matplotlib==2.2.3, while Flair requires >=3.0.0. When I install allennlp==0.7.0 (without the matplotlib requirement), it still fails because of PyTorch conflicts. Makes me wonder what versions I should use that are actually compatible?

**Comment by stefan-it** [comment]
Did you both install `flair` and `allennlp` from latest `master` branch? In my experiments using ELMo within `flair` I didn't get these error messages (installed via `pip install -e .`) 🤔

**Comment by dennisverspuij** [comment]
If you look at the requirements.txt you'll see that the version conflict is in current master branches.

**Comment by dennisverspuij** [comment]
That's a workaround, and probably a non-working setup if you would like to use functionalities using matplotlib from either Flair or AllenNLP. I am using pipenv and cannot get both packages installed without problem.

**Comment by alanakbik** [comment]
Perhaps a solution would be to relax our dependency constraint to a lower version of matplotlib. Perhaps if we change to matplotlib>=2.2.3 that might do the trick?

**Comment by stefan-it** [comment]
@alanakbik That should work, but we probably should test the plotter/visualization functions with an older version :D

**Comment by dennisverspuij** [comment]
Awesome thanks
