### ISSUE TITLE
What is data format for training a Flair language model

### ISSUE THREAD

**Issue by gccome** [zalandoresearch/flair#430]
First of all, thanks for developing such a great library!
I want to use LanguageModelTrainer to train my own Flair embedding, I am wondering what is the correct data format for train, val, and test data. E.g. should it be one sentence/paragraph per line? Or should it be one huge paragraph for each file?
Many thanks!

**Comment by alanakbik** [comment]
Hello @gccome thanks for your interest! 

We typically train with one sentence per line, but in principle you could also use any other format, such as one document per line, or preserve whitespaces and indentation as-is. 

It depends a bit on your use case. If you just want to tag sentences you can use one sentence per line. If you want to work on document-level tasks, it may make sense to use one document per line. If you want to use in a domain where indentation and line breaks are important (such as html or code) then you should use the text as is. 

Hope this helps!

**Comment by gccome** [comment]
Great. Thanks!
