### ISSUE TITLE
Character-level Language Model works as intended?

### ISSUE THREAD

**Issue by sarthakTUM** [zalandoresearch/flair#44]
Hi,
While stepping through code, following function appears in language_model_trainer.py

` @staticmethod
    def _get_batch(source, i, sequence_length):

        seq_len = min(sequence_length, len(source) - 1 - i)

        data = Variable(source[i:i + seq_len])

        target = Variable(source[i + 1:i + 1 + seq_len].view(-1))

        return data, target`

The dump of data and target shows these values for instance:

**Data Tensor:**
`tensor([[ 60,   2,   5,   9,   3,   4,   5,   6,   1,  12],
        [  2,   8,   1,   7,   6,  77,   6,  15,   8,  12],
        [ 77,  77,  22,   1,   1,  13,   8,   1,   2,  13],
        [ 13,  13,   7,   2,  14,   2,   1,   5,  11,   8],
        [  2,   2,   6,  13,   9,   5,   8,   2,   1,   1],
        [  1,   1,   2,   1,   3,   1,   2,  15,   7,   6],
        [ 27,   6,   8,   6,  11,   7,  11,  22,   4,   5],
        [  4,  11,   2,  13,   4,   4,   1,   9,   8,   1],
        [  5,   4,   3,  16,  15,   8,   8,   7,  13,  13],
        [  6,  22,   5,  13,   2,  13,   2,   1,   8,   7]], device='cuda:0')

Shape: (10, 10)`

**Target Tensor:**
`tensor([  2,   8,   1,   7,   6,  77,   6,  15,   8,  12,  77,  77,
         22,   1,   1,  13,   8,   1,   2,  13,  13,  13,   7,   2,
         14,   2,   1,   5,  11,   8,   2,   2,   6,  13,   9,   5,
          8,   2,   1,   1,   1,   1,   2,   1,   3,   1,   2,  15,
          7,   6,  27,   6,   8,   6,  11,   7,  11,  22,   4,   5,
          4,  11,   2,  13,   4,   4,   1,   9,   8,   1,   5,   4,
          3,  16,  15,   8,   8,   7,  13,  13,   6,  22,   5,  13,
          2,  13,   2,   1,   8,   7,   2,   4,   1,   2,   3,   8,
         11,   9,  18,   3], device='cuda:0')

Shape: (100)`

The output predictions from language_model_trainer is (10, 10, 275) and converted to (100, 275), which means we have 275 scores for each character. (dimensions are reffering to batch_size, sequence_length, output_embedding, and numbers refer to those obtained from test_language_model_trainer.py)

**Question:**
We see that Targets are shifted by sequence_length which is 10 in this case. This means that character at ith position is trained to predict character at i+seq_length position (i+10 position in test code provided). Shouldn't the characterLM predict the next word (i+1th)? Or am I missing something?

Thanks!

**Comment by alanakbik** [comment]
Hi! This implementation is based on the language model in [Pytorch examples](https://github.com/pytorch/examples/tree/master/word_language_model). They explain their approach as follows: 

```
# Starting from sequential data, batchify arranges the dataset into columns.
# For instance, with the alphabet as the sequence and batch size 4, we'd get
# ┌ a g m s ┐
# │ b h n t │
# │ c i o u │
# │ d j p v │
# │ e k q w │
# └ f l r x ┘.
# These columns are treated as independent by the model, which means that the
# dependence of e. g. 'g' on 'f' can not be learned, but allows more efficient
# batch processing.
```
So you read the tensor as a set of columns from top to bottom, i.e. they are always trained to predict the next character. Their implementation is very GPU efficient and according to their and our experiments produces very good LMs. 

Hope this helps!

**Comment by sarthakTUM** [comment]
Thanks! That definitely helps!
