### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'`

### ISSUE THREAD

**Issue by alipetiwala** [zalandoresearch/flair#452]
Getting following error while resuming a training model:

**Describe the bug**

<pre>
`TypeError                                 Traceback (most recent call last)
<ipython-input-3-c3b3f8d2e9fd> in <module>()
      2 
      3 trainer = ModelTrainer.load_from_checkpoint('resources/taggers/example-art/char/best-model.pt', 'SequenceTagger', corpus)
----> 4 trainer.train('resources/taggers/example-art/resume-best-model.pt',checkpoint=True)

~/anaconda3/lib/python3.6/site-packages/flair/trainers/trainer.py in train(self, base_path, evaluation_metric, learning_rate, mini_batch_size, eval_mini_batch_size, max_epochs, anneal_factor, patience, anneal_against_train_loss, train_with_dev, monitor_train, embeddings_in_memory, checkpoint, save_final_model, anneal_with_restarts, test_mode, param_selection_mode, **kwargs)
    111             previous_learning_rate = learning_rate
    112 
--> 113             for epoch in range(0 + self.epoch, max_epochs + self.epoch):
    114                 log_line(log)
    115 

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'`
</pre>
**To Reproduce**

Resume existing model with .pt extension

**Environment (please complete the following information):**
Ubuntu 18.x

**Comment by alipetiwala** [comment]
<pre>
 def load_checkpoint(cls, model_file: Union[str, Path]):
        state = SequenceTagger._load_state(model_file)
        model = SequenceTagger.load_from_file(model_file)

        **epoch = state['epoch'] if 'epoch' in state else None**
        loss = state['loss'] if 'loss' in state else None
        optimizer_state_dict = state['optimizer_state_dict'] if 'optimizer_state_dict' in state else None
        scheduler_state_dict = state['scheduler_state_dict'] if 'scheduler_state_dict' in state else None

        return {
            'model': model, 'epoch': epoch, 'loss': loss,
            'optimizer_state_dict': optimizer_state_dict, 'scheduler_state_dict': scheduler_state_dict
        }
</pre>

The epoch info is not saved in the model file which is causing this issue.

**Comment by stefan-it** [comment]
Are you trying to load a checkpoint file or an already trained and finished model? I can remember this kind of error message when I tried to load a non-checkpoint model.

**Comment by alipetiwala** [comment]
@stefan-it its a trained best model file.

**Comment by stefan-it** [comment]
If you want to use the `load_checkpoint` method, then you need to use the `checkpoint.pt` file.

I think you enabled checkpointing in the example code snippet, so that should work.

If you do not have any model checkpoint, then you can easily use the following snippet:

```python
language_model = LanguageModel.load_language_model('resources/taggers/language_model_forward/best-lm.pt')

```

To load the language model. Then you can use the same parameters as you used in your initial training, e.g.:

```
trainer = LanguageModelTrainer(language_model, corpus)

trainer.train('resources/taggers/language_model_forward_resumed',
              sequence_length=250,
              mini_batch_size=200,
              max_epochs=1,
              checkpoint=True)
```

**Comment by alanakbik** [comment]
Yes the `checkpoint.pt` file is needed to resume training - they are written out every epoch if checkpointing is enabled during training. @alipetiwala does this work for you? If not, feel free to reopen the issue!
