### ISSUE TITLE
Med Text corpus for NER

### ISSUE THREAD

**Issue by prabhatM** [zalandoresearch/flair#463]
Hi,

I have a corpus of medical text in the following format. Can we use this to identify NER ?
----
8621452	<category="SpecificDisease">Type II human complement C2 deficiency</category>. Allele-specific amino acid substitutions (Ser189 --> Phe; Gly444 --> Arg) cause impaired C2 secretion.	<category="SpecificDisease">Type II complement protein C2 deficiency</category> is characterized by a selective block in C2 secretion . The Type II C2 null allele ( C2Q0 ) is linked to two major histocompatibility haplotypes ( MHC ) that differ from the MHC of the more common <category="SpecificDisease">Type I C2 deficiency</category> . To determine the molecular basis of <category="SpecificDisease">Type II deficiency</category> the two Type II C2Q0 genes were isolated and transfected separately into L-cells . Subsequent molecular biology , biosynthetic , and immunofluorescence studies demonstrated that C2 secretion is impaired in <category="SpecificDisease">Type II C2 deficiency</category> because of different missense mutations at highly conserved residues in each of the C2Q0 alleles . One is in exon 5 ( nucleotide C566 -- > T ; Ser189 -- > Phe ) of the C2Q0 gene linked to the MHC haplotype A11 , B35 , DRw1 , BFS , C4A0B1 . The other is in exon 11 ( G1930 -- > A ; Gly444 -- > Arg ) of the C2Q0 gene linked to the MHC haplotype A2 , B5 , DRw4 , BFS , C4A3B1 . Each mutant C2 gene product is retained early in the secretory pathway . These mutants provide models for elucidating the C2 secretory pathway . . -------

A file with more sample text enclosed.

Regards
Prabhat MOHANTY

[med_corpus_sample.txt](https://github.com/zalandoresearch/flair/files/2836257/med_corpus_sample.txt)

**Comment by alanakbik** [comment]
Yes, this looks like an interesting dataset. You would need to convert this into a [sequence labeling format](https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_6_CORPUS.md#reading-a-sequence-labeling-dataset) and could directly train the `SequenceTagger` on this. We'd be curious to hear how well it works!
