### ISSUE TITLE
NER entities change per run 

### ISSUE THREAD

**Issue by dhairyadalal** [zalandoresearch/flair#468]
Is it possible to have an option to freeze the model at prediction (enable pytorch eval() mode) so that the predictions don't change every run? 

For example:
```
from flair.data import Sentence
from flair.models import SequenceTagger

tagger = SequenceTagger.load("ner")

for i in range(10):
    print("iteration: ", i)
    s = Sentence("Boston is the capital of MA.")
    tagger.predict(s)
    for e in s.get_spans("ner"):
        print(e.text, e.score)
    print("--------------------------")
```

Results in: 

> iteration:  0
> Boston 0.9999486207962036
> --------------------------
> iteration:  1
> Boston 0.999962568283081
> --------------------------
> iteration:  2
> Boston 0.9981124401092529
> MA. 0.6125262379646301
> --------------------------
> iteration:  3
> Boston 0.9999322891235352
> MA. 0.5145224928855896
> --------------------------
> iteration:  4
> Boston 0.9999871253967285
> --------------------------
> iteration:  5
> Boston 0.999849796295166
> --------------------------
> iteration:  6
> Boston 0.9999449253082275
> --------------------------
> iteration:  7
> Boston 0.9998575448989868
> --------------------------
> iteration:  8
> Boston 0.9999393224716187
> --------------------------
> iteration:  9
> Boston 0.9999902248382568
> --------------------------

**Comment by alanakbik** [comment]
Hello @dhairyadalal - are you using flair 0.4.0 installed through pip?

If so, this is a known issue (see #416) that we are currently fixing by retraining all models with the newest flair version. On the master branch, the ner model is updated with this fix. So you could check out the master branch and run from there. 

Alternatively, you could wait a bit until we push version 0.4.1 to pip. We originally wanted to already have 0.4.1 ready this week, but now it is looking more like end of next week for the release.

**Comment by dhairyadalal** [comment]
No worries. Appreciate the follow-up. I'll take a look at the main branch.
