### ISSUE TITLE
Inconsistent number of examples and wrong orders for both text classification and sequence tagging

### ISSUE THREAD

**Issue by gccome** [zalandoresearch/flair#469]
I recently found a couple of issues for both sequence tagging and text classification.

First of all, in the output test.tsv file, the number of examples are inconsistent with (slightly less than) original test file. Second, the order of examples in test.tsv is different from original test file. Any specific reason for causing this? 

For 1st issue, I didn't see shuffling eval or test data in the code. 
For 2nd issue, I cannot locate the code that might cause it either.

For text classification, I have 3,000 sentences in my test file, but only output 2,875.
For sequence tagging, I have 5,529 sentences in my test file, but only output 5,516.

**Comment by kubapok** [comment]
I've recently discovered that only documents with at least one label is taken into account into evaluation for text classification (I didn't look at sequence tagging). I'm going to fix this soon, refactor and add some unit tests.

You can check this by:
`grep __label__ test.txt | wc -l`

I suppose it would be 2875

**Comment by gccome** [comment]
@kubapok I just used the command you provided and it returned 3000. All the examples in test file has exactly one label, either 0 or 1.

**Comment by gccome** [comment]
Quick update. I noticed that for sequence tagging, there are 5529 sentences in my test file, but after loading using `load_column_corpus()`, only 5516 sentences are loaded. My test file contains two columns, first column is text, second column is tagging, two columns are tab separated. There is a empty line between each sentence.

**Comment by gccome** [comment]
Just found the reason for sequence tagging loader missing some sentences, it is because of the following code, as some of my tokens start with `#`. However, the order is still off.

`if line.startswith('#'):
    continue`

**Comment by alanakbik** [comment]
Ah ok - yes there are several places where reshuffling happens. For instance, sentences in each mini-batch are ordered by length when using FlairEmbeddings for the padding operation. Also, when you use a model to predict over many sentences, they are ordered by length for optimization purposes (so that short sentences are not padded to very long sequences in a mini-batch).

**Comment by gccome** [comment]
@alanakbik Thanks for the reply. It makes perfect sense.
