### ISSUE TITLE
Keeping a (frozen) branch for each release?

### ISSUE THREAD

**Issue by davidsbatista** [zalandoresearch/flair#476]
Should it not exist a frozen branch for each release? 

I just noticed that there is a release branch for 0.5 but no branch with 0.4; As the project grows this could help track better the changes, and produce a descriptive CHANGELOG.

Anyway, just a suggestion :)

**Comment by alanakbik** [comment]
Hello @davidsbatista - for this, we have the [release tags](https://github.com/zalandoresearch/flair/releases). This allows you to check out the code as it was when a release was produced. Is this what you mean?

**Comment by davidsbatista** [comment]
ah! ok, got it! that's exactly what I meant, going to close this than.
