### ISSUE TITLE
 NLPTaskDataFetcher.load_corpus(NLPTask.CONLL_03), file not found

### ISSUE THREAD

**Issue by Santosh-Gupta** [zalandoresearch/flair#478]
**Describe the bug**

I am trying to follow this tutorial https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_7_TRAINING_A_MODEL.md

and I am getting a file File not found for ` NLPTaskDataFetcher.load_corpus(NLPTask.CONLL_03)`. Similar issue to
https://github.com/zalandoresearch/flair/issues/371

**To Reproduce**
Steps to reproduce the behavior (e.g. which model did you train? what parameters did you use? etc.).

```
from flair.data import TaggedCorpus
from flair.data_fetcher import NLPTaskDataFetcher, NLPTask
from flair.embeddings import TokenEmbeddings, WordEmbeddings, StackedEmbeddings
from typing import List

corpus: TaggedCorpus = NLPTaskDataFetcher.load_corpus(NLPTask.CONLL_03).downsample(0.1)
```

**Expected behavior**

No error should appear, and files should be downloaded 

**Screenshots**

**Environment (please complete the following information):**
 - OS [e.g. iOS, Linux]:
 - Version [e.g. flair-0.3.2]:

Google colab 

**Additional context**

**Comment by stefan-it** [comment]
Hi,

one problem with this dataset is, that both German and English training data cannot be directly obtained from the shared tasks site: https://www.clips.uantwerpen.be/conll2003/ner/

> The English data is a collection of news wire articles from the Reuters Corpus. The annotation has been done by people of the University of Antwerp. Because of copyright reasons we only make available the annotations. In order to build the complete data sets you will need access to the Reuters Corpus. It can be obtained for research purposes without any charge from NIST. 

The shared task site only provides scripts to transform the annotations and the Reuters Corpus into a "real" dataset.

But in some repositories on GitHub you can find the complete training, dev and test dataset (for English). But I'm not sure if we're allowed to integrate them into flair 🤔

**Comment by kpranke** [comment]
> Hi,
> 
> one problem with this dataset is, that both German and English training data cannot be directly obtained from the shared tasks site: https://www.clips.uantwerpen.be/conll2003/ner/
> 
> > The English data is a collection of news wire articles from the Reuters Corpus. The annotation has been done by people of the University of Antwerp. Because of copyright reasons we only make available the annotations. In order to build the complete data sets you will need access to the Reuters Corpus. It can be obtained for research purposes without any charge from NIST.
> 
> The shared task site only provides scripts to transform the annotations and the Reuters Corpus into a "real" dataset.
> 
> But in some repositories on GitHub you can find the complete training, dev and test dataset (for English). But I'm not sure if we're allowed to integrate them into flair 🤔

I tried to use these: https://github.com/synalp/NER/tree/master/corpus/CoNLL-2003
but it's failing to work. Getting this exception: Getting 'Exception: Invalid IOB format!'.

**Comment by alanakbik** [comment]
Try only using the standard files, not the OpenNLP ones.
