### ISSUE TITLE
Is it possible to train Flair to recognize a new entity type? 

### ISSUE THREAD

**Issue by Santosh-Gupta** [zalandoresearch/flair#479]
A clear and concise description of what you want to know.

Is it possible to train Flair to recognize a new entity type? I would like to use Flair to train a model to recognize diseases from test, using a dataset where diseases are tagged in a sentence. 

For example

```
sentence = Sentence('22 patients developed significant thrombocytopenia while receiving prophylactic or therapeutic heparin')

tagger.predict(sentence)
print('The following NER tags are found:')

# iterate over entities and print
for entity in sentence.get_spans('ner'):
    print(entity)
```

Would result in 

```
The following NER tags are found:
DISEASE-span [3]: "thrombocytopenia"
```

**Comment by stefan-it** [comment]
@Santosh-Gupta You just need to follow the IOB tagging scheme and then you need to annotate this new entity in your training, dev and test datasets :)

For e.g. the following format could be used:

```text
22  O
patients    O
developed   O
significant O
thrombocytopenia B-DISEASE
while O
receiving O
prophylactic O
or O
therapeutic O
heparin O
```
