### ISSUE TITLE
Can't we do without naming training_split files?

### ISSUE THREAD

**Issue by prabhatM** [zalandoresearch/flair#480]
Hi,

In preparing a text corpus, it's mentioned that the a large file may be split in the train directory if it's too large as -
corpus/
corpus/train/
corpus/train/train_split_1
corpus/train/train_split_2
corpus/train/...
corpus/train/train_split_X

This means the programme has a provision to read multiple files from a specified directory called "train" or "test". 
Can't we just have multiple files without naming the fragments as train_split_1 / 2/ x etc?
This would help us use some old corpus in flair.

Regards

Prabhat

**Comment by stefan-it** [comment]
@prabhatM You could any file name pattern :) The `flair` training code will collect every file in the `train` folder, see [here](https://github.com/zalandoresearch/flair/blob/master/flair/trainers/language_model_trainer.py#L42). In my experiments I always use the default file name pattern from the `split` tool: `xaa`... `xzz`.

**Comment by stefan-it** [comment]
The only "hard-coded" convention is `valid.txt` and `test.txt` for validation and test dataset, see [here](https://github.com/zalandoresearch/flair/blob/master/flair/trainers/language_model_trainer.py#L165).
