### ISSUE TITLE
What is the release date for v0.4.1

### ISSUE THREAD

**Issue by and-kul** [zalandoresearch/flair#481]
I'm wondering when version 0.4.1 be released.
Since 0.4 a lot of bugs have been fixed

**Comment by alanakbik** [comment]
Probably end of this week!

**Comment by and-kul** [comment]
Thanks

**Comment by alanakbik** [comment]
A quick update: We will push back the release to address some critical issues first (#483 and #486), but it should be only a few days!

**Comment by stefan-it** [comment]
*0.4.1* has been released [today](https://github.com/zalandoresearch/flair/releases/tag/v0.4.1), so I'm closing here :)
