### ISSUE TITLE
Use of term word_weights in language_model

### ISSUE THREAD

**Issue by siddiqaa** [zalandoresearch/flair#496]
In language_model.py, line 272 has variable - "word_weights". Is that actually weights for characters? "word_weight" seems confusing. I am exploring adding beam search in the text generation function so need to understand the current code.

**Comment by alanakbik** [comment]
Hello @siddiqaa thanks for looking into this - a beam search decoder in the LM would be a great addition. 

In this case "word_weights" refers to the distribution that we sample to get the next character, so it's not really a weight and it is typically about characters, not words. We should probably rename this.

But the higher this value for each character, the higher the likelihood to be sampled. This distribution is the result of dividing the predictions by a temperature variable and then raising them through the exponential function.

**Comment by siddiqaa** [comment]
Ok, thanks for clarifying - I assumed weights referred to distribution but "word_weights" instead of "char_weights" confused me. Thanks for the explanation. Let me get started on this - will be slow but hopefully not too slow to get back to you
