### ISSUE TITLE
DocumentLSTMEmbeddings use GRU instead of LSTM

### ISSUE THREAD

**Issue by kubapok** [zalandoresearch/flair#511]
In DocumentLSTMEmbeddings there is:

`        self.rnn = torch.nn.GRU(self.embeddings_dimension, hidden_size, num_layers=rnn_layers,
                                bidirectional=self.bidirectional)`

which is inconsistent naming. Both GRU and LSTM are type of RNN networks, but GRU is not the same as LSTM.

**Comment by alanakbik** [comment]
fixed in #512 - thanks!!
