### ISSUE TITLE
Training one model with over 100 epochs, how to early stop? 

### ISSUE THREAD

**Issue by Huijun-Cui** [zalandoresearch/flair#515]
I hope I can stop the model training manually , but if I do this I can't see F1 score , how can I see the F1 score if I early stop the model?

**Comment by alanakbik** [comment]
Hi @Huijun-Cui what kind of model are you training, a sequence tagger or a language model? 

Generally, for manual stopping you can hit **ctrl+c** which will stop training, execute a final training run and then save the model. It should also display the final F1 score.

**Comment by alanakbik** [comment]
Closing this issue, but feel free to reopen if you have more questions!

**Comment by Akshayanti** [comment]
Is it possible to configure early stopping while using hyperparameter training?

**Comment by alanakbik** [comment]
Hello @Akshayanti yes you can set different parameters to configure this. For instance you can set a max_epoch in the ParamSelector class. You can also configure a patience and anneal factor as hyperparameters to set up early stopping. See more info [here](https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_8_MODEL_OPTIMIZATION.md#selecting-hyper-parameters).
