### ISSUE TITLE
Add support for Transformer-XL

### ISSUE THREAD

**Issue by stefan-it** [zalandoresearch/flair#522]
Thanks to `pytorch-pretrained-BERT`, we can add a new embeddings class for Transformer-XL embeddings (idea mainly taken from #68).

**Comment by alanakbik** [comment]
Awesome!

**Comment by stefan-it** [comment]
I'm not sure if the PR should land into the upcoming *0.4.1* release 🤔

Training is working :) Previous experiments I made resulted in a F-Score of 90 - 91 on CoNLL 2003 (English).

**Comment by alanakbik** [comment]
Hey wow that was fast :)

**Comment by alanakbik** [comment]
Training is also working on my end - I'm doing some example training runs. I'll merge into 0.4.1 branch in a bit once first numbers come in!

**Comment by stefan-it** [comment]
Transformer-XL embeddings can be used in [*0.4.1*](https://github.com/zalandoresearch/flair/releases/tag/v0.4.1) now, so I'm closing here :)
