### ISSUE TITLE
When running the calculate perplexity, got the error

### ISSUE THREAD

**Issue by jmlongriver** [zalandoresearch/flair#534]
Here is the error,  sounds likely it needs GPU, would you suggestion what I should I modify in the code of perplexity calculation?
File "/flair/models/language_model.py", line 69, in forward
    encoded = self.encoder(input)
  File ".local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File ".local/lib/python3.6/site-packages/torch/nn/modules/sparse.py", line 110, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File ".local/lib/python3.6/site-packages/torch/nn/functional.py", line 1110, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected object of type torch.cuda.LongTensor but found type torch.LongTensor for argument #3 'index'

**Comment by stefan-it** [comment]
Thanks for reporting it! I've found a fix for that + will open a PR soon :)

**Comment by stefan-it** [comment]
@jmlongriver I pushed a fix for that. Could you please try it out (see #536) - it should work now.

I tried it both on GPU and CPU. Perplexity is also the same :)

**Comment by alanakbik** [comment]
@jmlongriver thanks for reporting this, and @stefan-it thanks for fixing this! Caught just in time before the 0.4.1 release :)
