### ISSUE TITLE
Old 0.3.0 pytorch-pretrained-bert version in PyPI release for flair 0.4.0

### ISSUE THREAD

**Issue by knrd** [zalandoresearch/flair#535]
**Describe the bug**
On 0.4.0 tag in `requirements.txt` https://github.com/zalandoresearch/flair/blob/v0.4.0/requirements.txt there is `pytorch-pretrained-bert==0.4.0`, but in PyPI release in https://files.pythonhosted.org/packages/cc/6a/fea4f9533feea65f8b2ff3d6a9934dba6227df81bbc180915cbd30c5db95/flair-0.4.0.tar.gz in `flair-0.4.0/flair.egg-info/requires.txt` you can find `pytorch-pretrained-bert==0.3.0`.

**To reproduce**
`pip install flair` and `pip list`

After `pip install pytorch-pretrained-bert==0.4.0` pip will report:
> flair 0.4.0 has requirement pytorch-pretrained-bert==0.3.0, but you'll have pytorch-pretrained-bert 0.4.0 which is incompatible.

Should not be `pytorch-pretrained-bert==0.4.0` for PyPI release of flair 0.4.0?

**Comment by stefan-it** [comment]
Exactly :) 

This is fixed in the upcoming *0.4.1* release [branch](https://github.com/zalandoresearch/flair/tree/release-0.4.1) :)

**Comment by stefan-it** [comment]
*0.4.1* was released [today](https://github.com/zalandoresearch/flair/releases/tag/v0.4.1), so I'm closing here :)
