### ISSUE TITLE
Enhancement: NER Output not as string but nested dict

### ISSUE THREAD

**Issue by pwichmann** [zalandoresearch/flair#54]
It would be great if there was a way to obtain a nested dictionary as output of the NER instead of a string with <...> tags. The string is quite tedious to work with.

I imagine an output like:

```
"sentence": {
    "text": "Facebook, Inc. is a company, and Google is one as well.",
    "named_entities": [
        {
            "mention_text": "Facebook, Inc.",
            "start_pos": 0
            "end_pos": ...
            "type": "ORG",
            "confidence": 0.9
        },
        {
        ...
        }
    ]
} 
```

**Comment by pwichmann** [comment]
Thank you!

That does not solve the problem though.
It could be the case that words or word sequences are spelled the same but have different NER tags - depending on their context. That information is lost without the offset information which allows me to unambiguously identify the entity in the text.

I just had a similar problem with named entity mentions that contained other named entity mentions. It was a mess to process these without offset information. In fact, I just had to give up. :(

**Comment by tabergma** [comment]
in release-0.3

You need to call `sentence.to_dict(tag_type='ner')` to obtain the dictionary with the original sentence text, entities and labels.
