### ISSUE TITLE
Embeddings from OpenAI GPT models

### ISSUE THREAD

**Issue by stefan-it** [zalandoresearch/flair#547]
Hi,

this was partly discussed in #68.

I would really like to integrate embeddings from the two OpenAI GPT models. `pytorch-pretrained-BERT
`provides an excellent API for that.

One "challenging" problem would be, that GPT requires a BPE encoded input text.

I think we can use the `Sentence` class based tokenization, so we can rely on the `.tokens()` method.

Then for each token we need to call the GPT tokenization method, that returns subword(s).

Pseudocode:

```python
import torch
from pytorch_pretrained_bert import OpenAIGPTTokenizer, OpenAIGPTModel

from flair.data import Sentence

tokenizer = OpenAIGPTTokenizer.from_pretrained('openai-gpt')

model = OpenAIGPTModel.from_pretrained('openai-gpt')
model.eval()

sentence = Sentence("Who was Jim Henson? Jim Henson was a puppeteer", use_tokenizer=True)

tokens = [token.text for token in sentence]

for token in tokens:
    subwords = tokenizer.tokenize(token)

    indexed_tokens = tokenizer.convert_tokens_to_ids(subwords)

    tokens_tensor = torch.tensor([indexed_tokens])

    with torch.no_grad():
        hidden_states = model(tokens_tensor)

        print(hidden_states.shape)
```

Each token needs to have the same shape, so I think we can just use the first subword?

E.g. the token `puppeteer` is encoded to `['pupp', 'ete', 'er</w>']` after BPE. So the embedding for `pupp` will be used.

@alanakbik Do you think that this is a good strategy for the first attempt? Later we could try to use a mean over all subwords.

**Comment by alanakbik** [comment]
Hello @stefan-it yes I think that's a good strategy. You could check out the BytePairEmbeddings class where we do something similar. The BPE return a matrix of one vector for each subword, and then we take the first and last subwords to concatenate a word representation: 

https://github.com/zalandoresearch/flair/blob/1215d56c7921ca267e50e245e68dc55e45098b4f/flair/embeddings.py#L332 

This way, the prefix and suffix are always represented. If a word only has one subword, prefix and suffix are the same. 

But we never tested any other methods. Only embedding of first or last subwords, or a mean over all would be alternatives to test.

**Comment by stefan-it** [comment]
One model with using only the first subword is currently training (result is ~ 76%), so I'll definitely try your suggested approach that uses first and last subword :)

**Comment by stefan-it** [comment]
F-Score on CoNLL-2003 is 77.53% (with only using GPT embeddings of the first subword. Training for first and last subword is currently running :)

**Comment by stefan-it** [comment]
By using first and last subword a F-Score of 81.53% can be achieved :)

I'm trying to implement a method that uses the mean of all subword embeddings now.

**Comment by alanakbik** [comment]
Hey this is great - thanks for sharing this result!

**Comment by alanakbik** [comment]
Closing issue since it was added in a PR.
