### ISSUE TITLE
How to set the number of cores flair uses?

### ISSUE THREAD

**Issue by ixxie** [zalandoresearch/flair#561]
I noticed that when I run predictions with the sequence tagger, four out of eight cores on my machine are used. Is there a parameter that tells flair how many cores to use?

**Comment by alanakbik** [comment]
Currently, it is only possible to control the number of cpu cores for training language models, but not for prediction. We hope to add such a feature in the next version of Flair!

**Comment by ixxie** [comment]
Cool! And GPU cannot even in theory accelerate prediction right? Only training?

**Comment by alanakbik** [comment]
Depending on the model prediction should be much faster with GPU, especially if the model uses more recent embeddings such as Flair, ELMo or BERT.

**Comment by ixxie** [comment]
I noticed flair mentions the apex library in this context but it is unclear how to actually use it. Is it sufficient to have it installed and flair automatically picks it up and uses it? Is this documented anywhere?

**Comment by alanakbik** [comment]
The apex notification is from the underlying PyTorch framework. I believe it now uses apex whenever installed and outputs this message if not!

**Comment by ixxie** [comment]
Aha, thanks for the clarification!

**Comment by zeeshansayyed** [comment]
@alanakbik How can you specify the number of CPU cores for training language models? I wanted to run the training on a powerful CPU and compare it with the training on a GPU.

**Comment by alanakbik** [comment]
Hello @zeeshansayyed LM training is currently done on a single CPU / GPU. There is a `num_workers` argument that you can set for multi-CPU data preparation, but the default value of 2 is pretty much the only one that makes sense since this only affects data preparation. Still, if you want to increase this value, you can do it like this (not advised): 

```python
# train your language model
trainer = LanguageModelTrainer(language_model, corpus)
trainer.num_workers = 4
```

We have some multi-GPU in the works. See #733 for initial discussion on how to implement this. Perhaps something like this could also work for multi-CPU training.

**Comment by dabasmoti** [comment]
> Hello @zeeshansayyed LM training is currently done on a single CPU / GPU. There is a `num_workers` argument that you can set for multi-CPU data preparation, but the default value of 2 is pretty much the only one that makes sense since this only affects data preparation. Still, if you want to increase this value, you can do it like this (not advised):
> 
> ```python
> # train your language model
> trainer = LanguageModelTrainer(language_model, corpus)
> trainer.num_workers = 4
> ```
> 
> We have some multi-GPU in the works. See #733 for initial discussion on how to implement this. Perhaps something like this could also work for multi-CPU training.

Hi,
I am training with gpu but the data preparation takes long time,
Why it's not recommended to set multiplr cpu as you mention
`trainer.num_workers = #`
Thanks
