### ISSUE TITLE
Best models (when validating on dev) are not being saved

### ISSUE THREAD

**Issue by Borchmann** [zalandoresearch/flair#57]
When we are not in _train_with_dev_ mode, _scheduler.best_ stores the highest F1 (_dev_score_, not the _current_loss_).
https://github.com/zalandoresearch/flair/blob/3635220bdc05c19e4fe47555071db6c39c009bae/flair/trainers/sequence_tagger_trainer.py#L138

**Comment by alanakbik** [comment]
fixed by @mittalsuraj18 in #59
