### ISSUE TITLE
Tokenizer when using BERT?

### ISSUE THREAD

**Issue by waynedane** [zalandoresearch/flair#570]
Hi,  does flair use WordPiece tokenizer when using BERT embedding?

**Comment by stefan-it** [comment]
We use the `BertTokenizer` from `pytorch-pretrained-BERT` here:

https://github.com/zalandoresearch/flair/blob/master/flair/embeddings.py#L1099

**Comment by waynedane** [comment]
> We use the `BertTokenizer` from [`pytorch-pretrained-BERT`](https://github.com/huggingface/pytorch-pretrained-BERT) here:
> 
> https://github.com/zalandoresearch/flair/blob/master/flair/embeddings.py#L1099

thanks!
