### ISSUE TITLE
How to release a memory for word embeddings because it isn't released

### ISSUE THREAD

**Issue by avostryakov** [zalandoresearch/flair#574]
I used Stacked embeddings:
```self.stacked_embeddings = StackedEmbeddings([
            # WordEmbeddings('glove'),
            FlairEmbeddings('news-forward'),
            FlairEmbeddings('news-backward'),
        ])
```

for further training my own neural network. So, I get embeddings right in 'forward' method of my module:
```def forward(self, x):
        sentences = []
        for s in x:
            sentences.append(Sentence(s))
        self.stacked_embeddings.embed(sentences)

        x_emb = torch.zeros((len(x), self.stacked_embeddings.embedding_length, self.max_len),
                            dtype=torch.float32, device=self.device, requires_grad=False)
        for sid, s in enumerate(sentences):
            for tid, t in enumerate(s.tokens):
                x_emb[sid, :, tid] = t.embedding.data
        
        # my network code started here:
        x = self.convs0(x_emb)
        ...
```
It works but the problem is that memory is not released and in a minute a have out of memory from CUDA. Can you help with it?

**Comment by alanakbik** [comment]
Hi @avostryakov, CUDA out of memory can happen if you push too many sentences or too long sentences at the same time through the FlairEmbeddings. Could you try mini-batching to push only 32 sentences through at the same time?

**Comment by avostryakov** [comment]
Hi, @alanakbik! The problem is that from batch to batch occupied memory is increased. I can set batch size 8 and length 50. So, memory is not released somewhere after batch calculation was finished and the next batch is starting.

**Comment by alanakbik** [comment]
Hm that is strange. All embeddings are kept in regular memory by default, so this should not cause CUDA out of memory issues. You can delete embeddings from memory by calling this after each batch: 

```python
    for sentence in sentences:
        sentence.clear_embeddings()
```

Does this help?

**Comment by avostryakov** [comment]
@alanakbik Sorry for the delay. I understood that the problem not in FLAIR library but pytorch 1.0 itself. It doesn't release memory on GPU. I'll investigate the problem. I think something on my computer.

**Comment by alanakbik** [comment]
@avostryakov No worries - please let us know if you find the answer, it might help someone with the same issue!

**Comment by avostryakov** [comment]
I rolled back to pytorch 0.4.1 and flair started to work correctly. So, the
problem wasn't in flair but in pytorch 1.0. And I don't know why. Sorry for
insufficient information

Thank you!
Anatoly Vostryakov,
email to: a.vostrjakov@gmail.com

//////


ср, 13 мар. 2019 г. в 00:59, Alan Akbik <notifications@github.com>:

**Comment by alanakbik** [comment]
Great! Closing this issue but feel free to reopen if you have further questions!

**Comment by emrul** [comment]
For anyone else experiencing this, I faced the same problem (CUDA out of memory) and traced it to 2 separate problems:
1. Use latest nightly of pyTorch (which has a fix for this)
2. I also had a few long sentences (400-500 tokens) - I reduced my sentence size down to ~100

**Comment by jiteshm17** [comment]
I had faced the same problem while using PyTorch version 1.2.0. Upgrading to version 1.4 fixed the issue for me
