### ISSUE TITLE
Tutorial 8 code error

### ISSUE THREAD

**Issue by cy69855522** [zalandoresearch/flair#577]
tutorial 8

trainer: ModelTrainer = ModelTrainer(tagger, corpus,
                                     optimizer=Adam, weight_decay=1e-4)
↓ (Am I wrong? 0 0)
trainer: ModelTrainer = ModelTrainer(tagger, corpus,
                                     optimizer=Adam)
trainer.train(……, weight_decay=1e-4)

**Comment by alanakbik** [comment]
Sorry for the late reply! You are correct - just pushed a PR correcting this.
