### ISSUE TITLE
 Model name 'bert-base-chinese' was not found in model name list.

### ISSUE THREAD

**Issue by Das-Boot** [zalandoresearch/flair#594]
**Description**
When I use BertEmbeddings:

`from flair.embeddings import BertEmbeddings`
`embedding = BertEmbeddings('bert-base-chinese')`

I find that BertEmbeddings('bert-base-chinese') has an error:

> Model name 'bert-base-chinese' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese). We assumed 'https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-chinese.tar.gz' was a path or url but couldn't find any file associated to this path or url.

**Environment**
 - OS [Ubuntu 18.04.2]
 - Version [flair-0.4.1 Python-3.6.7]:

**Comment by alanakbik** [comment]
Hello @Das-Boot that is strange - it seems to be working when I run the command on my side. Which version of `pytorch-pretrained-bert` do you have installed?

**Comment by Das-Boot** [comment]
pytorch-pretrained-bert==0.6.1

**Comment by alanakbik** [comment]
Odd. And can you download the link 'https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-chinese.tar.gz' manually? If I click on the link, it immediately triggers a download for me.

**Comment by Das-Boot** [comment]
Thanks for your reply, I can download the link manually, but the speed is very slow, I think the problem is that the speed from my country is very slow to visit s3.amazonaws.com.
