### ISSUE TITLE
Compatibility issues in flair and Elmo embeddings

### ISSUE THREAD

**Issue by cherukuravi** [zalandoresearch/flair#597]
A clear and concise description of what you want to know.
Hi, I installed flair 0.4.1 and allennlp=0.5.1 with a pytorch version of 0.4.0.

When I call the function embedding = ELMoEmbeddings('original') it resulting the following error:

2019-03-06 10:05:05,372 ATTENTION! The library "allennlp" is not installed!
2019-03-06 10:05:05,373 To use ELMoEmbeddings, please first install with "pip install allennlp"
2019-03-06 10:05:05,373 ----------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-28-d1494a7fc15d> in <module>
----> 1 embedding = ELMoEmbeddings('original')

~/.local/lib64/python3.6/site-packages/flair/embeddings.py in __init__(self, model)
    358 
    359         # the default model for ELMo is the 'original' model, which is very large
--> 360         options_file = allennlp.commands.elmo.DEFAULT_OPTIONS_FILE
    361         weight_file = allennlp.commands.elmo.DEFAULT_WEIGHT_FILE
    362         # alternatively, a small, medium or portuguese model can be selected by passing the appropriate mode name

UnboundLocalError: local variable 'allennlp' referenced before assignment

Can you please suggest a solution for this?

**Comment by alanakbik** [comment]
Hello @cherukuravi it could be that your versions are too old. Could you try installing a newer version of allennlp (they are now at 0.8.2, but if that does not work you could try 0.8 or 0.7) and a newer version of PyTorch (now at 1.0)?

**Comment by cherukuravi** [comment]
@alanakbik. Thanks a lot. It worked.

Is there a way to tried ELMoEmbeddings for a large sentence which is of length ~30,000 as I am running into CUDA out of memory issue when I am using Flair ELMO Embeddings with such sentence.

**Comment by alanakbik** [comment]
Great! That's a good question - for our `FlairEmbeddings` we implemented a mechanism in which long sentences get chopped into smaller segments that are pushed through the RNN while always remembering the last hidden state. 

For ELMo embeddings, I think they would need to implement a similar mechanism to make it scale to larger sentences. It could also be that they already implement an approach for scaling to longer sentences. Perhaps you could ask in the `allennlp` github? 

Alternatively, you could split the document into sentences yourself and put each sentence individually through the ELMoEmbeddings. The word embeddings you get this way will be nearly the same as when you put the whole 30.000 word document through at the same time.

**Comment by alanakbik** [comment]
Closing for now, but feel free to reopen if you have more questions!

**Comment by Alea4jacta6est** [comment]
Hello! I have the same bug trying to use ELMoEmbeddings, I guess the reason might be in the new release of allennlp library, am i right?
```UnboundLocalError: local variable 'allennlp' referenced before assignment```
