### ISSUE TITLE
Is the Flair available to use the BERT for NER?

### ISSUE THREAD

**Issue by aslicedbread** [zalandoresearch/flair#598]
I mean that we only use the BERT+Softmax for NER. In other words, we don't use bilstm+crf.
Hope to get your reply, Thanks.

**Comment by alanakbik** [comment]
Hi @aslicedbread you can turn off the CRF by setting `use_crf=False` and turn off the biLSTM by setting `use_rnn=False` in the SequenceTagger, like this: 

```python
tagger: SequenceTagger = SequenceTagger(hidden_size=256,
                                        embeddings=embeddings,
                                        tag_dictionary=tag_dictionary,
                                        tag_type=tag_type,
                                        use_crf=False,
                                        use_rnn=False)
```

**Comment by aslicedbread** [comment]
> Hi @aslicedbread you can turn off the CRF by setting `use_crf=False` and turn off the biLSTM by setting `use_rnn=False` in the SequenceTagger, like this:
> 
> ```python
> tagger: SequenceTagger = SequenceTagger(hidden_size=256,
>                                         embeddings=embeddings,
>                                         tag_dictionary=tag_dictionary,
>                                         tag_type=tag_type,
>                                         use_crf=False,
>                                         use_rnn=False)
> ```

@alanakbik 
get、Thanks.

**Comment by gccome** [comment]
Hi @alanakbik , if we turn off `crf` and `rnn`, and only use BERT embedding, does it mean we are fine tuning BERT? Is the BERT embedding trainable in this case?

**Comment by alanakbik** [comment]
Hi @gccome unfortunately no, turning off the crf and rnn does not impact whether embeddings get fine tuned or not. In all cases currently the weights of the BERT embedding remain frozen.

**Comment by gccome** [comment]
@alanakbik Got it. Thanks! Hopefully we can have this feature in 0.5!

**Comment by alanakbik** [comment]
Yes, we'll look at adding this :)

**Comment by gccome** [comment]
@alanakbik wow great! Look forward to it!
