### ISSUE TITLE
Shape of document pool embedding changed between 0.4.0 and 0.4.1

### ISSUE THREAD

**Issue by davechallis** [zalandoresearch/flair#599]
The pooled embedding shape for a sentence changed between 0.4.0 and 0.4.1 of flair, though it's not clear if this was intentional or not.

For a document pool embedding with a single model, a 2D array was returned in 0.4.0, whereas a 1D array is returned in 0.4.1.

Sample code:

    import flair
    from flair.embeddings import FlairEmbeddings, DocumentPoolEmbeddings, Sentence
    
    flair_embedding_forward = FlairEmbeddings('news-forward-fast')
    doc_pool_embeddings = DocumentPoolEmbeddings([flair_embedding_forward])
    sent = Sentence('The quick brown fox.')
    doc_pool_embeddings.embed(sent)
    print(sent.get_embedding().shape)

In flair 0.4.0 this prints:

    torch.Size([1, 1024])

In flair 0.4.1 this prints:

    torch.Size([1024])

**Comment by alanakbik** [comment]
Hello @davechallis this is related to issue #367 - we generally want all embeddings to be simple vectors. Earlier versions had some inconsistencies here, but the shape of document embeddings has been corrected for version 0.4.1.

**Comment by davechallis** [comment]
@alanakbik ah, great, that sounds like a sensible change. I'll change code at my end to use the new embedding shape.
