### ISSUE TITLE
Question about corpus

### ISSUE THREAD

**Issue by jmlongriver12** [zalandoresearch/flair#602]
is there any downloadable train.txt, test.txt for IMDB set or other set for text classification, I followed the guideline to download IMDB dataset, but sounds likely no guideline for converting it to the format in the Flair, thanks!

**Comment by alanakbik** [comment]
Hello @jmlongriver12 in the current version of Flair, the IMDB dataset gets downloaded automatically the first time you call the data loader (`corpus = NLPTaskDataFetcher.load_corpus(NLPTask.IMDB)`. The corpus gets converted and placed into the folder `.flair/datasets/imdb` in your home folder.

If you're interested in how we do the conversion of this dataset, check out the code in the data_fetcher.py, specifically the code starting at this line: 
https://github.com/zalandoresearch/flair/blob/ccb2ffb4080550d25e1e067e2e82e661c8b81411/flair/data_fetcher.py#L578

Hope this helps!

**Comment by jmlongriver** [comment]
Thanks for your answer!

**Comment by alanakbik** [comment]
Closing for now, but feel free to reopen if you have more questions!
