### ISSUE TITLE
Visualisation routines

### ISSUE THREAD

**Issue by blythed** [zalandoresearch/flair#61]
We need some routines to do visualisation.
Implement these in ```flair.visual```

Useful features:

- tSNE maps of embedding features
- ...

**Comment by alanakbik** [comment]
Good idea! Other visualization that might be interesting:

- visualization of weight traces during training
- visualization of states in character LM akin to Radfort et al. 2017

**Comment by blythed** [comment]
This is a screenshot of the added feature (hovering mouse gives context):

![screen shot 2018-08-13 at 15 43 44](https://user-images.githubusercontent.com/15139331/44035313-7d6d2ec6-9f0f-11e8-869f-e9b345e560f8.png)

**Comment by blythed** [comment]
Added this, but the results don't look anything like Radford et al. (2017)
![screen shot 2018-08-13 at 16 43 23](https://user-images.githubusercontent.com/15139331/44038756-ca89e0ca-9f17-11e8-9e9d-bc1766dc70c2.png)

**Comment by stefan-it** [comment]
I'm currently using the latest `release-0.3`  branch and I just want to mention, that `sklearn` needs also to be added to the requirements file :)
