### ISSUE TITLE
multiple features as text input 

### ISSUE THREAD

**Issue by vijaysagi** [zalandoresearch/flair#613]
Hi

We have CSV file with 120 columns and 1 million records In which i have 1 label column and remaining are text fields. the text fields can empty in some cases. The label column is 0 or 1

The trained engine should  infer the input (from csv) and the output shud be 0 or 1.

Could u please suggest me how can we use flair package for above requirement

Thnks

vijay

**Comment by alanakbik** [comment]
Hi @vijaysagi does this mean you want to make a prediction of 0 or 1 based on the remaining 120 columns? 

Right now, Flair is built to derive a classification for a single paragraph of text. So you would need to create a single text paragraph for each row that encodes your 120 columns, for instance by always using the column title followed by the column text. Then, I would recommend using the DocumentRNNEmbeddings over this data to train the classifier. Hope this clarifies!

**Comment by vijaysagi** [comment]
got it thank u
