### ISSUE TITLE
SRL task

### ISSUE THREAD

**Issue by Huijun-Cui** [zalandoresearch/flair#631]
HI , when I read source code , I notice that your model seems to be able to deal with semantic labeling task ,I am not sure , so asking your is it true?

**Comment by alanakbik** [comment]
Hi @Huijun-Cui we currently have a pre-trained model for the frame detection and disambiguation part of SRL. Some documenation on how to use it is [here](https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_2_TAGGING.md#experimental-semantic-frame-detection). It will identify frame-evoking words and disambiguate them.

However, we do not yet implement a method for detecting the roles of each frame. I hope to do this at some point in the future, but this is not currently planned.

**Comment by Huijun-Cui** [comment]
thank you , in my opinion , your model can deal with  SRL task , because NER and SRL are quite similar .
