### ISSUE TITLE
Question about F1

### ISSUE THREAD

**Issue by Huijun-Cui** [zalandoresearch/flair#638]
Hi , I account some trouble with F1
In my opinion the number of TP + FN  ==  the number of the whole tag . But I notice that it not always equal .  I read your code , but still I cant`t know why this happened , do you know why ? Hope you can respond to me , thank you

**Comment by alanakbik** [comment]
Hello @Huijun-Cui we are planning to refactor the evaluation part so hopefully we can address this issue. Could you provide a bit more information on the error you encounter so we can reproduce it?

**Comment by Huijun-Cui** [comment]
@alanakbik  sorry , I made mistake , you code is good ,  👍

**Comment by alanakbik** [comment]
Ah great :) I'll close the issue but feel free to reopen if you have more questions/comments!
