### ISSUE TITLE
Did you implement the orthonormal initializing ? 

### ISSUE THREAD

**Issue by Huijun-Cui** [zalandoresearch/flair#639]
In recent paper I notice that initialize Bi-LSTM with orthonormal matrices can improve the performance , so have you implemented it in flair?

**Comment by alanakbik** [comment]
Sounds interesting - could you point us to the paper? Unless this is default in PyTorch RNNs we did not implement this. If you're interested in adding this to Flair, we'd always appreciate a pull request :)

**Comment by Huijun-Cui** [comment]
Deep Semantic Role Labeling : What Works and What`s Next  .   I have implemented in my understanding , just few line of code .  Like this 

            for p in self.rnn.parameters():
                if len(p.size()) >= 2:
                    torch.nn.init.orthogonal_(p)


Do you thinks this is right ?

**Comment by Huijun-Cui** [comment]
Yeah  , tomorrow morning I will you if make difference in performance ,  the experiment is running on

**Comment by Huijun-Cui** [comment]
orthogonal initialization didn`t make significant improvement , I still cant`t tell if it work

**Comment by alanakbik** [comment]
Closing for now, but feel free to reopen if you have more comments or questions!
