### ISSUE TITLE
Specify path for model?

### ISSUE THREAD

**Issue by DarkBlaez** [zalandoresearch/flair#653]
The default is to cache models in <userhome>.flair/models   how can I specify the path where I want these cached?

Thanks
DB

**Comment by stefan-it** [comment]
Hi @DarkBlaez,

at the moment, the cache model path is hard-coded and not configurable. But there's an already opened (and pending) issue (see #507) that also requested a configurable cache model path :)

**Comment by alanakbik** [comment]
Hi @DarkBlaez, 

we just pushed a PR to address this into master. You can now specify the base cache directory, i.e. the directory to where all models/embeddings/datasets get downloaded. It defaults to .flair in your home folder, but you can override this by calling

```python
import flair
flair.cache_root = 'my/cache/directory'
```
before calling your code. Let us know if this works for you!
