### ISSUE TITLE
Can we get embedding from different layers of loaded BERT model ?

### ISSUE THREAD

**Issue by search4mahesh** [zalandoresearch/flair#656]
Hi,

Is it possible to get embedding from different layers of loaded BERT model in flair?
Like is it possible to get embedding of second last layer.

Thanks
Mahesh

**Comment by SudalaiRajkumar** [comment]
Yes, it is possible. Please check this one
https://github.com/zalandoresearch/flair/issues/334

**Comment by stefan-it** [comment]
@search4mahesh Just use the `layers` argument to pass your desired layers for BERT embeddings:

https://github.com/zalandoresearch/flair/blob/master/flair/embeddings.py#L1122

It is definitely worth to try out different layers, see e.g. [this post](https://github.com/zalandoresearch/flair/issues/308#issuecomment-452360187) with per-layer analysis for PoS tagging.
