### ISSUE TITLE
Faster speed by splitting text for entity extraction

### ISSUE THREAD

**Issue by timnon** [zalandoresearch/flair#657]
I experienced a huge (10x) speed-up by splitting a text into sentences and then running entity extraction on each sentence separately in one batch run. The quality looked quite similar, but i am sure there are cases where running the whole text is better.

So the question: Is there some heuristic experience when it makes sense to split a text in sentences? I expected the speed improvement to stall when the number of text chunks hits the number of cores, but nothing like this happened.

This might be helpful to know, since running entity extraction on large texts without a GPU is quite slow.

**Comment by alanakbik** [comment]
Hello @timnon generally, it makes sense to split text into sentences for all problems in which we expect most relevant information to detect tags to be contained within a sentence. This includes pretty much all sequence labeling problems in Flair, which we train at the sentence level anyway. So the output of the tagger should be nearly identical and may even be better if you pass your text as sentences.

**Comment by timnon** [comment]
Thanks for the reply! Just though it might be useful to mention this somewhere prominently. Most people will probably push a complete text into the entity extraction, expecting that it doesnt make much a difference speedwise.

**Comment by alanakbik** [comment]
Good point! Will add to the docs!
