### ISSUE TITLE
No module named 'flair.embeddings'; 'flair' is not a package

### ISSUE THREAD

**Issue by sahand91** [zalandoresearch/flair#658]
I've just installed flair and getting this error when writing "from flair.embeddings import WordEmbeddings". I'm using anaconda 3.7 flair 0.4.1 and pytorch 1.0.1 version

**Comment by alanakbik** [comment]
Hello @sahand91 did you install in a virtual environment - if so, are you executing the code from this environment?

**Comment by alanakbik** [comment]
Closing for now, but feel free to reopen if you have more questions!

**Comment by ramreddymettu** [comment]
In [2]: import flair                                                                                                                                                                                          
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-e42b806689dc> in <module>
----> 1 import flair

~/Ram_data/flair/flair.py in <module>
      4 
      5 ## Flair Imports,
----> 6 from flair.data import Corpus
      7 from flair.datasets import ClassificationCorpus
      8 from flair.training_utils import EvaluationMetric

ModuleNotFoundError: No module named 'flair.data'; 'flair' is not a package

I'm facing the same issue.

**Comment by stefan-it** [comment]
Hi @ramreddymettu, did you install `flair` via pip, or did you install it from source (via `pip install -e .`)? Do you use a virtual environment btw 🤔

**Comment by jinlukang1** [comment]
Getting the same error when trying to execute a python script.

**Comment by jinlukang1** [comment]
I find my file name is flair.py.
Renaming helped me solve this problem.

**Comment by suvarnsingbhable** [comment]
ModuleNotFoundError: No module named 'flair'

**Comment by RohanSaxena14** [comment]
The problem was that I named my python file "flair.py" just like @jinlukang1, renaming it solved the issue :)

**Comment by MahmoudAliEng** [comment]
Me too same problem "File name == 'flair.py' ", changing it fixes the issue. This issue should be closed I think @alanakbik  ?

**Comment by alanakbik** [comment]
Hello @dansvotrecoeur the NLPTaskDataFetcher has long been deprecated. You should do

```python
import flair.datasets
corpus = flair.datasets.UD_INDONESIAN()
```

Check out this tutorial on how to load a corpus [here](https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_6_CORPUS.md#tutorial-6-loading-training-data).

**Comment by dansvotrecoeur** [comment]
Hi @alanakbik thank you for your help, it's worked for me. I want to ask you anymore, I've trained the corpus data for 'upos' label dictionary from UD_INDONESIAN() and did the pos-tag from my own doc/text. Could I use that output to use NER on spaCy? thank you.
