### ISSUE TITLE
Issue training word LM with ~30 million unique tokens

### ISSUE THREAD

**Issue by collinpu** [zalandoresearch/flair#660]
Hi, I am training a LM on word tokens and I am running into memory issues. My dictionary consists of ~30 million tokens and when your LM model executes self.decoder=nn.Linear(hidden_size, len(dictionary)) it tries to allocate ~115GB for a 1024 dimension hidden state. If I decrease the size of the hidden state to something smaller, like 200, the model will be able to allocate enough space in ram for self.decoder but will then fail to allocate enough space on my GPU. I'm wondering if there is a workaround for this that doesn't require me to subsample my dictionary or use small hidden states. 
My specs: 
Ubuntu 18.04
64 GB ram
RTX 2080 Ti 
![Screenshot from 2019-04-12 12-31-46](https://user-images.githubusercontent.com/35547241/56062169-6a950b00-5d20-11e9-8350-0bd849d8ec38.png)
![Screenshot from 2019-04-12 12-32-46](https://user-images.githubusercontent.com/35547241/56062178-6e289200-5d20-11e9-9db2-0a3404e526bf.png)

**Comment by stefan-it** [comment]
I would say the vocabulary size is way too huge. E.g. the original ELMo model uses 793,471 tokens as vocabulary. BERT and sciBERT both use a vocabulary of 30K subtokens.

I think you should run several experiments with different vocab sizes to check the performance on downstream tasks :)

Is there any particular reason why you want to train a word-based language model 🤔

**Comment by collinpu** [comment]
Wow, I never realized how small the vocabulary sizes were for those other models. I’ll try to downsample then. 

I’m training LM’s on the full patent corpus and the character LMs I’ve trained seem to struggle differentiating between the many disprite semantic contexts inherent in the data. I was hoping that word embeddings would better capture these differences because of its more explicit vocabulary. What do you think?

**Comment by alanakbik** [comment]
Hello @collinpu - word level representations could well be very useful. Generally we find best results by combining the character LMs with classic word-level embeddings using an [embedding stack](https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_4_ELMO_BERT_FLAIR_EMBEDDING.md#recommended-flair-usage). One resource-effective way for you might be to train character-level language models and additionally train standard word embeddings (such as FastText or Glove) over your corpus. I would probably try this first.

Other options as @stefan-it wrote include subsampling your dictionary to the most common words or using subtokens like BERT for your word-level LM. 

Depending on your domain, either of these approaches might work best. Should you try some of these methods, we'd be interested to hear how well they work for you and how they compare!

**Comment by alanakbik** [comment]
Closing for now, but feel free to reopen if you have more questions!
