### ISSUE TITLE
Language model trainer - test and validation data too big

### ISSUE THREAD

**Issue by TDaudert** [zalandoresearch/flair#668]
The language model trainer currently requires the following folder tree:

corpus/
corpus/train/
corpus/train/train_split_1
corpus/train/train_split_2
corpus/train/...
corpus/train/train_split_X
corpus/test.txt
corpus/valid.txt

However, I'm facing trouble with the size of the input data. 
With 6.6GB of test+validation data, I receive an out of RAM error requiring 26 GB; with 4.1 GB data, 15 GB RAM are required. 
I tested different nlayer sizes, hidden_sizes and mini_batch_sizes, however, the change in required RAM is marginal.

**Describe the solution you'd like**
1) one folder each for splits of the test, and validation data, similar to the "train" folder.
2) The ability to specify an eval_mini_batch_size similar to #289

**Comment by alanakbik** [comment]
Hello @TDaudert I think we can add this. The test data should probably only be loaded at the end since it is only used then. Small question: Is it really necessary to validate on so much data? Even 100 MB of text is a lot and will probably give you a very reliable estimate of perplexity during training.

**Comment by stefan-it** [comment]
I would say that the validation and test data is way too large 😱 compared to other language modeling tasks like 1 Billion word benchmark or Wiki-103.

**Comment by TDaudert** [comment]
Yes, I'm able to run it with fewer data. So it's more about how much data I have in total, the 1% might already be too much. Thank you!

**Comment by alanakbik** [comment]
Ok, then I'll close for now, but we'll keep this in mind as we refactor the data loaders - I think offering multi-file test and validation data is a useful feature to have in any case.
