### ISSUE TITLE
'UnicodeDecodeError' when using functions defined in data_fetcher.py 

### ISSUE THREAD

**Issue by iamyihwa** [zalandoresearch/flair#67]
Hello 

I was following steps given in the documentations in [here](https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_BASICS.md).

**Situation:** 
I am trying to train a Spanish NER. The data I am using to train is similar is a CONLL format. 
The error happened when I was testing a few options to load the input files. 
I have installed flair through git clone and installed from master branch. 
I first wanted to install via pip install however I wanted to train my own embedding and according to [this ](https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_TRAINING_LM_EMBEDDINGS.md) it seems a feature available only through the git clone not from pip install. 

**When the error occurred:** 
When I ran the function to load the file 
```data = NLPTaskDataFetcher.read_conll_sequence_labeling_data('./data/esp2.train')```
I got an error that said:  
```UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 291: ordinal not in range(128)```

**Screenshot of the error** 
![image](https://user-images.githubusercontent.com/12494156/44082776-7dcb6060-9fb2-11e8-8c4d-59183d402b5e.png)

**What  I tried:** 
I have tried (1) different functions implemented in the file data_fetcher. (2) also gave option of encoding to 'utf-8' in  ```open(path_to_conll_file, encoding='utf-8')``` , but didn't solve the issue. 

I have also tried a couple of options to change system encoding but not so successful.

**Comment by alanakbik** [comment]
Hello Yihwa, 

thanks for your interest! the error looks like some strange encoding problem. Could you share the data (or post a few sentences from it here) so we can try to reproduce the error?

**Comment by iamyihwa** [comment]
Sure! 

It is attached. 
It is Spanish words with NER encoding. (from CONLL 2002)
[esp.txt](https://github.com/zalandoresearch/flair/files/2286324/esp.txt)

**Comment by alanakbik** [comment]
Hello Yihwa, 

I cannot reproduce the error. Could you do a `git pull` to get the latest code in the master branch (we just refactored the `NLPTaskDataFetcher`) and do the following: 

```python
from flair.data_fetcher import NLPTaskDataFetcher

sentences = NLPTaskDataFetcher.read_column_data('/path/to/esp.txt', column_name_map={0: 'text', 3: 'ner'})

for sentence in sentences:
    print(sentence.to_tagged_string())
```
Does this also throw the errors? What operating system do you use?

**Comment by iamyihwa** [comment]
I did! 
Get the same error. 
I am using ubuntu. 

![image](https://user-images.githubusercontent.com/12494156/44087614-ade04140-9fc0-11e8-82dc-ccc0b6fa9830.png)


![image](https://user-images.githubusercontent.com/12494156/44087598-a40385ce-9fc0-11e8-9651-808e4cb07603.png)

**Comment by stefan-it** [comment]
What is the output of `locale` on your commandline?

**Comment by stefan-it** [comment]
I could reproduce the error with Anaconda:

```bash
$ export LANG=C
$ python esp.py
Traceback (most recent call last):
  File "esp.py", line 3, in <module>
    sentences = NLPTaskDataFetcher.read_column_data('/home/stefan/Downloads/esp.txt', column_name_map={0: 'text', 3: 'ner'})
  File "/home/stefan/Repositories/github.com/flair/flair/data_fetcher.py", line 229, in read_column_data
    lines: List[str] = open(path_to_column_file).read().strip().split('\n')
  File "/tmp/anaconda3/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 291: ordinal not in range(128)
```
So you have to make sure that you're using an utf-8 capable locale, like `C.UTF-8` or `es_ES.UTF-8` :)

**Comment by iamyihwa** [comment]
The system does have UTF-8 encoding 
![image](https://user-images.githubusercontent.com/12494156/44089955-e01a5120-9fc8-11e8-9748-dfeba8228fc1.png)
 
However anaconda does not seem to use that ... 
![image](https://user-images.githubusercontent.com/12494156/44090144-73f98b9a-9fc9-11e8-8d6d-c516d2545247.png)

I did a few attempts to change system encoding ... 
![image](https://user-images.githubusercontent.com/12494156/44090402-53a1d4f0-9fca-11e8-9a20-77935b4021db.png)

However even after that i get the same error .. 

![image](https://user-images.githubusercontent.com/12494156/44090420-60d6881e-9fca-11e8-8c60-8081574d98dd.png)


I tried on the mac, and the error doesn't seem to appear...

**Comment by iamyihwa** [comment]
adding  , encoding='utf-8'  and reloading solved the problem. 

This morning did not.. but now it works by adding  encoding = 'utf-8' to all the open functions, 
and also restarting the jupyter notebook kernel after the change ..

**Comment by manibt1992** [comment]
I faced "utf-8' codec can't decode byte 0xa0" error when initiate the flair retraining

Then I open the input file in notepad and did the save as with "UTF-8" option. Then I rerun the script, it works for me
