### ISSUE TITLE
labels of Text Classification

### ISSUE THREAD

**Issue by amitbcp** [zalandoresearch/flair#684]
For text classification, the format is follows -
__label__<label1> <text>

As per my understanding, the text/document is converted to it's word embedding format . But what about the categorical labels ? i.e. are the labels converted to a vector representation using the word embedding or assigned numbers or hot-encoded or something similar ?

The concern being, it can be possible that the label might not be a part of the corpus over which the word embedding was trained.

**Comment by gwohlgen** [comment]
(in my understanding as a user of the lib) labels are clearly separated from the document words by a "__label__" prefix.
For exampe:
__label__positive The movie was great! 

Does that answer the question?

**Comment by amitbcp** [comment]
@gwohlgen  the question that I want to figure out is, with __label__positive, how is the word "positive" used internally ?
Does the word "positive" is converted to it's vector representation using the word embedding or it is categorically encoded ?

**Comment by alanakbik** [comment]
Hello @amitbcp labels are one-hot encoded using the `Dictionary` class. This is wholly separate from encodings used by the different word embeddings.

**Comment by amitbcp** [comment]
Thanks @alanakbik . I just wanted to confirm the encoding as one-hot encoded should work for  us. Thanks for the response. I am closing the question as well.

**Comment by ychong** [comment]
> Hello @amitbcp labels are one-hot encoded using the `Dictionary` class. This is wholly separate from encodings used by the different word embeddings.

Hi @alanakbik thanks for the reply. Do you mind pointing to which portion of the code that contains this one-hot encoding label transformation? May I ask why use Dictionary class when one can use OneHotEncoder from sklearn?
