### ISSUE TITLE
'multi-forward-fast' - what does fast stand for?

### ISSUE THREAD

**Issue by Janinanu** [zalandoresearch/flair#688]
In the list of possible string arguments to pass to the FlairEmbeddings class ([https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_4_ELMO_BERT_FLAIR_EMBEDDING.md](url)), what does the 'fast' in 'multi-forward-fast' or 'multi-backward-fast' imply? Were they trained from fasttext embeddings...? Are they somehow intended to make computations faster...?

**Comment by stefan-it** [comment]
Hi @Janinanu, `-fast` indicates, that the model size of these embeddings are smaller compared to the "normal" models' :) Training will be faster, but a smaller model size has impact on the downstream task, see e.g. [this](https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_2_TAGGING.md) comparison here.

**Comment by Janinanu** [comment]
hi @stefan-it , got it, thank you very much!

**Comment by Janinanu** [comment]
On a similar note: Does Flair provide any options to choose smaller embedding sizes? Even the "fast" embeddings have a dimension of 1024, which makes everything super slow.

**Comment by Janinanu** [comment]
According to this [https://github.com/zalandoresearch/flair/issues/111](url) , the answer to my question is probably no ;)
