### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified when subprocess.Popen

### ISSUE THREAD

**Issue by sharathyadav1993** [zalandoresearch/flair#698]
When we run the below lines of code to extract the frames from a video, then it is showing file not found error. But the video file is present in the location given.

**The function call is given below**

def extract_frames(video_file, num_frames):
    """Return a list of PIL image frames uniformly sampled from an mp4 video."""
    try:
        os.makedirs(os.path.join(os.getcwd(), 'frames'))
    except OSError:
        pass
    print(video_file)
    output = subprocess.Popen(['ffmpeg', '-i', video_file],stderr=subprocess.PIPE).communicate()
    # Search and parse 'Duration: 00:05:24.13,' from ffmpeg stderr.
    re_duration = re.compile(r'Duration: (.*?)\.')
    duration = re_duration.search(str(output[1])).groups()[0]

    seconds = functools.reduce(lambda x, y: x * 60 + y,
                               map(int, duration.split(':')))
    rate = num_frames / float(seconds)

    output = subprocess.Popen(['ffmpeg', '-i', video_file,
                               '-vf', 'fps={}'.format(rate),
                               '-vframes', str(num_frames),
                               '-loglevel', 'panic',
                               'frames/%d.jpg']).communicate()
    frame_paths = sorted([os.path.join('frames', frame)
                          for frame in os.listdir('frames')])
    frames = load_frames(frame_paths, num_frames=num_frames)
    subprocess.call(['rm', '-rf', 'frames'])
    return frames

**Errors are shown below**

C:/Users/SHemantharaj/Desktop/Cybersecurity/moments_models-master/video.mp4
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
~\Desktop\Cybersecurity\moments_models-master\test_video.py in <module>()
     59 else:
     60     print('Extracting frames using ffmpeg...')
---> 61     frames = extract_frames(args.video_file, args.num_segments)
     62 
     63 

~\Desktop\Cybersecurity\moments_models-master\utils.py in extract_frames(video_file, num_frames)
     17         pass
     18     print(video_file)
---> 19     output = subprocess.Popen(['ffmpeg', '-i', video_file],stderr=subprocess.PIPE,shell=True).communicate()
     20     # Search and parse 'Duration: 00:05:24.13,' from ffmpeg stderr.
     21     re_duration = re.compile(r'Duration: (.*?)\.')

~\AppData\Local\Continuum\anaconda3_old_version_Final\lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors)
    707                                 c2pread, c2pwrite,
    708                                 errread, errwrite,
--> 709                                 restore_signals, start_new_session)
    710         except:
    711             # Cleanup if the child failed starting.

~\AppData\Local\Continuum\anaconda3_old_version_Final\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_start_new_session)
    995                                          env,
    996                                          os.fspath(cwd) if cwd is not None else None,
--> 997                                          startupinfo)
    998             finally:
    999                 # Child is launched. Close the parent's copy of those pipe

FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by UweR70** [comment]
Have the same error. What was the solution?
