### ISSUE TITLE
tagger.predict() is very slow

### ISSUE THREAD

**Issue by juggernauts** [zalandoresearch/flair#7]
Compared to other deep learning based NER models, tagger.predict() appears to be slow. It took around 70 seconds to parse a string with 455 tokens. 

Upon running line profiler, it seems all the time is spent in creating the embeddings

`self.embeddings.embed(sentences)`

Any ideas why this would be so slow?

**Comment by alanakbik** [comment]
The latest commit now includes automatic batching for parsing lists of sentences. Can you split your text into a list of sentences and try again?

**Comment by juggernauts** [comment]
You were right, I was passing the complete text without splitting it into sentences. With your latest commit, I was able to bring down the time to 18 seconds so I guess it did work.
Here's my latest code

`from flair.data import Sentence
from flair.tagging_model import SequenceTagger
import nltk
sent_tokens = nltk.sent_tokenize("My long text of 455 words")
sentence = [Sentence(i) for i in sent_tokens]
tagger = SequenceTagger.load('ner')
tagger.predict(sentence)`

**Comment by alanakbik** [comment]
Ok, that's great! Thanks for raising the issue and posting the code! we also expect upcoming releases to further improve on tagging speed - we'll keep you posted!

**Comment by alanakbik** [comment]
For full text classification you should not use sentence splitting, i.e. each tweet (or text paragraph you wish to classify) should get its own `Sentence` object. Since tweets are not long it should be OK, runtime-wise.

**Comment by alanakbik** [comment]
Hi @jewl123 yes that seems very slow. You are using a non-GPU setup, correct?

You can try to use mini-batching to speed things up - for instance you could pass a lists of 4, 8, 16 or 32 tweets at the same time, like this: 

```python
classifier = TextClassifier.load('en-sentiment')

# make mini-batch of sentences
sentences = [
    Sentence('I love this movie'),
    Sentence('I hate this movie'),
    Sentence('This movie is great'),
]

# pass mini-batch
classifier.predict(sentences)

for sentence in sentences:
    print(sentence)
```

**Comment by jewl123** [comment]
Ahhhh I just realized that I had the "TextClassifier.load_from_file" call inside of my for loop!
Moving it outside helped tremendously.

I will also try with mini-batches soon to see if it optimizes prediction time and report back.

Hope this helps someone later on
