### ISSUE TITLE
Adding pre-trained classification models

### ISSUE THREAD

**Issue by tabergma** [zalandoresearch/flair#70]
Add pre-trained classification models for 
- AGNews and
- IMDB

The models should be loadable by calling `TextClassifier.load('ag-news')` and `TextClassifier.load('imdb')`

**Comment by stefan-it** [comment]
@tabergma What parameters did you use for training on IMDB? I'm constantly running out of CUDA error with:

```bash
document_embeddings: DocumentLSTMEmbeddings = DocumentLSTMEmbeddings(word_embeddings, hidden_states=512)
```

And

```
trainer.train('resources/imdb/results',
              learning_rate=0.1,
              mini_batch_size=8,
              max_epochs=150)
```

**Comment by ducalpha** [comment]
I have just upgraded from release 0.2.0 to 0.3.2 and now cannot train my dataset because the GPU memory runs out even I reduce the mini_batch_size to 1 and use only Glove word embeddings.

**Comment by alanakbik** [comment]
Strange - could you give more details on how you train? Which dataset, which training method etc?

**Comment by tabergma** [comment]
The next release will have pre-trained models for IMDB (micro f-score 0.9054) and GermEval2018 Task 1 (macro f-score 0.7571). We are going to create separate issue for any new model we are going to add.
