### ISSUE TITLE
Confidence Score as a variable

### ISSUE THREAD

**Issue by amitbcp** [zalandoresearch/flair#715]
**Is your feature/enhancement request related to a problem? Please describe.**
 Yes. For multi-label text classification, only those labels are added whose confidence score is  > 0.5 
This is hard-coded and does not provide user any option to play around the score based on their specific use cases.
File - https://github.com/zalandoresearch/flair/blob/master/flair/models/text_classification_model.py

Line - 290

**Describe the solution you'd like**
conf should be a an parameter to the predict function.

![conf](https://user-images.githubusercontent.com/13197403/57280658-d4f25e80-70c6-11e9-88a0-c54a31399607.png)

**Comment by stefan-it** [comment]
I think this is addressed in https://github.com/zalandoresearch/flair/pull/707 :) So it should be included in an upcoming release!
