### ISSUE TITLE
BytePairEmbeddings of dim n returns embedding of size 2n

### ISSUE THREAD

**Issue by san7988** [zalandoresearch/flair#724]
I am trying to use BytePairEmbeddings for OOV words. Default initialization of BytePairEmbeddings class has dimension of embedding as 50. However, returned tensors are of size 100. Same for dimensions of size 200 and 300, returned tensor is 400 and 600.
Could not figure out the reason for this.
Sample code:

`from flair.embeddings import BytePairEmbeddings`
`embedding = BytePairEmbeddings('en', dim=300)`
`sentence = Sentence('The grass is green .')`
`embedding.embed(sentence)`
`for token in sentence:`
`    print(token)`
`    print(token.embedding.shape)`

Output:

Token: 1 The
torch.Size([100])
Token: 2 grass
torch.Size([100])
Token: 3 is
torch.Size([100])
Token: 4 green
torch.Size([100])
Token: 5 .
torch.Size([100])

Can you please help?

**Comment by stefan-it** [comment]
@san7988 Imagine your input token is `playing`. After applying BPE it is converted into subtokens like `play` and `##ing`. The current BPEPairEmbeddings then use the embedding vectors from both the first subword (`play`) and the last subword (`##ing´) and concatenates them. The result then is a `d * 2` embedding vector.

You can find the relevant lines here:

https://github.com/zalandoresearch/flair/blob/master/flair/embeddings.py#L417

**Comment by alanakbik** [comment]
To add to @stefan-it 's answer this is a way of dealing with the fact that each word may be split into a variable number of subtokens, but we always want the same length embedding vector for each token. A common strategy is to use only the first subtoken for an embedding, or only the last subtoken. In our case, we use both first and last subtokens for the final embedding, so the embedding length is always twice the subtoken embedding length.  

@stefan-it posted an evaluation of different strategies a while back for another embedding (see #547) and also found first and last subtoken to work well.

**Comment by san7988** [comment]
Got it. So I guess, if I have to use the embeddings of size 300, I'll just take the embedding of first subtoken.
