### ISSUE TITLE
suggestion: CRF transition matrix

### ISSUE THREAD

**Issue by davidsbatista** [zalandoresearch/flair#726]
given a trained `tagger` object, one can quickly get the CRF transition matrix with this code:

```
for to_idx, row in enumerate(tagger.transitions):
    for from_idx, column in enumerate(row):
        print(tagger.tag_dictionary.get_item_for_index(from_idx), tagger.tag_dictionary.get_item_for_index(to_idx), column.item())
    print()
```

I was about to open a PR to add this to the SequenceTagger, but I thought it would be much better to have it in a nice ASCII format, or some other format. Anyone has suggestions on how to better display/output this matrix, or even if this is totally irrelevant and shouldn't be added?

Best,
David

**Comment by alanakbik** [comment]
Some users will surely find this useful so we'd appreciate a PR :)

**Comment by davidsbatista** [comment]
any suggestions on how to present the matrix, simple print statement, output to a JSON?

**Comment by alanakbik** [comment]
I'm personally not a big fan of JSONs readability and find simple prints often more readable. But I really do not have a strong opinion here.

**Comment by stefan-it** [comment]
Great idea, what do you think about this:

![image](https://user-images.githubusercontent.com/20651387/57770947-bd902280-7711-11e9-87f4-81d69014348f.png)

**Comment by stefan-it** [comment]
So just one extra dependency would be needed (`tabulate`) , and it seems to be a lightweight one :)

**Comment by davidsbatista** [comment]
[PR#730](https://github.com/zalandoresearch/flair/pull/730/files)

**Comment by alanakbik** [comment]
Feature is now in master branch (see PR #730) and will be part of 0.4.2 release - thanks @davidsbatista!
