### ISSUE TITLE
Chunk doesnt provide an output

### ISSUE THREAD

**Issue by cliffordgreen** [zalandoresearch/flair#739]
When running the chunking method the same way one would run the POS tagging to the NER, the chunking doesn't provide an output, do you have to define the classification of chunks?

example

`from flair.data import Sentence
from flair.models import SequenceTagger

sentence = Sentence('I am currently looking for John, Rob is down the street running to the Post Office, not really sure why')

tagger = SequenceTagger.load('chunk')

tagger.predict(sentence)
print(sentence)
print('The following chunk tags are found:')
for entity in sentence.get_spans('chunk'):
    print(entity)`

output is

Sentence: "I am currently looking for John, Rob is down the street running to the Post Office, not really sure why" - 20 Tokens
The following chunk tags are found:

**Comment by cliffordgreen** [comment]
when running chunking the same way one would run NER or POS, the chunk method doesnt return chunks or labels.

**Comment by alanakbik** [comment]
Hello @cliffordgreen thanks for posting the code to reproduce! The problem lies in the name of the tag the tagger predicts, i.e. you are looking for 'chunk' spans, but it predicts 'np' spans. This is admittedly a bit confusing so perhaps we can make this more clear. 

Anyway, here is the code snippet that works: 

```python
from flair.data import Sentence
from flair.models import SequenceTagger

sentence = Sentence('I am currently looking for John, Rob is down the street running to the Post Office, not really sure why')

tagger = SequenceTagger.load('chunk')

print(f'this tagger predicts the {tagger.tag_type} tag')

tagger.predict(sentence)
print(sentence)
print('The following chunk tags are found:')
for entity in sentence.get_spans('np'):
    print(entity) 
```

Hope this helps!

**Comment by cliffordgreen** [comment]
thanks!
