### ISSUE TITLE
Bert embeddings producing empty vectors

### ISSUE THREAD

**Issue by elyase** [zalandoresearch/flair#760]
**Describe the bug**
When I try to get a sentence embedding using BERT the output is an empty tensor

**To Reproduce**

``` python
import flair
document_embeddings = flair.embeddings.BertEmbeddings('bert-base-uncased')
sentence = flair.embeddings.Sentence('The grass is green .')
document_embeddings.embed(sentence)
sentence.get_embedding()
```
output:
```
# tensor([])
```
**Expected behavior**
A non empty list of numbers

**Environment (please complete the following information):**
 - OS [Linux]:
 - Version [flair-0.4.1]:

**Additional context**
Tested with several BERT models and both on CPU and GPU.

**Comment by stefan-it** [comment]
Hi @elyase,

This method just retrieves the embedding for each in the sentence:

```python
for token in sentence.tokens:
  print(token.get_embedding())
```

Should then output the following:

```bash
tensor([-0.0323, -0.3904, -1.1946,  ...,  0.1305, -0.1365, -0.4323])
tensor([-0.3973,  0.2652, -0.1337,  ...,  0.3715,  0.1097, -1.1625])
tensor([ 0.1374, -0.3688, -0.8292,  ...,  0.2533,  0.0294,  0.4293])
tensor([-0.7722, -0.1152,  0.3661,  ...,  0.1575, -0.0682, -0.7661])
tensor([ 0.1441, -0.1772, -0.5911,  ..., -1.4830,  0.1995, -0.0112])
```

But you can do the following to get "real" document embeddings:

```python

real_document_embeddings = flair.embeddings.DocumentPoolEmbeddings([flair.embeddings.BertEmbeddings('bert-base-uncased')])

real_document_embeddings.embed([sentence])

print(sentence.embedding)
```

This should output:

```bash
tensor([-0.1841, -0.1573, -0.4765,  ..., -0.1140,  0.0268, -0.3886])
```

Example was taken from [here](https://github.com/zalandoresearch/flair/issues/321).

I hope that helps :)

**Comment by elyase** [comment]
@stefan-it  That's helpful thanks!
