### ISSUE TITLE
TypeError: 'PosixPath' object is not subscriptable

### ISSUE THREAD

**Issue by Dhanachandra** [zalandoresearch/flair#770]
`TypeError                                 Traceback (most recent call last)

<ipython-input-19-1a4cdefda8f1> in <module>()
     13                              train_file='trainData1.txt',
     14                              dev_file='testData1.txt')
---> 15 trainer = ModelTrainer.load_from_checkpoint(Path('gdrive/My Drive/Colab Notebooks/Cli_flair/resources/BT7l/checkpoint.pt'), corpus)
     16 #trainer = ModelTrainer.load_from_checkpoint(Path('resources/taggers/example-ner/checkpoint.pt'), corpus)
     17 trainer.train('gdrive/My Drive/Colab Notebooks/Cli_flair/resources/BT7l',

/usr/local/lib/python3.6/dist-packages/flair/trainers/trainer.py in load_from_checkpoint(cls, checkpoint, corpus, optimizer)
    371     ):
    372         return ModelTrainer(
--> 373             checkpoint["model"],
    374             corpus,
    375             optimizer,

TypeError: 'PosixPath' object is not subscriptable`

**Comment by Nivek92** [comment]
If you still need a solution or someone else is facing the same problem, here is a possible solution, though it would be great if it would be fixed instead.

```
checkpoint = torch.load('checkpoint.pt')
    model = TextClassifier(
        document_embeddings=checkpoint["document_embeddings"],
        label_dictionary=checkpoint["label_dictionary"],
        multi_label=checkpoint["multi_label"],
    )
model.load_state_dict(checkpoint["state_dict"])
checkpoint['model'] = model
trainer = ModelTrainer.load_from_checkpoint(checkpoint, corpus)```

**Comment by alanakbik** [comment]
Closing issue since answered by @Nivek92 (thanks!) but feel free to reopen if there's more questions.
