### ISSUE TITLE
Calculating F1 score

### ISSUE THREAD

**Issue by reza1615** [zalandoresearch/flair#774]
would you please add some code to the documentation which helps us to calculate F1 score for BIO test and train files?
I want to have a comparison between Prepared Datasets by flair and Trained Model by myself. so I need to inject test data to the model and get the f1 score like [here](https://machinelearningmastery.com/how-to-calculate-precision-recall-f1-and-more-for-deep-learning-models/)

**Comment by CamielK** [comment]
You can call the tagger evaluate method on a list of sentences from the corpus to get these results.
```Python
from flair.datasets import ColumnCorpus
from flair.models import SequenceTagger

corpus: ColumnCorpus = ColumnCorpus(path_to_BIO_corpus, column_format=columns)

tagger: SequenceTagger = SequenceTagger.load('ner')
result, _ = tagger.evaluate(corpus.test)
print(result.detailed_results)
```
This works for any corpus or tagger. Simply change the path or name of the model/corpus.

**Comment by reza1615** [comment]
@Cameilk: Thank you for reply. 
would you please tell me a:b means a,b? I didnt see this syntax in python

**Comment by CamielK** [comment]
**variable: type = value**
It allows you to define a type hint for the variable (since [Python 3.6](https://www.python.org/dev/peps/pep-0526/#status)). It is not required but it can be useful in some scenario's

**Comment by alanakbik** [comment]
@CamielK thanks for answering this and preparing the example!

**Comment by Ayush-iitkgp** [comment]
A small correction:
Instead of 
`result, _ = tagger.evaluate(corpus.test)
`
we need 
`result, _ = tagger.evaluate([corpus.test])
`

**Comment by OguzKircicek** [comment]
I have a problem. 

Problem : RuntimeError: The expanded size of the tensor (300) must match the existing size (0) at non-singleton dimension 1.  Target sizes: [9, 300].  Tensor sizes: [9, 0]
