### ISSUE TITLE
Getting tagwise accuracy/fscore metrics in sequence tagger

### ISSUE THREAD

**Issue by mnishant2** [zalandoresearch/flair#783]
I am training a multi-class sequence tagger. How to get various evaluation ma=etrics like accuracy and fscore for each tag separately?

**Comment by CamielK** [comment]
https://github.com/zalandoresearch/flair/issues/774#issuecomment-498562991

**Comment by alanakbik** [comment]
@mnishant2 as @CamielK pointed out you can use the evaluate function of the tagger to do this: 

```python
from flair.datasets import ColumnCorpus
from flair.models import SequenceTagger

corpus: ColumnCorpus = ColumnCorpus('path/to/your/corpus', column_format={0: 'text', 1: 'ner'})

tagger: SequenceTagger = SequenceTagger.load('ner')
result, _ = tagger.evaluate(corpus.test)
print(result.detailed_results)
```

Closing this issue for now, but feel free to reopen if you have more questions!

**Comment by Ayush-iitkgp** [comment]
A small correction:
Instead of
`result, _ = tagger.evaluate(corpus.test)
`
we need
`result, _ = tagger.evaluate([corpus.test])`

**Comment by Beam-coder** [comment]
> ```python
> from flair.datasets import ColumnCorpus
> from flair.models import SequenceTagger
> 
> corpus: ColumnCorpus = ColumnCorpus('path/to/your/corpus', column_format={0: 'text', 1: 'ner'})
> 
> tagger: SequenceTagger = SequenceTagger.load('ner')
> result, _ = tagger.evaluate(corpus.test)
> print(result.detailed_results)
> ```

Hello, I tried to use this code @alanakbik with correction `tagger.evaluate([corpus.test])` suggested by @Ayush-iitkgp . But, there was an AttributeError:

```
2022-01-18 17:21:04,377 Reading data from data_folder\simple_test
2022-01-18 17:21:04,377 Train: None
2022-01-18 17:21:04,377 Dev: None
2022-01-18 17:21:04,377 Test: data_folder\simple_test\column format_test.txt
2022-01-18 17:21:04,994 loading file C:\Users\xxx\.flair\models\ner-french\7363c68d2342aef796cf73c7a5a598c2786b051a5bcbd1152d32e6a100b63ce9.203314314706e4ef730093277621572fc37d926fdf95f0c7623c840ff4ac664c
Sentence: "Sam Houston restait à la maison"   [− Tokens: 6  − Token-Labels: "Sam <B-PER> Houston <I-PER> restait à la maison"]
Traceback (most recent call last):
  File "D:\xxx\accuracy.py", line 18, in <module>
    result, _ = tagger.evaluate([corpus.test], gold_label_type='ner', mini_batch_size=1, out_path=f"predictions.txt")
  File "D:\xxx\venv\lib\site-packages\flair\nn\model.py", line 217, in evaluate
    datapoint.remove_labels('predicted')
  File "D:\xxx\venv\lib\site-packages\torch\utils\data\dataset.py", line 87, in __getattr__
    raise AttributeError
AttributeError

Process finished with exit code 1
```

Any help?
