### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by Aditya715** [zalandoresearch/flair#786]
I'm trying to build my own Name Entity Model for a non-Latin language and I'm using ModelTrainer Class for the training but there came an error as AsssertionError. Also the training starts from bad epoch 0 and then AssertionLoss. I'm using 3 sentences in train.txt, 1 in dev and 1 in test. Just to check whether it works or not.

**Comment by alanakbik** [comment]
Hello @Aditya715 - it should normally work depending on which embeddings you are using since not all embeddings support all languages. There should not be an assertion error. Could you paste the full training snippet and share your training files?

**Comment by Aditya715** [comment]
I'm using gensim embedding that is already made. Can you make me understand the dataset format for an non-latin language. Should the entities as I-PER is converted in the same non-latin language too.

**Comment by alanakbik** [comment]
You can check for instance the dataset that gets downloaded to '`~/.flair/datasets/wikiner_russian`' when you run: 

```python
russian = WIKINER_RUSSIAN()
print(russian.train[4])
```

A sentence from this dataset looks like this: 

```console
На	PR	O
престол	S	O
было	V	O
решено	V	O
пригласить	V	O
немецкого	A	O
принца	S	O
Вильгельма	S	I-PER
фон	S	I-PER
Ураха	S	I-PER
.	SENT	O
```

So you don't need to convert the tags or anything else. The format is the same for a non-latin langauge as for a latin language.

**Comment by Aditya715** [comment]
S to denote Noun in Russian Dataset but in Engish dataset it is denoted as NNP. Is POS tag is not important to make an NER model.

**Comment by alanakbik** [comment]
In most cases including Flair the POS tag information is actually not used for NER. Prediction directly goes from text to NER tag. So the fact that different languages have different POS tags makes no difference in this case.

**Comment by Aditya715** [comment]
Should the sentences need to grammatically correct? Can I use a corpus of just locations to train the model?

**Comment by Aditya715** [comment]
Thanks for the help it worked for me
