### ISSUE TITLE
Tutorial 7: Training a model - Sample code needs correction (post release 0.4.2)

### ISSUE THREAD

**Issue by aayushsanghavi** [zalandoresearch/flair#794]
**Describe the bug**

Release 0.4.2 changes the model loading mechanism. As per the docs

> it removes the load_from_file() methods, which are now part of the load() method

The sample code in [Tutorial 7](https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_7_TRAINING_A_MODEL.md) uses `SequenceTagger.load_from_file()` and `TextClassifier.load_from_file()` methods instead of the new `load()` method to load an already trained model for evaluation.

**Comment by alanakbik** [comment]
Good point, thanks! Will make the change!

**Comment by alanakbik** [comment]
Changes made - thanks again for reporting!
