### ISSUE TITLE
Disabling test set usage

### ISSUE THREAD

**Issue by Henry-E** [zalandoresearch/flair#796]
It seems odd that during training the model is continuously evaluated on both the dev and test set. This is not really the purpose of a test set? Is there any easy way of disabling test set usage, either at the corpus input processing level, or during training. Looking at the [ColumnCorpus](https://github.com/zalandoresearch/flair/blob/master/flair/datasets.py#L20) class it doesn't seem like this is possible but I may have missed something.

**Comment by alanakbik** [comment]
Yes you're right, test set evaluation should be disabled during training and only executed after the training is complete. I'll put in a PR for this!
