### ISSUE TITLE
Checkpoints

### ISSUE THREAD

**Issue by Aditya715** [zalandoresearch/flair#808]
How to use check point to train a model in flair? I am working on flair NER but this is too slow, I am scared if my system fail there is no checkpoints to save my work till now.

**Comment by alanakbik** [comment]
You can enable checkpointing by setting `checkpoint=True` in the `ModelTrainer`:

```python
trainer: ModelTrainer = ModelTrainer(tagger, corpus)
trainer.train('your/folder',
    checkpoint=True,
)
```

This will write out `checkpoint.pt` model files at the end of each epoch. You can load this checkpoint with the code as illustrated in the [tutorial](https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_7_TRAINING_A_MODEL.md#resuming-training):

```python
# load checkpoint
checkpoint = tagger.load_checkpoint(Path('your/folder/checkpoint.pt'))
trainer = ModelTrainer.load_from_checkpoint(checkpoint, corpus)

# resume training
trainer.train('your/resume/folder',
              checkpoint=True)
```

**Comment by Aditya715** [comment]
Yup I found it. Thanks for all your help alanakbik

**Comment by david-waterworth** [comment]
Note this has moved to https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_TRAINING_MORE.md
