### ISSUE TITLE
Classifier seems to get basic tasks wrong?

### ISSUE THREAD

**Issue by alvisanovari** [zalandoresearch/flair#815]
```
from flair.models import TextClassifier

classifier = TextClassifier.load('en-sentiment')

sentence = Sentence('I hate you!')

# predict NER tags
classifier.predict(sentence)

# print sentence with predicted labels
print(sentence.labels)
```

The result is [POSITIVE (0.5075260400772095)].

If I change the sentence to 'I hate this!'. The result switches to [NEGATIVE (0.60359787940979)] (more accurate).

Am I failing to take something into account when classifying sentiment or is this a bug? 

Thanks!

**Comment by stefan-it** [comment]
Hi @alvisanovari,

the `Sentence` object expects a tokenized text by default. So just use  `Sentence('I hate you !')` (4 tokens now!) or use `Sentence(text='I hate you!', use_tokenizer=True)` (also 4 tokens, because it uses the internal tokenizer).

Then the prob. changes to `[POSITIVE (0.5702767372131348)]`, but is still postive.

**Comment by alvisanovari** [comment]
But it shouldn't be positive?

**Comment by alanakbik** [comment]
Hi @alvisanovari sorry for getting back so late - yes I agree the classification of the sentiment model needs to be improved. One problem is that we train this on movie reviews, so the sentiment is domain specific to movie reviews. Another is that we did not do much parameter selection for this model. 

For the next release of Flair, I'd like to find a better sentiment dataset to train on and train a better model.  If you know any good datasets for this, do let me know :)

**Comment by alvisanovari** [comment]
Gotcha.

I'd say yeah if you can add any reddit dataset where people use casual terminology, it would be make your model more robust. Not sure if there is a labeled dataset though.

Another idea, since it failed on such a basic case, is to do a simple TF-IDF / naive bayes analysis and have a percentage probability coming from that (10-20%?). You could even vary this percentage based on the length of the sentence i.e. give higher probability for shorter sentences where there is (literally) less room for nuance. This might help with cases like these and the additional compute should be minimal.
