### ISSUE TITLE
Non-deterministic behaviour for BERT embeddings

### ISSUE THREAD

**Issue by angeloziletti** [zalandoresearch/flair#816]
**Describe the bug**
I am using FLAIR (great software, thanks a lot!) to get BERT embeddings. 

For a given input, I get different BERT embeddings every time I run the code.

This might be a PyTorch related issue (https://github.com/huggingface/pytorch-pretrained-BERT/issues/695) 

Is there a way to get deterministic BERT embeddings using FLAIR?

**Comment by stefan-it** [comment]
Hi @angeloziletti ,

could you provide a short code snippet that shows how you use the BERT embeddings?

**Comment by angeloziletti** [comment]
I just found out that in my code there was an operation that did not mainted the order of the words in a sentence (I overlooked that before because I was using word2vec). That was causing the problem.

BERT embeddings are indeed deterministic within FLAIR.

Apologies for the confusion, and thanks a lot for your fast reply.
