### ISSUE TITLE
Pretrained GloVe model - what was it trained on? And is it cased?

### ISSUE THREAD

**Issue by danielchalef** [zalandoresearch/flair#821]
The pretrained GloVe model (available via `WordEmbeddings`) is downloaded from an AllenNLP S3 bucket. What was the model was trained on? And it is cased or not?

Thanks!

**Comment by alanakbik** [comment]
Hello @danielchalef it's actually one of our S3 buckets, so not hosted at AllenNLP. The folder is named `alan-nlp` (i.e. that's my folder :)), not `allen-nlp`.

The default GloVe vectors are the one computed by [Stanford](https://nlp.stanford.edu/projects/glove/), namely the 6B vectors with 100 dimensions.

**Comment by danielchalef** [comment]
Heh, cool. :-)  Thanks for clarifying!
