### ISSUE TITLE
Add support for XLNet

### ISSUE THREAD

**Issue by stefan-it** [zalandoresearch/flair#822]
Hi,

XLNet is a new pre-training method for NLP, that adopts some ideas from the Transformer-XL architecture and was published today:

[XLNet: Generalized Autoregressive Pretraining for Language Understanding](https://arxiv.org/abs/1906.08237).

I just read in the `pytorch-pretrained-BERT` repo, that they're [planning to integrate](https://github.com/huggingface/pytorch-pretrained-BERT/issues/705) it 😍

So whenever an implementation is available there, I would like to add a new embedding class `XLNetEmbeddings` so that it can be used in `flair` for downstream tasks.

**Comment by Hellisotherpeople** [comment]
I am extremely interested in this!

**Comment by vprelovac** [comment]
+1 for this

**Comment by alanakbik** [comment]
Yes that would be awesome!

**Comment by saj1919** [comment]
Huggingface just released this -> https://github.com/huggingface/pytorch-transformers. 
Would like to see the implementation here as well .. hope the development is on track !!

**Comment by MarcioPorto** [comment]
Should this be closed since https://github.com/zalandoresearch/flair/pull/941 has been merged?

**Comment by alanakbik** [comment]
Yes, good point! :)

**Comment by abeermohamed1** [comment]
Hi @stefan-it  and @alanakbik 
Could you please advise how to use this?

**Comment by alanakbik** [comment]
I am not sure if there are XLNet embeddings for Arabic, check here: https://huggingface.co/models?search=xlnet 

But you can use any Arabic BERT model from this list: https://huggingface.co/models?search=arabic 

You can load any model you find here with the `TransformerWordEmbeddings` or `TransformerDocumentEmbeddings` classes, depending on whether you want to embed words or documents: 

```python
    embeddings = TransformerWordEmbeddings(
        model=' asafaya/bert-base-arabic',
    )

```

**Comment by abeermohamed1** [comment]
Thank yiu

> I am not sure if there are XLNet embeddings for Arabic, check here: https://huggingface.co/models?search=xlnet
> 
> But you can use any Arabic BERT model from this list: https://huggingface.co/models?search=arabic
> 
> You can load any model you find here with the `TransformerWordEmbeddings` or `TransformerDocumentEmbeddings` classes, depending on whether you want to embed words or documents:
> 
> ```python
>     embeddings = TransformerWordEmbeddings(
>         model=' asafaya/bert-base-arabic',
>     )
> ```

Thank you @alanakbik unfortunately there is no pretrained Arabic XLNET model on huggingface. I already tried Arabic BERT model since while
