### ISSUE TITLE
Setting flair.device to a different GPU than default (0) is overwritten by ELMoEmbeddings when using them in DocumentPoolEmbedding

### ISSUE THREAD

**Issue by helmersl** [zalandoresearch/flair#823]
**Problem**
Specified GPU ('cuda:1') was ignored in `DocumentPoolEmbedding` since I'm using `ELMoEmbeddings` together with flair embeddings and in line 570 of `embeddings.py`, the device to use for elmo embeddings is set to 0 so after all, the embeddings were still done on 'cuda:0'

**Idea**
Make it possible to initialize elmo embeddings with a specific GPU. I adapted `embeddings.py` accordingly and now it's working fine. Happy to contribute with a PR in case the necessity is seen by others as well !

**Comment by alanakbik** [comment]
Hello @helmersl yes a PR would be great since other users have reported problems with this in the past as well!
