### ISSUE TITLE
zipfile.BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by WSTC2007** [zalandoresearch/flair#847]
```python
from flair.models import SequenceTagger
from flair.data import Sentence
tagger = SequenceTagger.load('ner-fast')
sentence = Sentence('George Washington went to Washington .')
tagger.predict(sentence)
```
When I run the above code, the error is: zipfile.BadZipFile: File is not a zip file.
Can someone help me? Thx.

**Comment by alanakbik** [comment]
Hm strange, this code works on my side. Can you give us more details on your setup?

**Comment by logan-siyao-peng** [comment]
I also face this issue when I try to import flair on my docker pyenv environment. (However, it works in my local MacOS environment).
I tried rm ~/.cache/pip and pip install flair --no-cache-dir but neither helped. 
Not sure what is wrong with this case.
