### ISSUE TITLE
Gpu Utilization is not 100%.

### ISSUE THREAD

**Issue by Aditya715** [zalandoresearch/flair#851]
I want to use full of my gpu but it's using max to max 75% I want to use maximum of my gpu so that I'll get quicker output. I'm not able to find any solution.

**Comment by alanakbik** [comment]
Hello @Aditya715 we believe the current way we structure Flair has CPU bottlenecks that prevent full GPU utilization. For instance, to go from an embedded Sentence object to a tensor we must always iterate over all Tokens, get their embeddings and make a tensor for the upper layers of the network, which presumably costs CPU while the GPU idles. This is something that's been on our list to optimize for a long while, but we haven't yet had enough time to really look into this problem and formulate solutions. Any help from the community is greatly appreciated here :)

**Comment by Aditya715** [comment]
Okay if I got some lead I'll surely tell you.
