### ISSUE TITLE
Simple TaggedCorpus Deprecation Update

### ISSUE THREAD

**Issue by aychang95** [zalandoresearch/flair#856]
The experiments markdown file _resources/docs/EXPERIMENTS.md_ includes the deprecated "TaggedCorpus" objects, which should be replaced with the more robust "Corpus" object.

 _flair/data_fetcher_ also has most documentation referring to the deprecated "TaggedCorpus" object.

Running any of the experiments will fail with a "cannot import..." error obviously.

Will initialize a pr if no objections

**Comment by aychang95** [comment]
p.s. Experiment breaking commit was at GH-232: Add new Corpus interface over TaggedCorpus and MultiCorpus

**Comment by alanakbik** [comment]
Sure, we'd appreciate a PR!
