### ISSUE TITLE
An example dataset for ColumnCorpus

### ISSUE THREAD

**Issue by antgr** [zalandoresearch/flair#867]
In  Tutorial 6: Loading Training Data
there is the following code example
```
from flair.data import Corpus
from flair.datasets import ColumnCorpus

# define columns
columns = {0: 'text', 1: 'pos', 2: 'ner'}

# this is the folder in which train, test and dev files reside
data_folder = '/path/to/data/folder'

# init a corpus using column format, data folder and the names of the train, dev and test files
corpus: Corpus = ColumnCorpus(data_folder, columns,
                              train_file='train.txt',
                              test_file='test.txt',
                              dev_file='dev.txt')
```
i would like to run this code, but I need a dataset. Could you tell me a dataset that this code could run on?

**Comment by antgr** [comment]
I  downloaded NER-de-train.tsv, NER-de-dev.tsv, NER-de-test.tsv
and using this code snippet,
```
from flair.data import Corpus
from flair.datasets import ColumnCorpus

# define columns
columns = {0: 'Sentence', 1: 'Word', 2: 'Pos', 3: 'Tag'}

# this is the folder in which train, test and dev files reside
data_folder = '.'

# init a corpus using column format, data folder and the names of the train, dev and test files
corpus: Corpus = ColumnCorpus(data_folder, columns,
                              train_file='NER-de-train.tsv',
                              test_file='NER-de-test.tsv',
                              dev_file='NER-de-dev.tsv')
```
I see the following
print (len(corpus.train))
2
print (len(corpus.test))
print (len(corpus.dev))
1
1
BUT:
rint(corpus.train[0])
print(corpus.train[0].to_tagged_string('ner'))
Sentence: "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25" - 25 Tokens
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25

Can you provide some guidance?

**Comment by alanakbik** [comment]
Hello @antgr, I think the problem is your definition of the columns. You need to define a 'text' column for the surface forms, and an 'ner' column for the ner tags. Try like this: 

```python
# define columns
columns = {0: 'idx', 1: 'text', 2: 'ner', 3: 'ner_nested'}
```

Does this work for you?

**Comment by antgr** [comment]
yes! the output:
Sentence: "Firmengründer Wolf Peter Bree arbeitete Anfang der siebziger Jahre als Möbelvertreter , als er einen fliegenden Händler aus dem Libanon traf ." - 22 Tokens
Firmengründer Wolf <B-PER> Peter <I-PER> Bree <I-PER> arbeitete Anfang der siebziger Jahre als Möbelvertreter , als er einen fliegenden Händler aus dem Libanon <B-LOC> traf .
Thank you @alanakbik 
(for your help and for this beautiful library!)
