### ISSUE TITLE
about model download

### ISSUE THREAD

**Issue by wen-fei** [zalandoresearch/flair#874]
hi, thanks for your great job. when I run the sample code, I get this `requests.exceptions.ConnectionError: HTTPSConnectionPool(host='s3.eu-central-1.amazonaws.com', port=443): Max retries exceeded with url: /alan-nlp/resources/models-v0.4/NER-conll03-english/en-ner-conll03-v0.4.pt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x1a255b3358>: Failed to establish a new connection: [Errno 61] Connection refused',))`

I searched issues and found that I am not the only one facing similar issues. I guess that you design requesting a url for a model download while calling the interface for saving install time.
This is a good idea, but ignores some special cases.  I suggest that provide a way to specify the local model configuration path, such as json files or function parameters to solve this problem.
Thank you very much.
Looking forward to improvement!

**Comment by alanakbik** [comment]
Hello @wen-fei can you download the model from here: https://alan-nlp.s3.eu-central-1.amazonaws.com/resources/models-v0.4/NER-conll03-english/en-ner-conll03-v0.4.pt
 
If so, you could pass the path to the model file to the `load()` method to load the model.

**Comment by wen-fei** [comment]
thanks for your replay.  i solved this problem same with your suggestion by VPN. Unfortunately, this library is not friendly enough for developers in mainland China

**Comment by zwacm** [comment]
Hi, @alanakbik .
I am using flair-0.2.1, where I can download the model similar to **en-ner-conll03-v0.4.pt**?

Thank you in advance.

**Comment by alanakbik** [comment]
This is the link: https://alan-nlp.s3.eu-central-1.amazonaws.com/resources/models-v0.2/NER-conll03--h256-l1-b32-%2Bglove%2Bnews-forward%2Bnews-backward--v0.2/en-ner-conll03-v0.2.pt 

However, this model has a bug, so its better to use the current model.

**Comment by JoyHuYY1412** [comment]
> Hello @wen-fei can you download the model from here: https://alan-nlp.s3.eu-central-1.amazonaws.com/resources/models-v0.4/NER-conll03-english/en-ner-conll03-v0.4.pt
> 
> If so, you could pass the path to the model file to the `load()` method to load the model.

excuse me, how to use the load function?

**Comment by zwacm** [comment]
@JoyHuYY1412 I just put the file in the path of resource/taggers.

**Comment by shadylpstan** [comment]
I am trying to download this, but it opens a webpage instead of download the file.
https://nlp.informatik.hu-berlin.de/resources/models/pt-pos-clinical/pucpr-flair-clinical-pos-tagging-best-model.pt

**Comment by shadylpstan** [comment]
I am trying to download this, but it opens a webpage instead of download the file.
http://nlp.informatik.hu-berlin.de/resources/models/pt-pos-clinical/pucpr-flair-clinical-pos-tagging-best-model.pt
