### ISSUE TITLE
AttributeError: 'WordEmbeddings' object has no attribute 'embeddings'

### ISSUE THREAD

**Issue by jind11** [zalandoresearch/flair#880]
After executing the following codes:
'''
from flair.models import SequenceTagger
tagger = SequenceTagger.load('multi-ner')
print(tagger)
'''
I got this error:
'''
AttributeError: 'WordEmbeddings' object has no attribute 'embeddings'
'''
Something should be wrong in extracting the embeddings from the pretrained multi-ner model.

**Comment by alanakbik** [comment]
Hello @jind11 I was not able to reproduce the error. Have you found out more or got it working on your end?

**Comment by myaldiz** [comment]
@alanakbik The same thing happened to me as well, you need to download models from the web, it does not occur if you trained those models.

**Comment by CoderChang** [comment]
Got the same error when loading 'ner-fast', with torch==1.0.0 and flair==0.4.2

**Comment by alanakbik** [comment]
Ah thanks for the details! I'll try to reproduce!

**Comment by alanakbik** [comment]
Can reproduce, thanks! Will fix with a PR.
