### ISSUE TITLE
OSError: HEAD request failed when using TREC_6

### ISSUE THREAD

**Issue by ReacherAppDev** [zalandoresearch/flair#893]
When I use the example code from tutorial 7 I get this error.

> OSError: HEAD request failed for url http://cogcomp.org/Data/QA/QC/train_5500.label with status code 301.

This is the code:
from flair.data import Corpus
from flair.datasets import TREC_6
from flair.models import TextClassifier
from flair.trainers import ModelTrainer
from flair.embeddings import WordEmbeddings, FlairEmbeddings, DocumentRNNEmbeddings

corpus: Corpus = TREC_6()
label_dict = corpus.make_label_dictionary()
word_embeddings = [
    WordEmbeddings('glove')
]
document_embeddings = DocumentRNNEmbeddings(
    word_embeddings,
    hidden_size=512,
    reproject_words=True,
    reproject_words_dimension=256,
)

classifier = TextClassifier(document_embeddings, label_dictionary=label_dict)

trainer = ModelTrainer(classifier, corpus)

trainer.train(
    'resources/taggers/ag_news',
    learning_rate=0.1,
    mini_batch_size=32,
    anneal_factor=0.5,
    patience=5,
    max_epochs=150
)

**Comment by stefan-it** [comment]
Oh no, the url was changed :( However, it seems that the dataset is now located under:

https://cogcomp.seas.upenn.edu/Data/QA/QC/train_5500.label

I'll prepare a PR for that url change, thanks for reporting it1

**Comment by ReacherAppDev** [comment]
Thanks for the quick help ;)

**Comment by Mark-L6n** [comment]
Hi, I just installed flair with 'pip install flair' and am getting the same error message, 16 days after the merge.  I assume that simply a new version for pip hasn't been released yet.
In the meantime, is there a way to pass an argument with the correct URL, that will override the hard-coded URL?

**Comment by alanakbik** [comment]
@Mark-L6n yes we haven't released another version on pip yet. You can install master directly in a fresh virtual environment like this: 
```console
pip install --upgrade git+https://github.com/zalandoresearch/flair.git 

```
