### ISSUE TITLE
Lstm Learnable Hidden State

### ISSUE THREAD

**Issue by myaldiz** [zalandoresearch/flair#897]
Hi,

As far as I noticed, Lstm module in Pytorch initializes hidden state as zero. [In some blog posts](https://r2rt.com/non-zero-initial-states-for-recurrent-neural-networks.html) (also by Hinton), it is recommended to initialize it as a learnable parameter. I believe between initial hidden state and next hidden states, the network got affected less by covariate shift when the initial hidden state learned. It would be great if it can be implemented, it may boost accuracy.

Thanks.

**Comment by alanakbik** [comment]
Yes would be interesting to try out - care to do a PR for this? :)

**Comment by myaldiz** [comment]
[pull request sent](https://github.com/zalandoresearch/flair/pull/899)
