### ISSUE TITLE
How to pre-train elmo or other embedding using flair?

### ISSUE THREAD

**Issue by songtaoshi** [zalandoresearch/flair#918]
Hello ,it seems that in the tutorial, there is only the tutorials about the language model training of flair embedding but there is not other tutorials about how to train other language model

**Comment by songtaoshi** [comment]
@alanakbik

**Comment by alanakbik** [comment]
For training ELMo, you could check out the AllenNLP project - we use `allennlp` as a dependency for the `ELMoEmbeddings` so the training should be performed there.

**Comment by songtaoshi** [comment]
Thanks a lot ！！！
