### ISSUE TITLE
Can i use flair for NER without POS taggings for custom embeddings NER

### ISSUE THREAD

**Issue by pratapaprasanna** [zalandoresearch/flair#920]
Hi all,

I have gone through the docs and i have a doubt regarding the data in NER training.

https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_6_CORPUS.md

Can i Have my training data set with out pos ?

can i have group of words under one entity ? in my training data set i have group of words like 

eg:
If this is the sentence ```I will complete the assigned work by afternoon and will inform you ```  in my data set i have ```work by afternoon``` as ```Today``` and ``` inform you ``` as ```empathy``` and dont have a POS tagging in this case how can i proceed further and send in data for NER in Flair?

and i have the dataset in hindi mix english format so i am assuming the embeddings for that will be sufficient to train the NER ..

Can anyone help me in giving me a way forward and clarify any mistake in my assumption

Thanks in advance

**Comment by alanakbik** [comment]
Hello @pratapaprasanna POS tags are not needed and in fact will be ignored by Flair if you provide them. The library directly goes from text to the tags you wish to predict and requires no extra features. So if you don't have POS tags, you only need to change the `column_format` to reflect this in the `ColumnCorpus` and everything should be good to go!

**Comment by pratapaprasanna** [comment]
Hi @alanakbik  

Thanks for the reply so my column format  columns = {0: 'text',  1: 'ner'} so  text  column can i send the group of words which are named as NER  right

i.e is the below format valid ?

say this is my sentence in my training data set 

```kitne mein likha aapko this rupay discount de do to phir aap jama kar den```

```kitne mein likha aapko this rupay O```
discount de do. Today
to phir O
aap jama kar den Empathy
```
Thanks

**Comment by alanakbik** [comment]
Hello @pratapaprasanna each line has to be exactly one word, so a group of words is not possible. If your entity spans several words, you can encode this using BIO tags. Essentially the first word of the entity gets the B- tag (for "begin") and the other words in the entity gets the I- tag (for "in").

**Comment by pratapaprasanna** [comment]
thanks @alanakbik will try to do it.

**Comment by Aariciah** [comment]
> POS tags are not needed and in fact will be ignored by Flair if you provide them. The library directly goes from text to the tags you wish to predict and requires no extra features.

Hi @alanakbik, is there a way to include pos tags for ner finetuning improvement?
