### ISSUE TITLE
How do you apply a function to each doc in the corpus?

### ISSUE THREAD

**Issue by BernierCR** [zalandoresearch/flair#925]
So I'm trying to use corpus now. I would like to apply a text cleaning function to each doc/sentence of my corpus, before embedding. Is there a way to do this with flair? Or must I clean before loading up the corpus? 

It makes sense that people would want to insert functionality in between generating the corpus and doing the embedding. Is this possible yet? None of the tutorials mention such a thing. 

Thanks, great work. I will keep integrating features while I wait for an answer.

**Comment by alanakbik** [comment]
@BernierCR current you would have to do such cleaning beforehand. We could proably add better ways for inserting cleaning functions in the future, so I'm very much open for suggestions here.

**Comment by BernierCR** [comment]
OK thanks. The cleaning beforehand method works for me. It would still be nice to have something nicer here, but I'd rather have you work on more important things. 

I could maybe develop a feature myself, but the process to release such a feature publicly isn't very fast and I've never been through it before, so don't expect anything soon. I appreciate this library and want to contribute something though.

**Comment by alanakbik** [comment]
Ok great - we'll keep it in mind as we develop and of course always welcome contributions. I'll close for now, but feel free to reopen if there's more questions/comments.
