### ISSUE TITLE
Please Offer a README to show how to manually download all the File and put it in the right place

### ISSUE THREAD

**Issue by 312shan** [zalandoresearch/flair#930]
@alanakbik 
In case of specific network condition , it would be suffer to download  the resource file need for task.
can flair offer a readme to show how to manually download all the resource file like emb_file,model_file  ....and extract / put it where?? I think a lot of issue can be solve by provide such readme.
thank you!

**Comment by BernierCR** [comment]
I think you can figure this out by looking at the code. Then, if you like, make your own README. Would be nice.
