### ISSUE TITLE
no visualisation returned with Plotter

### ISSUE THREAD

**Issue by SiewLinYap** [zalandoresearch/flair#935]
I try to check how the plot_training_curves and plot_weights results look like, but nothing is returned/displayed even though the script finished running with no error. After checking the raw script, notice the plots are  actually auto-saved as png in the resources sub-folder, instead of displaying the plots towards the end. Perhaps it is good to have the enhancement done by displaying the plots after we called the plotter functions or at least a note returned to inform where the images are saved.Thanks.

![Screenshot 2019-07-30 at 11 26 26 AM](https://user-images.githubusercontent.com/35646492/62099014-43f2e400-b2bf-11e9-868e-37c9ec6e6f82.png)

**Comment by SiewLinYap** [comment]
Just to add on : When re-run the whole data in GCP, there are charts displayed towards the end together with saved plots. But the same notebook when run locally will have no chart displayed. Is there any step that I need to take note if to run it locally?

**Comment by alanakbik** [comment]
@SiewLinYap that's a good point. Would you be interested in doing a PR to add this?

**Comment by SiewLinYap** [comment]
@alanakbik I've amended the source code in training_curves.py locally, so it will show the chart at my end instead of switching to GCP each time using it. Will be doing a PR for this :)

![Screenshot 2019-08-01 at 2 31 24 PM](https://user-images.githubusercontent.com/35646492/62270943-e2bb4400-b469-11e9-98a4-b06d3fe3092a.png)

**Comment by alanakbik** [comment]
Closed by #943
