### ISSUE TITLE
Can anyone provide me the resources to fully understand about Flair NER?

### ISSUE THREAD

**Issue by Wickky** [zalandoresearch/flair#942]
I would like to train **NER** model. 
I have read that flair ner uses **Bi-LSTM-CRF** under the hood. Is there any paper that describes it? Is that the same with Bi-LSTM-CRF mentioned in other papers?
And how are the embeddings used in NER training differ? 
How can these embeddings enhance our models? 
Please also provide useful links to read all about these. 
Thank you so much in advance!

**Comment by alanakbik** [comment]
Hello @Wickky we provide a description of the tagger in the [papers linked on the github page](https://github.com/zalandoresearch/flair#comparison-with-state-of-the-art). The best place to start would be our COLING 2018 paper.

**Comment by amitbcp** [comment]
@alanakbik I was trying to reuse, Flair On-notes NER. The tutorial says it's based on 12 Named Entities, but I am not able to check the annotations for them. 
Can you please help to show where to get the named entities and their definitions.
For eg, spacy has the following on On-Notes https://spacy.io/api/annotation#named-entities

**Comment by alanakbik** [comment]
Hello @amitbcp the SpaCy link is in fact correct. Our model has all 18 ontonotes classes listed there. This is an error in our documentation that we should correct.

**Comment by alanakbik** [comment]
@amitbcp just corrected the documentation so closing this issue, but feel free to reopen if you have more questions.
