### ISSUE TITLE
Question about FlairEmbeddings implementation

### ISSUE THREAD

**Issue by BaptisteBlouin** [zalandoresearch/flair#944]
I'm wondering, in your class FlairEmbeddings, in _add_embeddings_internal function : 
What did you get from the LanguageModel to set embeddings ?

From what I see, the sentence you pass to the language model look like this : 
`padded = '{}{}{}{}'.format(start_marker, sentence_text, end_marker, pad_by * ' ')`

And after that to get the embeddings from  the LM hiddens states you initialize your offsets by : 
`offset_forward: int = extra_offset`  
and
`offset_backward: int = len(sentence_text) + extra_offset`

And you run throw your sentence by : 
`offset_forward += len(token.text)`

...

`embedding = all_hidden_states_in_lm[offset, i, :]`

...

`offset_forward += 1`
`offset_backward -= 1`
`offset_backward -= len(token.text)`

So my question is, with this initialization of offset, what did you get from the LM ?

In the case of forward LM it look like you get the value of the space after the last char of the token and in the case of backward LM you get the value of the space after the first ( cause it's revert ) char of the token.
I just thought that you get the last and the first ( forward and backward ) char of the token and you concat them. And in that case you should initialize your offset like this : 

`offset_forward: int = extra_offset -1`  

and

`offset_backward: int = len(sentence_text) -1 + extra_offset`

I think there is something I do not understand and I hope you can enlighten me on the subject.

**Comment by alanakbik** [comment]
Hello @BaptisteBlouin yes you're absolutely right we currently take the hidden state after the whitespace. With your code, we would take the hidden state directly after the last character which would also be ok. We briefly looked at both variants a while back and found that it made very little difference, so we just used the current version. But we never did a real evaluation, so maybe we should add a parameter to control this behavior to the class in case somebody would like to do this evaluation.

**Comment by BaptisteBlouin** [comment]
Hello @alanakbik , 
Thank you for your answer. As you said, I haven't notice a relevant difference in my experiment. 
I have just noticed this fact when i was trying to get the hidden state of each character for a char based ner model. Thanks for your reply and your work it's really helpful ! Keep up the good work.
