### ISSUE TITLE
Dev / Test Clarification / Bug

### ISSUE THREAD

**Issue by BernierCR** [zalandoresearch/flair#947]
Hello. So I'm trying to build my models and see which changes are improving things, ie, doing data science. 

However, I have noticed that the test.tsv file is full of dev data, not test data as expected. What could be going on here? 

Thanks.

**Comment by anjapago** [comment]
I have noticed a related issue during training, my dev loss and test loss are always exactly the same. I did not have the test.tsv with any dev data as far as I could tell though.
 
2019-08-02 23:09:40,845 DEV : loss 0.16333866119384766 - score 0.7631
2019-08-02 23:09:42,795 TEST : loss 0.16333866119384766 - score 0.7631

I have looked in the code, to me it seems these numbers should not always be the same? Thanks.

**Comment by alanakbik** [comment]
@BernierCR @anjapago thanks for spotting this - definite bug.
