### ISSUE TITLE
new line character

### ISSUE THREAD

**Issue by j55liang** [zalandoresearch/flair#950]
Looks like \n is considered a character in the dictionary for the news-forward lm, so can I use this character in the ner task? If so when I use ColumnCorpus object to load my own corpus won't the newline character be mistaken as an indicator for a new sentence or new tag? How can I use it as a character in my corpus?

**Comment by alanakbik** [comment]
Hello @j55liang I think this is a duplicate of #737: Essentialy, one workaround would be to replace the newline character with some special symbol so that you can still use the ColumnCorpus format.
