### ISSUE TITLE
the num_worker parameterLanguageModelTrainer

### ISSUE THREAD

**Issue by ArmandGiraud** [zalandoresearch/flair#960]
**Is your feature/enhancement request related to a problem? Please describe.**
the num_worker parameters in LanguageModelTrainer seems to be hard coded.

**Describe the solution you'd like**
it would be great to set it as a parameter of the LanguageModelTrainer class.

**Additional context**
I am currently fine tuning  FlairEmbeddings on a relatively small corpus ~30 M words which fits on memory (so I use a single split). 
For some reason the datasets seems to be preprocessed between each epoch. As a results training takes more time between each Epoch than the actual training time of a single epoch.  Any advice on this particular scenario would be helpful.

Btw great work with this package it is very helpful 👍 If you need any help, I would be happy to contribute.

**Comment by alanakbik** [comment]
@ArmandGiraud you're right - I'll put in a PR to make this a parameter. In the meantime, you can still change this parameter by doing: 

```python
# train your language model
trainer = LanguageModelTrainer(language_model, corpus)

# set the num workers
trainer.num_workers = 10

# train away
trainer.train('resources/taggers/language_model',
              sequence_length=10,
              mini_batch_size=10,
              max_epochs=10)
```

**Comment by ArmandGiraud** [comment]
thanks @alanakbik !
