### ISSUE TITLE
Better handling of CSV files

### ISSUE THREAD

**Issue by basaldella** [zalandoresearch/flair#966]
**Is your feature/enhancement request related to a problem? Please describe.**
Currently, `CSVClassificationCorpus` only supports CSV files formatted with Python's default CSV library format, i.e. Excel's CSV format. It would be nice to be able to specify custom headers, delimiters, and escape characters, so that one would be able to load any CSV without having to pre-process it beforehand.

**Describe the solution you'd like**
It would be sufficient to add the option to pass `fmtparams` to `csv.reader`.

**Additional context**
I encountered this problem while trying to load non-Excel formatted CSV files.

**Comment by alanakbik** [comment]
closed by #967 - thanks @basaldella for adding this!
