### ISSUE TITLE
Hyperopt params

### ISSUE THREAD

**Issue by BernierCR** [zalandoresearch/flair#970]
Hello. I can't figure out how to send some training parameters to the TextClassifierParamSelector. Specifically, I can't pass embeddings_storage_mode= 'gpu'. 

How do you do this? Thanks.

**Comment by isanvicente** [comment]
Hi, 
    from what I see in file parameter_selection.py,  https://github.com/zalandoresearch/flair/blob/63b118394f10de1cec4902a3c1e48529627d732c/flair/hyperparameter/param_selection.py#L108 

 trainer takes its parameters from the  `training_params` variable, which accepts parameters defined in the hyperparameter/parameter.py file `TRAINING_PARAMETERS` list: https://github.com/zalandoresearch/flair/blob/63b118394f10de1cec4902a3c1e48529627d732c/flair/hyperparameter/parameter.py#L31

'embeddings_storage_mode' is not among those, so my guess is you would have to add it both into the parameter class definition and into the aforementioned array. 
For example,
    1. add `EMBEDDINGS_STORAGE_MODE : "embeddings_storage_mode"` to [line 29](https://github.com/zalandoresearch/flair/blob/63b118394f10de1cec4902a3c1e48529627d732c/flair/hyperparameter/parameter.py#L29)  
    2. add `Parameter.EMBEDDINGS_STORAGE_MODE.value,` to [line 43](https://github.com/zalandoresearch/flair/blob/63b118394f10de1cec4902a3c1e48529627d732c/flair/hyperparameter/parameter.py#L43) ( TRAINING_PARAMETERS definition).

I haven't tested it myself, but you could give it a try. 

Cheers.

**Comment by BernierCR** [comment]
Thanks, I'll look into that.

**Comment by BernierCR** [comment]
Thanks. 

It was an =, not a :, and I had to remember to also add this to the search space, but after that, it worked.
