### ISSUE TITLE
PyTorch-Transformers: add documentation for new embeddings

### ISSUE THREAD

**Issue by stefan-it** [zalandoresearch/flair#971]
Documentation for the following embeddings should be added:

* `BertEmbeddings`
* `OpenAIGPTEmbeddings`
* `OpenAIGPT2Embeddings`
* `TransformerXLEmbeddings`
* `XLNetEmbeddings`
* `XLMEmbeddings`
* `RoBERTaEmbeddings`

Pooling operations and scalar mix should also get an extra section :)

**Comment by Sakib-Ar-Rahman** [comment]
Have these embeddings been included in version 0.4.2? I was following the documentation but not sure if these have made it into the flair package yet. Is there any way I can use these? I don't seem to be able to import the following:

- `OpenAIGPT2Embeddings`
- `XLNetEmbeddings`
- `XLMEmbeddings`
- `RoBERTaEmbeddings`

**Comment by alanakbik** [comment]
@Sakib-Ar-Rahman we're planning a release of 0.4.3 sometime next week. In the meantime you can install in a fresh virtual environment like this: 

```console
pip install --upgrade git+https://github.com/zalandoresearch/flair.git
```

**Comment by stefan-it** [comment]
Documentation was added for version *0.4.3* 🤗
