### ISSUE TITLE
Loading checkpoint issue

### ISSUE THREAD

**Issue by DecentMakeover** [zalandoresearch/flair#973]
A clear and concise description of what you want to know.
Trying to fine tune a model , using this

	  DeprecationWarning)
	Traceback (most recent call last):
	  File "fine_tune_custom.py", line 68, in <module>
	    trainer: ModelTrainer = ModelTrainer.load_from_checkpoint(checkpoint_file=Path('data/pretrained/checkpoint.pt'),model_type='SequenceTagger',corpus=corpus)
	TypeError: load_from_checkpoint() got an unexpected keyword argument 'checkpoint_file'

Any suggestions on how i can fix this?

**Comment by alanakbik** [comment]
You are using an old way of loading checkpoints I think. This is the current way:

```python
checkpoint = tagger.load_checkpoint(Path('data/pretrained/checkpoint.pt'))
trainer = ModelTrainer.load_from_checkpoint(checkpoint, corpus)
```

Here is [more info](https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_7_TRAINING_A_MODEL.md#resuming-training) on this.

**Comment by DecentMakeover** [comment]
@alanakbik  Thanks for the quick reply ,Works like a charm.
