### ISSUE TITLE
Bert embedding

### ISSUE THREAD

**Issue by GGchen1997** [zalandoresearch/flair#977]
flair 0.4.0
ubuntu16
I want to use BertEmbeddings base cased but the code "embedding = BertEmbeddings("bert-base-uncased")" can not download the embedding because of my network. So I have downloaded it and what should I do to load the embedding? I tried to pass the path to BertEmbeddings but this did not work.

**Comment by GGchen1997** [comment]
I solved the problem.

**Comment by alanakbik** [comment]
Cool, could you share the solution? Others might be interested in this.
