### ISSUE TITLE
Reproducing 'ner-ontonotes' model results

### ISSUE THREAD

**Issue by ydovzhenko** [zalandoresearch/flair#98]
Hi! Thank you for the great work! Could you give a couple of clarifications for purposes of benchmarking:

- Do you use your own script to assemble the ontonotes data (i.e. go from *_conll to eng.*)?
- Do you use gold annotations as well as auto annotations?

**Comment by alanakbik** [comment]
Hi! Thanks for your interest! 

- Yes, we used our own script to assemble the data into a CoNLL-03-style column format, after using the CoNLL-12 scripts to create train, dev and test splits.
- What do you mean by gold and auto annotations?

**Comment by ydovzhenko** [comment]
After obtaining conll files, did you discard any of them? For example, there are files with 'gold' and 'auto' in the name: 'gold' annotated by humans, 'auto' annotated automatically. 

In particular, I am trying to understand exactly which data was used to compute the reported F1 score.

**Comment by alanakbik** [comment]
We used the files that end with '_gold_conll'. If I remember correctly, they are produced by one of the CoNLL-12 scripts. They are formatted like this: 

```
tc/ch/00/ch_0049   0   0    Actually    RB   (TOP(S(ADVP*)     -    -   -    A      *      *    (ARGM-DIS*)     -
tc/ch/00/ch_0049   0   1           I   PRP           (NP*)     -    -   -    A      *      *             *    (32)
tc/ch/00/ch_0049   0   2         've   VBP           (VP*    have  01   -    A      *    (V*)            *      -
tc/ch/00/ch_0049   0   3        been   VBN           (VP*      be  01   -    A      *      *           (V*)     -
tc/ch/00/ch_0049   0   4          up    IN           (PP*      -    -   -    A      *      *        (ARG2*      -
tc/ch/00/ch_0049   0   5          to    IN           (PP*      -    -   -    A      *      *             *      -
tc/ch/00/ch_0049   0   6     Holland   NNP         (NP*)))     -    -   -    A   (GPE)     *             *)     -
tc/ch/00/ch_0049   0   7      before    RB       (ADVP*)))     -    -   -    A      *      *    (ARGM-TMP*)     -
tc/ch/00/ch_0049   0   8           .     .             *))     -    -   -    A      *      *             *      -
```

From these files we then retrieve the NER span annotation from column 11.

**Comment by ydovzhenko** [comment]
Thank you for clarifying! We were able to reproduce your reported results now.
