### ISSUE TITLE
Changing learning rate when finetuning

### ISSUE THREAD

**Issue by DecentMakeover** [zalandoresearch/flair#985]
A clear and concise description of what you want to know.
When i try to change the learning rate of a model while finetuning, 

        from flair.trainers import ModelTrainer
	checkpoint = tagger.load_checkpoint(Path('data/models/exp_18/checkpoint.pt'))
	trainer = ModelTrainer.load_from_checkpoint(checkpoint, corpus)
	learning_rate = 0.1

	import pdb;pdb.set_trace()
	for param_group in trainer.optimizer.param_groups:
	        param_group['lr'] = learning_rate

i get 

    AttributeError: type object 'SGD' has no attribute 'param_groups'

Any suggestions on how to fix this will be helpful.
Thanks

**Comment by alanakbik** [comment]
You can set the learning rate in the `train()` method, so this should work (on master branch not Flair 0.4.3 release):

```python
# restore checkpoint
from flair.trainers import ModelTrainer
trainer = ModelTrainer.load_checkpoint('resources/taggers/local-test-0/checkpoint.pt', corpus)

# new learning rate
learning_rate=0.123

# train with new learning rate
trainer.train(learning_rate=learning_rate)
```

**Comment by DecentMakeover** [comment]
Thanks a lot.
