### ISSUE TITLE
Architectural differences between pretrained models 'ner' and 'ner-ontonotes'

### ISSUE THREAD

**Issue by TheArowanaDude** [zalandoresearch/flair#989]
Are the neural network architectures and word embeddings setup for the pretrained models for conll2003(ner) and ontonotes(ner-ontonotes) datasets the same? 

Thanks in advance!

**Comment by alanakbik** [comment]
They are pretty much exactly the same, the only difference is that we used GloVe embeddings for CoNLL and FastText embeddings for Ontonotes. See the training configurations [here](https://github.com/zalandoresearch/flair/blob/master/resources/docs/EXPERIMENTS.md).
